### ISSUE TITLE
Capital of Tokelau?

### ISSUE THREAD

**Issue by JohnHBrock** [axelboc/anki-ultimate-geography#100]
The deck currently lists the capital of Tokelau as Atafu, but [Wikipedia lists the capital as Nukunonu](https://en.wikipedia.org/wiki/Tokelau), with a footnote that, "Each atoll has its own administrative centre." Wikipedia also says the capital rotates yearly between the three atolls that make up Tokelau, but the page that Wikipedia cites doesn't seem to support that claim. In fact, the [CIA World Factbook](https://www.cia.gov/library/publications/the-world-factbook/fields/312.html#TL) says, "the meeting place of the Tokelau Council rotates annually among the three atolls; this tradition has given rise to the somewhat misleading description that the capital rotates yearly between the three atolls; in actuality, it is the seat of the government councilors that rotates since Tokelau has no capital".

Thoughts on how to best incorporate this information into the deck? I suggest changing the `Capital` field to be `"(no capital)"`, and `Capital info` to `"There is no capital; the meeting place of the Tokelau Council rotates annually among the three atolls that make up Tokelau."`

See #20 for related discussion.

**Comment by axelboc** [comment]
Changing to `(no capital)` is not an option, because the reverse card _Capital > Country_ would not make sense. How about removing the capital entirely and changing the _Country info_ field to the following ?

> Dependent territory of New Zealand. Tokelau has no official capital; the meeting place of the Tokelau Council rotates annually.

**Comment by JohnHBrock** [comment]
Makes sense, I'll submit a PR in the next day or two.
