### ISSUE TITLE
The body of water called "Hudson Bay" in the deck is actually called "Hudson's Bay"

### ISSUE THREAD

**Issue by ArjunPanickssery** [axelboc/anki-ultimate-geography#102]

**Comment by axelboc** [comment]
**Hudson Bay** seems to be the official name, according to [Wikipedia](https://en.wikipedia.org/wiki/Hudson_Bay):

> Hudson Bay [...] (sometimes called Hudson's Bay, usually historically) is a large body of saltwater [...]
