### ISSUE TITLE
Define criteria for inclusion of non-sovereign states

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#11]
On one hand, I feel like some notes are quite obscure, like Saba, Sint Eustatius, or Mount Athos, and on the other hand it seems like the deck is missing a few obvious ones, like Hawaii, Tasmania, or Svalbard. What makes a card worth adding?

- Relying solely on governance status (e.g. overseas territory, etc.) is clearly not working as adding `Saint Helena, Ascension and Tristan da Cunha` is out of the question... and it doesn't cover Hawaii, Java, the Balkan Peninsula, etc.
- General awareness would be ideal, but it's not easy to quantify and very arbitrary...
- Perhaps a combination of surface area and population size?
- Historical significance as well, maybe?
- How practical it is to learn for an English speaker? Again... highly arbitrary.

**Comment by code-hunger** [comment]
I'd suggest to keep countries with interesting or just more notable facts about them which would help learners to memorize them.

For example, apart from just *Autonomous region of Finland* the Aland Islands can be described as consisting of more than 6700 islands; or some facts could be added like that after the Crimean war the area was demilitarized.

Another example is Abkhazia, currently presented as an *Independent state claimed by Georgia*. This could be extended to [what wikipedia states](https://en.wikipedia.org/wiki/Abkhazia): *Abkhazia declared its independence after its war with Georgia in 1992–1993 [...] Russia recognised the independence of Abkhazia on 26 August 2008*.
Not necessarily this information, maybe something else, but something historical or unique about the given state.

**Comment by axelboc** [comment]
Good point, it would make the cards a lot more interesting and a little easier to remember. However, when I cleaned up the deck and decided to go with very short governance info, I was a bit concerned that adding more info would make the deck a little more difficult to keep up to date, and especially more prone to complaints. The other downside of longer country information is that they seem to get in the way after you've read them a couple of times. You could also argue that someone who's having trouble learning a card because of its lack of context could just do a Google search. I'm playing devil's advocate here, but I still think these are all arguments worth considering.

Assuming we decide to expand some country info, we'd have to keep them concise and make sure they're well written... which takes time. If other people think this is a good idea (with a comment, or a thumbs up or other emoji on @code-hunger's comment). I'd also love to hear what others think about using something like this as the criteria for inclusion of non-sovereign states:

> [...] countries with interesting or just more notable facts about them which would help learners to memorize them.

**Comment by code-hunger** [comment]
> adding more info would make the deck a little more difficult to keep up to date, and especially more prone to complaints (about the truthfulness of the facts given).

Storing historical information shouldn't cause such problems as by definition history never changes (unless God decides to do `git reset --hard` and `git push --force`, which we hope won't happen)

Geographical facts won't be an issue, either. For example, about Saba [from Wikipedia](https://en.wikipedia.org/wiki/Saba): *is a Caribbean island [...]. It consists largely of the potentially active volcano Mount Scenery*.

However, the *actually* interesting part is that  the volcano is "*at 887 metres (2,910 ft) the highest point of the entire Netherlands.*" This is controversary, though, as we don't know how the borders of the Netherlands would change in the future. To "fix" this we can just add "by 2017".

Like you said, Saba is quite obscure (especially if you never heard about it before). Additional information puts Saba in a context that helps learners memorize it much faster.

> someone who's having trouble learning a card because of its lack of context could just do a Google search

You're right, and that's what *I* did :)

> Assuming we decide to expand some country info, we'd have to keep them concise and make sure they're well written... which takes time. If other people think this is a good idea (with a comment, or a thumbs up or other emoji on @code-hunger's comment), I'll happily kick start the work.

I don't think enough people will read this to form an objective feedback;
in the process of learning I will also be interested in adding such information.

**Comment by axelboc** [comment]
Okay, I've defined the criteria for inclusion as "reasonably easy to memorise" and added it to the README:

> For a card to be included, it must be reasonably easy to memorise. This excludes places with very long or unpronouncable names, or with little geographical and historical significance.

Closing this issue and opening a new one to deal with expanding the country information field of cards that are difficult to learn.
