### ISSUE TITLE
East Sea / Sea of Japan

### ISSUE THREAD

**Issue by jamesdeluk** [axelboc/anki-ultimate-geography#112]
Perhaps edit the "Sea of Japan" to include its other name, "East Sea".

Source: https://en.wikipedia.org/wiki/Sea_of_Japan_naming_dispute (and an angry Korean girlfriend)

**Comment by axelboc** [comment]
Since the Wikipedia article is still titled _Sea of Japan_, I'll leave it as is but I'll mention the naming dispute in the _Country info_ field.
