### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by 1e3oss** [axelboc/anki-ultimate-geography#119]
Hello,

I would like to contribute by translating to French.
From what I understand of issues #52 and #64 for the German translation, I should make a PR with additionnal columns in src/data.csv for:
```csv
 Country:fr,"Country info:fr",Capital:fr,"Capital info:fr","Capital hint:fr","Flag similarity:fr"
```
Do you need something else to be able to make a release ?
I would be able to maintain the French version.

Thank yo for your work

**Comment by axelboc** [comment]
Amazing news!! :tada:

I'm French, so I've been looking forward to this for a long time. :smile: I'll be able to review the translations and help with the maintenance. 

- You've got it right regarding the columns. Each French column should come right after its corresponding German column.
- Nothing else needed for the release. Once you're done, I'll update the README and deck description and release v3.2 (it's long overdue).
- If the whole thing is going to take you a while (i.e. more than a couple of weeks), you may want to open partial PRs (one with the new columns added, then a few for the translations). It will reduce the risk of running into conflicts.
- From an editorial standpoint, just follow the English version as closely as you can: concise and to the point ; no redundant articles ; capital letter at the start and full stop at the end of each sentence. Do make sure to add a space before semi-colons, though... :smile:
- Perhaps do start with a PR with only a few translations, so we can double check that the style is right?

Thank you!! :100: Looking forward to releasing this new translation!

**Comment by 1e3oss** [comment]
Nice :smile: 
French here too, as you could expect !

- Alright for column order and style
- Let's reach 3.2 !
- I think opening a first PR to double check format and style is a good idea. I'll then open PRs depending on progress. I might do it all over the week-end, or take some time. Anyway I think I will translate about 20 entries per commit to help reviewing. The first one would be England to Bulgaria. What do you think ?

Glad to help

**Comment by hobbes** [comment]
Hi there, I had a go at the French translation, please find the PR here:

https://github.com/axelboc/anki-ultimate-geography/pull/157

Comments welcome :-)
