### ISSUE TITLE
Flag similarities for extended deck <Country - Flag> template

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#132]
In issue #50, there was some [confusion](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-522241023) around the purpose of the current **_Flag similarity_ field**.

The field is used on the standard deck's **_Flag - Country_ template**, on the back side of the cards, to help users to **stop mixing up flags that look similar** over and over again. Typically, when a user is presented with the flag of Poland and guesses wrongly that it's the flag of Indonesia, they have the opportunity (with the help of the flag similarity information) to come up with a mnemonic to help them differentiate the two flags the next time they see either one of them.

In the case of the extended deck's **_Country - Flag_ template**, the situation is quite different. Remembering and **describing what a flag looks like** is a very different skill. From #50, it's clear that the _Flag similarity_ field is not providing the level of assistance needed for this template.

I've suggested adding a **hint field** on the front side of the cards, which could be revealed on demand by the user, to **list the countries with similar flags**. My thinking is that the hint could help jog the user's memory as to what the geometry and colours of the flags might be (as they might know what one of the other flags look like). And if they don't know what the geometry and colours of any of the flags in the group are at all, they will for sure once they see the answer and make the appropriate associations in their mind.

Am I onto something here? Is it worth adding a new hint field for the _Country - Flag_ template? Do you have any other suggestions or insights to help memorisation in the context of the _Country - Flag_ template?

**Comment by aplaice** [comment]
As you could probably guess from the fact that I "misused" the similarity descriptions for this purpose, I'm broadly in favour. :)

Some possible counter-arguments:

1. From an editing perspective, adding two more fields will make dealing `data.csv` as plain text (as opposed to in a spreadsheet or pseudo-spreadsheet (like VSC's extension or Emacs's Org Mode's tables)) even more unwieldy. However, especially if #129 is fixed, this might not be a major problem.

2. Hint fields are often "abusable". (Though in this, specific case, I don't think that seeing a list of countries with similar flags beforehand would be particularly harmful to memory formation.)

3. (As you mentioned in the other thread:) There are many different potential mnemonics for cards, and I'm not sure if promoting this particular set would be generally valuable.

**Comment by axelboc** [comment]
Ideally this could be done as a composition/extension, as discussed in https://github.com/ohare93/brain-brew/issues/4. That being said, since it's not gonna happen any time soon, I wouldn't be against adding an extra field for describing flags once we have Brain Brew... We can rediscuss this in due time and see if other people are interested.
