### ISSUE TITLE
Norwegian (bokmål) translation

### ISSUE THREAD

**Issue by Vages** [axelboc/anki-ultimate-geography#139]
Hi! I've got a Norwegian (bokmål; we have two written languages; it's complicated) version of the deck almost ready. I guess I'll just do the same thing as in #119 and add a column to the CSV?

**Comment by axelboc** [comment]
Great, thanks!

**Comment by Vages** [comment]
I think it'll be in by the end of today or tomorrow. Unfortunately, there are a lot of line changes in src/data.csv, but I'm doing my best to make sure there are no troubles.

I'm currently looking through all the Norwegian cards. Are there any further measures I can take to save you time in quality control before posting a PR? E.g. checking the diff of the built JSON-files in English and German?

**Comment by Vages** [comment]
And by the way, I have also made a node script to quote items with spaces in them, in case your favorite CSV editing tool (in my case, Google Sheets) exports without spaces on quoted items. Would you like me to include it? The script is below.

```javascript
#!/usr/bin/env node
const fs = require("fs");

const file = fs.readFileSync("./src/data.csv").toString();
const lines = file.split(/\r\n|\r|\n/);
const linesWithItemsContainingSpacesQuoted = lines
  .map(line => {
    const lineWithExtraCommaToTriggerAddLastSegment = `${line},`;
    let insideQuotes = false;
    let segmentStart = 0;
    let segments = [];
    for (let i = 0; i < lineWithExtraCommaToTriggerAddLastSegment.length; i++) {
      const currentCharacter = lineWithExtraCommaToTriggerAddLastSegment[i];
      if (currentCharacter === "," && !insideQuotes) {
        segments = [
          ...segments,
          lineWithExtraCommaToTriggerAddLastSegment.substring(segmentStart, i)
        ];
        segmentStart = i + 1;
      }
      if (currentCharacter === '"') {
        insideQuotes = !insideQuotes;
      }
    }
    return segments;
  })
  .map(line =>
    line
      .map(element => {
        const alreadyQuoted = element.startsWith('"');
        if (alreadyQuoted) {
          return element;
        }
        const hasSpace = element.indexOf(" ") > -1;
        if (hasSpace) {
          return `"${element}"`;
        }
        return element;
      })
      .join(",")
  );

const newContent = linesWithItemsContainingSpacesQuoted.join("\n");
fs.writeFileSync("./src/data.csv", newContent);
````

**Comment by axelboc** [comment]
For the quotes, you can run `composer index`. It's not the main purpose of the command, but it normalises quotes as a side effect.

Doing a diff of the output English and German decks to make sure they haven't changed would indeed be very helpful. CSV is really not the best format for managing translations, is it? 😄 As more translations come in, and to make it easier for people to contribute more translations, we'll most likely have to rethink the format in the near future.

**Comment by axelboc** [comment]
Forgot to mention that I was planning on finishing and merging PR #125 in the next couple of hours. You'll have to resolve a few conflicts and remove/add a couple of translations, sorry. Hope it won't be too much trouble...

Are you happy maintaining the Norwegian translation in the long term? I don't think I'll attempt any translating myself like I do for the German deck. Are you happy just watching the deck and adding translations in separate PRs as needed?

**Comment by Vages** [comment]
Great with the `composer index` tip! I think the tip could be added to `CONTRIBUTING.md`, as I'm probably not going to be the last to waste my time normalizing the quotes 😄 

Regarding the diffing: I think implementing some kind of snapshot tests for the decks would be great, so that the process won't have to be done manually. I'll make a separate issue for it.

I'm happy maintaining the Norwegian translation, as long as the workload stays as low as it seems now.

Won't be a problem with the merges; I'll just "redo" the changes in Google Sheets.
