### ISSUE TITLE
Automatic testing of decks to avoid unintentional edits

### ISSUE THREAD

**Issue by Vages** [axelboc/anki-ultimate-geography#142]
As mentioned by me in #139, we should have some kind of automatic tests for decks to avoid unintentional edits of other languages. In Jest, this is called snapshot testing for components.

Possible further work: Run automatic tests as a git commit hook, to avoid polluting commits.

**Comment by axelboc** [comment]
We discussed the idea of checking the escaping of `data.csv` in a CI workflow very briefly in https://github.com/axelboc/anki-ultimate-geography/issues/129#issuecomment-522727326. Our concern was mainly about creating a barrier to new contributors.

As with making unintentional edits of other languages, I feel like a better approach would be to make those edits impossible in the first place. In other words, the current CSV format is not adequate for managing translations. It was good to start with, but I think we need to consider switching to a more advanced internationalisation format/system/workflow.

**Comment by axelboc** [comment]
FYI, I've added a GitHub Action workflow in #171 to make sure `data.csv` is always well formatted. Seems to be working!

**Comment by axelboc** [comment]
It would be great to have a one-liner command (i.e. a script in `composer.json`) that we could run to output which columns have changed. We could then run it in GitHub Actions and output the result on every PR. If this sounds like a good idea, is anyone interested in having a crack at it?

**Comment by ukanuk** [comment]
With what I've learned while working on my Wikipedia checking script, I could easily write a script which compares two `data.csv` files and outputs which fields have changed. It could even output a new table with just the changed rows/columns in a CSV file. It appears the `pandas` library I'm using can even export to markdown. 

However, I've never integrated with Github, so I'm not sure how tightly I could integrate it with Github actions, e.g. whether it could automatically add a comment to the PR with the changed table in markdown, and whether it could automatically check the history to grab old/new versions of `data.csv` for comparison. 

In any case, isn't this pretty much obsolete with the proposed change in data format, from CSV to e.g. YAML? Since if every language is on a separate line, the integrated PR comparisons make unintentional edits obvious.

**Comment by axelboc** [comment]
> In any case, isn't this pretty much obsolete with the proposed change in data format, from CSV to e.g. YAML?

It will be yes. I'll just keep this issue open until the change is confirmed to go ahead.

**Comment by aplaice** [comment]
> However, I've never integrated with Github, so I'm not sure how tightly I could integrate it with Github actions, e.g. whether it could automatically add a comment to the PR with the changed table in markdown,

Unfortunately, based on what I had discovered when investigating a similar topic (checking the [CSV quoting](https://github.com/axelboc/anki-ultimate-geography/issues/188#issuecomment-560175285)) and in line with what you had also found (? I think — I can't find the relevant issue, at the moment), an action run on the filing of a third-party (i.e. not from a branch within the target repository) pull-request can't write comments...

> whether it could automatically check the history to grab old/new versions of data.csv for comparison

This it can, easily.

> >  In any case, isn't this pretty much obsolete with the proposed change in data format, from CSV to e.g. YAML?
> It will be yes. I'll just keep this issue open until the change is confirmed to go ahead.

I'm not sure — even after a switch to YAML it would still be quite useful (if not as essential) to have a summary of which languages and/or notes were modified.

**Comment by axelboc** [comment]
> I'm not sure — even after a switch to YAML it would still be quite useful (if not as essential) to have a summary of which languages and/or notes were modified.

True, true, but this is perhaps more on the topic of making PRs easier to review, than to avoid unintentional edits.

**Comment by axelboc** [comment]
Filing this one as waiting for a `better-deck-manager`. No point in improving our current set-up, since we've put a moratorium on new translations and we'll soonish switch to YAML, as discussed. I'll reopen once we have Brain Brew.
