### ISSUE TITLE
Ease commiting after export with custom settings

### ISSUE THREAD

**Issue by code-hunger** [axelboc/anki-ultimate-geography#15]
After I make my edits and I export the deck as JSON, I get quite a lot of differences with the repository file that don't need to be commited.

Lines like 'crowdanki_uuid', 'deck_config_uuid', custom settings like new cards/reviews per day, the media file list (some files are reordered), the font, 'mid' value, marked cards - all these lines need to be reset by hand one by one when adding the file for commit.
This is really annoying when I want to commit just a few changes to the deck.

I was about to write a script to do this but I found no easy way to `git add` by line programmatically. How do you deal with this problem?

If there was a way to split the file into multiple parts so that the card info is separated from the settings, I could .gitignore the other files but currently that's impossible.

**Comment by axelboc** [comment]
Yeah it's annoying... I don't get why the CrowdAnki plugin is exporting all this stuff, especially the custom settings. The media ordering is definitely an issue. Feel free to create an issue there, but I reckon the easiest for now would be to edit the JSON file directly.

**Comment by code-hunger** [comment]
I did it! A bash script to reset the first 792 lines (they hold the settings information).
https://gist.github.com/code-hunger/40d28682628186b8e7568da7a0645dcd
It works wonderfully. Now I just export the deck and run this script, and only the note changes are kept. I'm sure it'll make life a lot easier!
Closing the issue.
