### ISSUE TITLE
Visual answer type hints

### ISSUE THREAD

**Issue by Vages** [axelboc/anki-ultimate-geography#152]
I may be a bit dim, but I often miss what kind of answer is expected if I don't concentrate on reading the headline. I guess I'm not alone. Some visual indicator of the type of answer would be great.

An icon in front of the expected type of answer is an idea which I'll deliver a PR on shortly.

**Comment by axelboc** [comment]
That's a cool idea!

One concern would be about emojis not being available on all devices. Not sure that's still the case, these days, though... They also don't look the same everywhere. Looking at your PR, I feel like we could just as well use inline SVG icons in the templates. It would give us more freedom and guarantee the same rendering on all devices.

There are plenty of open source SVG icon/emoji libraries out there. I've just come across https://openmoji.org for instance, which has a few interesting emojis, like the [authority building](https://openmoji.org/library/#emoji=E093), or the [world map](https://openmoji.org/library/#search=map&emoji=1F5FA). They may be a bit too detailed for the size at which they will be displayed in the deck, though.

**Comment by axelboc** [comment]
I've added the `votes wanted` label to the issue. How does everyone else feel about the idea of having emojis/icons in the templates (in whichever format)?

**Comment by aplaice** [comment]
I'd vote for some small (visually and ideally memory-wise) SVG icons!

I feel that emojis are a bit too inconsistent between platforms (like @axelboc pointed out).

> inline SVG icons

Just to clarify, do you mean having the SVG "code" entirely included (inline) in the HTML/templates, (as opposed to just using the standard `<img src="foobar.svg" />` tag, with the actual SVGs bundled as part of the media in the deck)? If yes, I'm not sure if that'd be optimal:

1. Testing ~ a year ago inlined SVGs were somehow mangled by Ankidroid. (This might have changed).

2. It'd lead to messier diffs for the templates.

(PS Thanks @vages for the idea!)

**Comment by axelboc** [comment]
Arf damn, I was hoping inline SVGs were supported. SVG files bundled as media in the deck, sounds good, then. 👍

**Comment by ohare93** [comment]
I've been using @Vages's PR for the last week or so. At the start I did not like the Emojis in the cards, I thought they looked bad; now I simply do not notice them at all :slightly_frowning_face: Also the lack of an icon for the X -> Country cards bothers me aesthetically :slightly_smiling_face: :anger: 

I don't think they help me personally know which card type it is, though as I said in my comment in the PR I did not have this problem in the first place :sweat_smile: I think the new cloze templates are sufficient. If necessary perhaps each bottom title Capital/Map/Flag could have it's own colour/font/etc to make it stand out :thinking: just a thought

**Comment by aplaice** [comment]
Correction:

> (This might have changed).

Checking now with a random SVG from the internet, I've not noticed any problems with an SVG inlined within the template, on any of Desktop, Android or (old-ish) iOS.

I'm still not sure whether the advantages of inline SVG (mainly control over styling of sub-elements of the SVG) are worth it, though.

**Comment by ohare93** [comment]
Ahh, should have posted this here first! Just going to copy paste:

As I've been doing more of the extended deck I find I need something that accomplishes the goal of this PR more and more. It is sometimes very difficult to tell which question is being asked, if you are to answer Capital, Flag, or Location. Though I still maintain that just an emoji did not solve the issue (for me, at least). So I made the following updates to my own extended templates:

### Country -> Flag
![image](https://user-images.githubusercontent.com/1471350/73127539-22e72380-3fc2-11ea-9a20-f0372d113832.png)

### Country -> Map
![image](https://user-images.githubusercontent.com/1471350/73127547-372b2080-3fc2-11ea-8b13-2cfb43bd3162.png)

The big obvious shapes for the flag or the globe really help me get into the right headspace quickly, I am finding at least. The circle for the globe then turning into a square shaped map is asthetically displeasing, but I could not think of a better blank symbol for the Country -> Map, and was unwilling to add in an unreferenced (in a card) media file just to make it look nicer. 

What do you think @Vages, @axelboc? 😁

_Originally posted by @ohare93 in https://github.com/axelboc/anki-ultimate-geography/pull/153#issuecomment-578445070_

**Comment by aplaice** [comment]
This is a really cool idea!

> and was unwilling to add in an unreferenced (in a card) media file just to make it look nicer.

You're right that having an unreferenced media file is indeed an issue, as it would make importing it from the ankiweb Shared Deck page much harder. (There obviously are workarounds — having a "dummy" note with the media file or having the unreferenced media file referenced in one of the existing notes (but wrapped in a `<div style="display: none">`) — however, none of them are pretty...)

> The circle for the globe then turning into a square shaped map is asthetically displeasing,

Yeah, that might be slightly annoying.

Perhaps using something like this:

![empty mini-map](https://user-images.githubusercontent.com/16461345/73136241-ad279a00-404b-11ea-8547-a6e939709dd1.png)

might avoid this unaesthetic transition (and it might be sufficiently simple to include inline, without bloating the template excessively).

(If allowing an external media file were OK, I'd suggest something like this:

![1](https://user-images.githubusercontent.com/16461345/73136310-933a8700-404c-11ea-88ba-27eb92a43002.png)

)

(I'm not sure about the external rectangular border, in either case, since it isn't present in any of the actual maps, and besides it might be easy to confuse with the empty rectangle for the flag, which would completely beat the point of the exercise...)

**Comment by ohare93** [comment]
Sorry for the late reply @aplaice, thanks for the feedback.

>(I'm not sure about the external rectangular border, in either case, since it isn't present in any of the actual maps, and besides it might be easy to confuse with the empty rectangle for the flag, which would completely beat the point of the exercise...)

Yea, pretty much! 😅 Also the world map does not appear on all map fields, such as most Seas (such as Labrador) or certain autonomous cities (such as Melillia), so it would not be a universal standard anyways. I fear there is no answer which will please all asthetics! 😭 I am happy enough with my template change for the time being, but will leave this open for a while for someone else to suggest an alternative 👍

**Comment by aplaice** [comment]
> Also the world map does not appear on [...] most Seas (such as Labrador)

[It does now!](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-labrador_sea.png) :D 

Your point about Ceuta and Melilla (and the Pacific Island regions, the Balkans and Saint Helena — though I'm planning to suggest changes to the latter two) still stands, though.

**Comment by ukanuk** [comment]
I like the proposal from @ohare93, though I've modified it by replacing the circle's `border-radius: 50%;` with `border-radius: 35% / 50%;` to more closely match the inset world map. I also modified it to automatically scale down on smaller screens (images have `max-width: 100%`, which takes some extra work to replicate with div's), and also invert colors for Night Mode/Dark Mode. Here are the full changes:

![image](https://user-images.githubusercontent.com/59303202/74598537-8e4e7d80-50b6-11ea-804b-3a59ecd3a0e1.png)

**Comment by ukanuk** [comment]
> @ohare93 If necessary perhaps each bottom title Capital/Map/Flag could have it's own colour/font/etc to make it stand out 🤔 just a thought

I'd recommend changes to these colors regardless, as they're currently broken for night mode. If the group moves to non-grey colors entirely, then that fixes it night mode. But if the headings/extended notes stay grey, then night mode is improved by changing the CSS on `.type` and `.info` classes from `color: #333;` to `filter: contrast(70%);`. It appears the same in regular day mode, but dramatically improves night mode appearance.

AnkiDroid "Dark" Night theme with `color: #333;`
![image](https://user-images.githubusercontent.com/59303202/74598667-9a3b3f00-50b8-11ea-91da-8ec9c896aad4.png)

AnkiDroid "Dark" Night theme with `filter: contrast(70%);`
![image](https://user-images.githubusercontent.com/59303202/74598669-aa531e80-50b8-11ea-9ae7-db6dcfa03ab8.png)

**Comment by aplaice** [comment]
> they're currently broken for night mode. 

Please report this as a (separate) issue, as that definitely shouldn't be happening. 

FWIW with AnkiDroid 2.9.3, with `anki-ultimate-geography` from git, I get a readable contrast, both with the "dark" and "black" themes:

![black_theme](https://user-images.githubusercontent.com/16461345/74604717-c8bd1800-50c0-11ea-805c-a024d246168b.jpg)
![dark_theme](https://user-images.githubusercontent.com/16461345/74604718-c955ae80-50c0-11ea-85fd-b9a4c1b3406f.jpg)

(I also didn't encounter the problem you have, with any combination of AnkiDroid and `anki-ultimate-geography`, in the past.)

I don't know whose "fault" it is (AnkiDroid's, `anki-ultimate-geography`'s or Android's), but it might be worth investigating.

**Comment by ukanuk** [comment]
@aplaice I retract my claim about night mode.

It's broken on desktop with the latest 3.2 Release, but PR #173 fixes it for whenever the next release comes. Concerning AnkiDroid, that's my own dumb fault because of other styling I added while thinking about Issue #81. When testing styling from the 3.2 release and PR #173, my AnkiDroid dark mode works normally.

**Comment by josealberto4444** [comment]
For me, this was an issue at the beginning, now I mostly read what the card is asking. However, sometimes I think about the capital no matter what asked.

So my vote would go for having a visual hint, yes. I love both [@ohare93's suggestion](https://github.com/axelboc/anki-ultimate-geography/issues/152#issuecomment-578491048) and [@ukanuk's suggestion](https://github.com/axelboc/anki-ultimate-geography/issues/152#issuecomment-586665007). I think [@aplaice's suggestion](https://github.com/axelboc/anki-ultimate-geography/issues/152#issuecomment-578505089) is maybe too subtle (flag and map would share the rectangle). And, I also think emojis are not enough, I would keep skipping them.

**Comment by axelboc** [comment]
I had a bit of a play with some SVG graphics from [OpenMoji](https://openmoji.org/). I adapted this [flag emoji](https://openmoji.org/library/#emoji=1F3C1) and this [map emoji](https://openmoji.org/library/#search=map&emoji=1F5FA).

![Preview 2020-04-05 14-23-41](https://user-images.githubusercontent.com/2936402/78494002-9a1aff80-7749-11ea-88a8-e23d3ba3ae64.gif)

**Comment by ukanuk** [comment]
I really like the inline svg, I think it's the best method so far. Moreover it scales simply by adding CSS `max-width: 100%;`, and CSS can also change border color for night mode.

I'm not as fond of the modified OpenMoji designs, as I think it makes an ugly/intimidating wall of text in the card template, especially for people who don't already know to look for `<svg>...</svg>`. With the primary goal being an intuitive visual indicator of card type, a rectangle for the flag and a flattened-oval for the map seem fine to me.

Regardless, I think an inline SVG is the best method so far, and any of the proposed shapes will work. With my newfound Github powers, I would enjoy making a pull request for this once there's sufficient consensus :-)

<details>
  <summary>Front <i>Country - Flag</i> template</summary>

```html
{{#Flag}}
  <div class="value value--top">{{Country}}</div>
  {{#Country info}}<div class="info">{{Country info}}</div>{{/Country info}}

  <hr>

  <div class="type">Flag</div>
  <div class="image">
    <svg xmlns="http://www.w3.org/2000/svg" width="407" height="229" viewBox="0 0 407 229" class="image__placeholder"><path d="m0.5 0.5 l406 0l0 228l-406 0z"/></svg>
  </div>
{{/Flag}}
```
</details>

<details>
  <summary>Front <i>Country - Map</i> template</summary>

```html
{{#Map}}
  <div class="value value--top">{{Country}}</div>

  <hr>

  <div class="type">Location</div>
  <div class="image">
    <svg xmlns="http://www.w3.org/2000/svg" width="407" height="250" viewBox="0 0 407 250" class="image__placeholder"><path d="m283 0.5c167 56 163 195-0.29 249-72-0.084-72-0.51-158 0-164-54-167-194 0.29-249l158 0.07"/></svg>
  </div>
{{/Map}}
```

</details>

<details>
  <summary>Additional CSS</summary>

```css
.image__placeholder {
  max-width: 100%;
  height: auto; /* Required for webkit */
}

.image__placeholder path {
  fill: none;
  stroke: #333;
  stroke-width: 1;
}

.night_mode .image__placeholder path {
  stroke: #ccc;
}
```
</details>

![image](https://user-images.githubusercontent.com/59303202/78546535-8e5a3680-7838-11ea-8323-44c73312c7cd.png)

**Comment by aplaice** [comment]
I've just been testing out the designs. To possibly save somebody a tiny amount of time, a filtered search with `deck:"Ultimate Geography*" -is:due (card:3 or card:5 )` and a random selection order will give a convenient testing ground for how the cards would look when in use. (Don't forget to uncheck the "Reschedule cards based on my answers in this deck" box!)

I'm surprised that I *really* like the flag emoji that @axelboc suggested (I thought that I'd find it too "cutesy")!

The map emoji is OK (I don't dislike it), but I'm not too enthusiastic about it, either. Also, I agree with @ukanuk's point about a long SVG in the template being potentially annoying for anybody who wants to edit the templates for their own use (the flag emoji and @ukanuk suggestions are both short enough IMO).

<hr/>

@ukanuk suggestions are clear, simple and consistent with each other. (I appreciate the thought given to adapting for night mode!). 

My only remaining worry is about the rectangle for the flag being potentially interpretable (on a subconscious level — but that's what this whole issue is about) as referring to the map (unless and until the association between the map and the flattened oval is fully "absorbed"). However, I'm not sure how warranted this worry is.

<hr/>

Hence, I'd vote either for @ukanuk's combination (my first choice), or perhaps @axelboc's emoji flag together with @ukanuk's flattened oval (possibly with some editing for a consistent look).

**Comment by axelboc** [comment]
What about giving @ukanuk's flag suggestion a bit of a wave? I feel like a simple rectangle is not sufficiently "iconic" -- not sure if that's the word I'm looking for...

**Comment by horwitz** [comment]
> What about giving @ukanuk's flag suggestion a bit of a wave? I feel like a simple rectangle is not sufficiently "iconic" -- not sure if that's the word I'm looking for...

"evocative"? "suggestive"?

**Comment by ukanuk** [comment]
I like that idea, how about this? 

<details>
  <summary>Front <i>Country - Flag</i> template (bounding box ratio = 3:5)</summary>

```html
{{#Flag}}
  <div class="value value--top">{{Country}}</div>
  {{#Country info}}<div class="info">{{Country info}}</div>{{/Country info}}

  <hr>

  <div class="type">Flag</div>
  <div class="image">
    <svg class="image__placeholder" xmlns="http://www.w3.org/2000/svg" width="417" height="250" viewBox="0 0 417 250"><path d="m2 26s45-24 129-24c86 0 146 25 210 25 64 0 74-10 74-10v218s-25 13-83 13-146-25-206-25c-60 0-123 19-123 19z"/></svg>
  </div>
{{/Flag}}
```
</details>

![image](https://user-images.githubusercontent.com/59303202/78625280-a11b4c80-78c6-11ea-8c27-c34a4934ccb1.png)

Apparently [most flags have a 2:3 ratio](https://en.wikipedia.org/wiki/List_of_aspect_ratios_of_national_flags), but I think the 3:5 ratio above looks better overall. Here's code for the 2:3 ratio if you want to compare. They look basically the same to me on a computer since everything has height=250px, but when the `max-width: 100%` scaling starts to happen on mobile, that's when I think the thinner flag especially looks better. (Note I couldn't round to whole numbers for this inline SVG otherwise the left flag edge gets slanted. But I'm guessing it will work with whole numbers with a bit of fiddling, if others prefer this aspect ratio)

<details>
  <summary>Front <i>Country - Flag</i> template (bounding box ratio = 2:3)</summary>

```html
{{#Flag}}
  <div class="value value--top">{{Country}}</div>
  {{#Country info}}<div class="info">{{Country info}}</div>{{/Country info}}

  <hr>

  <div class="type">Flag</div>
  <div class="image">
    <svg class="image__placeholder" xmlns="http://www.w3.org/2000/svg" width="375" height="250" viewBox="0 0 375 250"><path d="m2 25.71s40.14-23.71 116.1-23.71c77.02 0 131.3 24.7 188.8 24.7 57.49 0 66.17-9.88 66.17-9.88v218.3s-22.78 12.84-74.85 12.84c-52.07 0-131.3-24.7-185.5-24.7-54.24 0-110.6 18.77-110.6 18.77z"/></svg>
  </div>
{{/Flag}}
```
</details>

**Comment by axelboc** [comment]
Excellent! I reckon it's time for a PR, @ukanuk. We can iron out the final details in there.
