### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by lervag** [axelboc/anki-ultimate-geography#155]
I'm sorry for opening an issue just to say this, but: Thank you all! I've been maintaining my own geography deck for 8-9 years now (forked from one of the large ones in 2011). I've tried to keep up with changes, but it is not so easy.

When I found this project, I immediately found a lot of news that I've missed (e.g. new flag in Mauritania, changed name of Swaziland, and so on). And since you are releasing updates with very good release notes, it becomes very easy for me to discover such updates! The value of your work is thus greater than simply providing a good geography deck!

Thanks! <3

Edit: Feel free to close the issue; but please leave it open for a couple of hours at least so that contributors can see my message.

**Comment by axelboc** [comment]
Very glad to hear! Thanks for your support ❤️
