### ISSUE TITLE
Cayman Islands Capital hint in Norwegian (bokmål) potentially misleading

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#160]
I'm not sure about this, as my knowledge of Norwegian is non-existent, so I can only rely on similarities with other languages and Google translate, but the capital hint for the Cayman Islands is potentially misleading.

The capitals of the Cayman Islands and Guyana are very similar, (also in Norwegian), so a capital hint is useful to distinguish them in the Capital → Country cards. However, in Norwegian both countries are apparently\* single words (`Caymanøyene` and `Guyana`). The Norwegian respective "capital hint" fields are:

    Land med to ord
    Landsavn på ett ord

which Google translates to:

    Land in two words
    Country name in one word

and which is potentially confusing, under the circumstances.

\* though I might be wrong — word-splitting rules might be different in Norwegian

(Noticed while reviewing the French translation.)

**Comment by Vages** [comment]
Well spotted. My bad.

I'll just change the hint to mainland country (Guyana) and islands (Cayman Islands)  respectively.

**Comment by aplaice** [comment]
That sounds great! Thanks!

(Given the monumental task of translating the entire deck, with a not-exactly-friendly translation format (CSV), that you did, a few errors are probably inevitable..)

**Comment by aplaice** [comment]
To avoid opening an additional issue for a minor paste typo: you had mistyped/mispasted Boliva instead of Colombia, as the name of the country, [here](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/data.csv#L160).
