### ISSUE TITLE
Country info often excessively informative in Country -> Map cards

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#164]
For some of the Country -> Map cards, the "Country info" (present on the front) can provide the entire answer for you. For example, Scandinavia:

![screenshot_2019-11-06_19:12:23](https://user-images.githubusercontent.com/16461345/68325894-a6336000-00ca-11ea-9841-f32bb97290f9.png)

Some other particularly egregious culprits are Melanesia and Athos, and slightly less egregious ones include the Indonesian islands, the constituent countries of the UK, Macau or Hong Kong.

![screenshot_2019-11-06_19:33:40](https://user-images.githubusercontent.com/16461345/68326782-62d9f100-00cc-11ea-92c3-4abaedcaa681.png)

## Some more examples, with country info, for reference

Country | Country info
----------|----------------
Melanesia | Subregion of Oceania, which includes the four countries of Vanuatu, the Solomon Islands, Fiji, and Papua New Guinea.
Polynesia | Subregion of Oceania comprising thousands of small islands in the central and southern Pacific Ocean.
Micronesia | Subregion of Oceania comprising thousands of small islands in the western Pacific Ocean.
Java | Island of Indonesia.
Mount Athos | Autonomous orthodox monastic state in northeastern Greece, also known as the Holy Mountain.
England  | Constituent country of the United Kingdom.
Macau | Special Administrative Region of China.

## Some possible approaches

1. **Remove the Country info from the front template** for the Country -> Map cards, and only display it on the back. Possible downsides:

   - For some cards, the Country info might be useful to identify the country (as opposed to pinpoint its location...). The main case I can think of is eSwatini (with info "Also known as Swaziland."), and perhaps North Macedonia, Myanmar and the DRC, where people might not have heard of the new name.

     - Counterpoint: by the time the Country -> Map card comes up, the learner will have been exposed to the "Country info" in the Map -> Country card (as well as, probably, in the Country <-> Capital and Country <-> Flag ones), so will hopefully already be aware of it.

   - When revealing the answer (displaying the "bottom" side) having the Country info appear in the upper half of the card, at the same time as the map appears in the lower half, might be disorientating to the learner.

2. **Place the "Country info" within a [hint field](https://apps.ankiweb.net/docs/manual.html#hint-fields)** for the Country -> Map front template. For cases like the Indonesian islands or the constituent countries of the UK, the "Country info" is an ideal location hint! Possible downsides:

   - The hint field should never contain the actual answer, which it still would for Scandinavia etc.

   - For many of the cards that have it, the "Country info" *isn't * a very useful location hint (e.g. finding out that French Polynesia is an Overseas Territory of France won't help you place it on the map), potentially disappointing/discouraging learners.

3. **Revise the contents of the "Country info"**, to be less "spoilery"/revealing (possibly in combination with 2.) 

   - However, how could that be done without completely removing the usefulness of the country info, for the culprit cards?

   - For Melanesia, for instance, the specific list of countries would have to be removed and the info cut down to basically "Subregion of Oceania", which would mostly remove the utility of the information.

   - Scandinavia's and Mount Athos's info would have to be completely removed...

   - Making the main (non-extended) deck worse, by removing information, for the benefit of the more niche extended deck seems a poor trade-off.

4. (Terrible idea) **Add yet another field** to separate the "spoilery" and "non-spoilery" country infos.

   - Huge added complexity to repository for only a couple of notes.

   - The cut-off of what reveals too much information would still not be obvious...

     - Might still need to hide even the "non-spoilery" country info within a hint...

I personally would vote for **1**, as the least harmful.

(AFAIR this was also an issue before the cloze-style redesign, so it's not a regression, but it would still be nice to fix. Currently I "solve" the issue by trying not to look at the country info when the relevant cards come up...)

**Comment by axelboc** [comment]
Hmm, great catch... Option 1 seems like the way to go, then. In some cases, Anki will scroll down to the `id=answer` element (if the card is tall-enough to scroll on the user's device), which actually mitigates the problem of the country info appearing above the answer.

Now that I think of it, I do have a 5th option to suggest: could the _Country info_ field just **not be used on the extended deck's templates at all**? After all, the extended deck is meant for advanced users. Wouldn't those users have learnt the normal deck first, and therefore already seen the country info fields? Also, it would make the extended deck even more challenging, which might be a good thing. Just a thought!

**Comment by aplaice** [comment]
You're right! The *Country info* isn't really needed for the Country -> Map cards, at all, and it would be cleanest to just remove it from them.

OTOH given the (understandable) general trend towards wanting to have as much info as possible on the answer cards (e.g. #162), it might perhaps not hurt too much for the *Country info* to be included in the back template. It doesn't make the cards significantly easier (since it's only displayed on the back side, it only affects hardness for new and lapsed cards) and mostly just provides a compact reminder of some tangentially useful info.

As far as I'm concerned either 1 or 5 would be fine! :)

**Comment by axelboc** [comment]
@ohare93, any preference between options 1 and 5? 🤷‍♂ I don't use the extended deck, so it feels wrong for me to decide... 😄

**Comment by ohare93** [comment]
I would prefer 1 over 5, simply because it fits in better with the other templates. I can't say if I pay attention to the country info fields in this context, or if I know them fully already, but it seems wrong to not include them :thinking: but yes either would ultimately be fine :grin:

**Comment by ukanuk** [comment]
Just found this while perusing the new v3.3 release notes (CONGRATULATIONS 🥳🥳🥳). 

> ...The extended deck is meant for advanced users. Wouldn't those users have learnt the normal deck first, and therefore already seen the country info fields? Also, it would make the extended deck even more challenging, which might be a good thing. Just a thought!

I would be careful about that assumption -- when I started this deck over the new year, I immediately went for the extended deck for three reasons:
* *Country - Map* card is only available in the extended deck, and this is the information I most care about in the entire deck. When meeting a new person from Xyz country or reading a news article about it, I want to be able to picture in my head where in the world that country is. 
* Learning the *Country - Flag* card may be difficult, but I personally find it more likely to "stick" in my long-term memory, and a little more rewarding (it's a cool party trick, even if it's not useful professionally)
* [README: Other languages and versions](https://github.com/axelboc/anki-ultimate-geography#other-languages-and-versions) discourages migrating from a standard deck to an extended deck, and in the future event that I might want some of those extended cards I definitely do not want to lose progress on existing cards.

So my point is while some see the extended deck as needless extra, others might conceivably download the extended deck and suspend all cards from standard deck. Maybe some schoolkid's next Quizbowl competition includes drawing country flags, and this happens to be the only deck they can find with good *Country - Flag* cards to help them study.
