### ISSUE TITLE
Possibility to type the answers

### ISSUE THREAD

**Issue by DavideFr** [axelboc/anki-ultimate-geography#165]
It would super useful to have the possibility to type in the answers already built into the deck.
Also because doing that in case of updates we don't need to mess up with the deck.

Thanks for the great work!

**Comment by axelboc** [comment]
This could be done as a deck variation, similarly to the extended deck.

However, given that each variation comes in 4 (soon to be 5) languages, this would bring the total number of decks built to 12 (soon 15 ... or 20 even, if we add a fourth variation - i.e. extended deck with typable answers). For my own sake, I probably wouldn't continue uploading them all into each release, so people interested in specific versions would have to build the decks themselves.

I'll leave this issue open with a `votes wanted` label to see if more people are interested. If you'd like to have a go at creating templates with typable answers yourself, feel free to do so and open a PR so people can try the deck with them and give feedback!

**Comment by mighty-cthulhu** [comment]
Personally, I wouldn't want to type answers. However I wonder if it would be problematic to type answers like "São Tomé and Príncipe", "Åland Islands", "Ivory Coast (Côte d'Ivoire)" on a desktop version of Anki.

**Comment by ohare93** [comment]
A deck variation would be fine, but this seems like a deck another person should manage in their own repo, tbh. Perhaps this will all be easier when we have moved to another deck management system, eventually.

> However I wonder if it would be problematic to type answers like "São Tomé and Príncipe", "Åland Islands", "Ivory Coast (Côte d'Ivoire)" on a desktop version of Anki.

@mighty-cthulhu Well typing answers in Anki is a user specific thing and is all relative, as Anki doesn't actually mark the answer as correct or not, you still do that afterwards. So if I have a flashcard to spell the Esperanto word "poŝo" using only my English keyboard I will type "posxo" as is done in Esperanto as another way to mark that an accent is there. Anki will say ŝ ≠ sx, but I know that was my intention and mark the card as correct :+1: Users will find a way to suit them

**Comment by code-hunger** [comment]
Let me summarise the three main points I see **againts** adding this feature, even as a deck variation:

* The possibility to type the answer is entirely a matter of presonal preference. You want it this way, someone else wants it the opposite;
* The majority of Anki users *do not* use this feature (take a look at any random shared deck);
* It is trivial to add it yourself. Just click 'edit' while studying and add `{{type:Capital}}` on both sides of a card asking for a capital, or `{{type:Country}}` on both sides of a card asking for a country name. Done.

**Comment by axelboc** [comment]
Alright, closing the issue, since it's not getting traction. If someone wishes to provide counter-arguments, feel free to keep commenting. Thanks for the suggestion anyway, @DavideFr!

**Comment by DavideFr** [comment]
Hello everyone. Sorry for the late answer. 

> However I wonder if it would be problematic to type answers like "São Tomé and Príncipe", "Åland Islands", "Ivory Coast (Côte d'Ivoire)" on a desktop version of Anki.

On Mac you can just hold a key and it'll show the different kind on letter. I don't know if there is something similar on Windows


> * The possibility to type the answer is entirely a matter of presonal preference. You want it this way, someone else wants it the opposite;

I feel it's more effective typing instead of just retrieving from my mind. But as you said is a matter of personal preference.

> * It is trivial to add it yourself. Just click 'edit' while studying and add `{{type:Capital}}` on both sides of a card asking for a capital, or `{{type:Country}}` on both sides of a card asking for a country name. Done.

I did it myself to my deck but now when the deck gets modified by the creator and I download the new version the cards won't upgrade in my deck as well cause now for Anki the card type is different.
