### ISSUE TITLE
CrowdAnki Updates: Sorting + Deck Movement

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#175]
This one's just an fyi, but perhaps some documentation changes could be useful from these changes. A few of my PRs have recently been pulled into [CrowdAnki](https://github.com/Stvad/CrowdAnki/), which may benefit this repo and it's users 👍 

1) Sorting Options for Export (Stvad/CrowdAnki#66)
There is now a config window where you can set the add-on options, including a new option to set the order that cards should be sorted in on export. For this repo specifically I imagine this could be useful for us developers types to export our changes and compare the differences 👍 I recommend sort by notemodel then guid for the most consistency, in general.

1) Do Not Move Cards On Import (Stvad/CrowdAnki#69)
Another config option I've added is the ability to *not move cards on import* 🍾 🎉 If, like me, you were always annoyed when you imported the deck and all the cards moved back into the default UG deck, well now you can enable this option and this will no longer happen 👍 This could be useful to mention in the repos "Updating Steps" so that users of the deck know this is possible to avoid 🙂 

I have some other PRs for CrowdAnki in the works, which will make great things possible for this repo, but I will keep those for whenever they are done 😏 😅

**Comment by axelboc** [comment]
Great stuff 👍 

Just to clarify, is the ability to "not move cards on import" now the default behaviour, or is it a configuration option people have to turn on?

If it's the new default, I'm wondering whether anyone would want to revert back to the old behaviour and not have their cards moved on import.

**Comment by ohare93** [comment]
It is not the default behaviour 😞 though I agree with you that it should be. For both issues above I believe @Stvad is of the opinion that current behaviour should remain the default. So users will have to enable this in the config settings on their machine, but only once 👍
