### ISSUE TITLE
Missing cards in v3.2

### ISSUE THREAD

**Issue by mighty-cthulhu** [axelboc/anki-ultimate-geography#177]
I am using deck v1.0 and before switching to v3.2 I decided to compare deck contents. From reading the release notes I can see that cards for "Manchuria", "Siberia" and "Tahiti" have been removed. But others are missing, too, some of which are mentioned as updated in the release notes: Gulf of Mexico, White Sea, Aegean Sea, The Balkan Peninsula, Sea of Japan, Gulf of Carpentaria, Polynesia, and Scandinavia.

**Comment by axelboc** [comment]
The issue you describe is most likely an import issue. Did you perform a "clean import", as [explained in the README](https://github.com/axelboc/anki-ultimate-geography#major-version)? You may want to give that a try.

**Comment by mighty-cthulhu** [comment]
I created a new user profile and imported Ultimate_Geography_v32.apkg. Those cards are missing. I'm using Anki 2.1.11.

Notes found in file: 313
Notes added from file: 313

**Comment by mighty-cthulhu** [comment]
It seems that the problem is with the deck that I downloaded from AnkiWeb shared decks https://ankiweb.net/shared/info/2109889812 (Ultimate_Geography_v32.apkg). When I download from the github (Ultimate_Geography_v3.2_EN.apkg.zip) all 8 of the missing entries are present.

Notes found in file: 321
Notes added from file: 321

**Comment by aplaice** [comment]
This is really weird, but I can indeed reproduce the issue when importing from the ankiweb shared deck page.

Thanks for bringing this up @mighty-cthulhu!

**Comment by axelboc** [comment]
Really strange, there must have been a synchronisation issue when I shared the deck. I've re-shared it and it seems to be fine now. Thanks for reporting!
