### ISSUE TITLE
[Improvement]show location of the capital on "country>capital" cards

### ISSUE THREAD

**Issue by Erim24** [axelboc/anki-ultimate-geography#18]
It would be great to have a map with an indicator of the location of the capital within the "country>capital" card.
I think it would help memorizing the capital

**Comment by axelboc** [comment]
Thanks for the suggestion, but this one's way too challenging. It would require finding a set of good-quality maps that include capital locators, or adding the locators manually on the existing maps. More importantly, I don't see a way to add the locators without duplicating the map files, and adding an extra 200+ images to the deck would make it way too big.
