### ISSUE TITLE
Change names of Czech Republic, Cape Verde, Ivory Coast, and East Timor

### ISSUE THREAD

**Issue by mighty-cthulhu** [axelboc/anki-ultimate-geography#180]
https://en.wikipedia.org/wiki/Timeline_of_historical_geopolitical_changes#2010s

Czech Republic -> Czechia
2016 | 2 May | The Czech Republic votes to adopt Czechia as its official short-form name in English.
_It's the same as using "China" instead of "People's Republic of China"._

Cape Verde -> Cabo Verde
Ivory Coast -> Côte d'Ivoire
East Timor -> Timor-Leste
2013 | 24 October | The Republic of Cape Verde decrees the official English-language rendering of its name to be the Republic of Cabo Verde, following precedents set by Côte d'Ivoire and Timor-Leste (neither of which use English as an official language).

**Comment by horwitz** [comment]
FWIW, [CIA World Factbook](https://www.cia.gov/library/publications/the-world-factbook/geos/ez.html) also uses Czechia

**Comment by axelboc** [comment]
Hi there!

Wikipedia still uses [Czech Republic](https://en.wikipedia.org/wiki/Czech_Republic) as the title of its article, so this change will have to wait. Same goes with the other countries you listed.

There's plenty of [ongoing discussions on Wikipedia](https://en.wikipedia.org/wiki/Talk:Czech_Republic) regarding the titles of these countries' articles, and we cannot possibly have our own discussions here as well. Apparently, _Czech Republic_ is still more commonly used than _Czechia_, so we'll have to wait a bit.

Don't hesitate to re-open an issue as soon as the article is renamed, though!
