### ISSUE TITLE
Map of Aegean Sea also highlights Sea of Marmara

### ISSUE THREAD

**Issue by mighty-cthulhu** [axelboc/anki-ultimate-geography#183]
Current map of Aegean Sea highlights both Aegean Sea and Sea of Marmara.

This is the correct map of Aegean Sea: https://en.wikipedia.org/wiki/Aegean_Sea#/media/File:Locatie_Egeische_Zee.PNG

**Comment by aplaice** [comment]
The current map is indeed incorrect. (It also doesn't include the Sea of Crete which is part of the Aegean Sea, like the map you linked to shows.)

Also, the Black sea includes the Sea of Azov in the current maps, which it shouldn't.

However, these issues will be fixed once the sea maps are updated (#176). In case you're curious, the updated maps are in the "details" section. If you have any comments or criticism, regarding the new maps, please bring them up!

(As the title of that pull request suggests, the process of updating the maps isn't finished.)

**Comment by aplaice** [comment]
This is now fixed in master!

![here](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-aegean_sea.png)
