### ISSUE TITLE
The "index" integrity check seems to be somehow mangled by GitHub

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#188]
This is independent of the question of whether the intention is for the check to explicitly fail when `src/data.csv` isn't quote-normalised or just for the information to be available in the checks tab [discussed here](https://github.com/axelboc/anki-ultimate-geography/pull/176#issuecomment-560135327). 

It appears that even the information available in the checks tab is incorrect. For example, see [this recent check](https://github.com/axelboc/anki-ultimate-geography/pull/187/checks?check_run_id=328111947) or [this earlier one]https://github.com/axelboc/anki-ultimate-geography/pull/185/checks?check_run_id=318062785) — for both of these pull requests `src/data.csv` was definitely quote-normalised, but if you clicked on the "Check diff" section, the echo would run displaying the "You need to run `composer index`" message (or similar).

Testing locally I can sort-of reproduce this. If I run

    composer index

and then, very quickly afterwards

    git diff-index --quiet HEAD -- || echo "You need to run \`composer index\`"

I also get the message. If I wait a while, or run `git status` (or even `git diff`) in between the two commands, then I don't get the message.

[This stackexchange question](https://unix.stackexchange.com/questions/519371/why-does-executing-git-status-change-the-result-of-subsequent-git-diff-index) discusses what seems to be exactly the same problem — apparently `git diff-index` is only supposed to give approximate results and rely on a potentially stale cache. The suggested solution is using `git diff --quiet` (which does update the cache) instead.

**Comment by axelboc** [comment]
Gosh, thanks for figuring this out. Feel free to fix the command whenever you can.

**Comment by aplaice** [comment]
> Feel free to fix the command whenever you can.

I think it's just a matter of changing `git diff-index` to `git diff`. 

<hr/>

What about having a "bot" that would comment in the pull-request with the feedback? 

I think (haven't tested) that it'd be really straightforward. [This](https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action/58704739#58704739) is almost exactly what we'd need, while [this](https://stackoverflow.com/questions/58468495/how-create-a-comment-on-commit-with-github-actions) describes a similar problem.

The most problematic part might be the use of the `secrets.GITHUB_TOKEN`, but [based on the documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret), I think that using it is safe, provided the action steps don't do anything crazy. It appears that a token/secret is generated every time a job action is run and `${{ secrets.GITHUB_TOKEN }}` in the action steps is replaced with its value. (Apparently no set-up, other than enabling actions in the first place, is needed.)

One further issue might be whether the `secrets.GITHUB_TOKEN` can run with the "write" permission on pull requests (which is [necessary to create a comment](https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests), if it's triggered by a pull request from a fork (I'm not sure how to read the [table](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token)). However, there appear to be [quite a large number of linter actions](https://github.com/sdras/awesome-actions#testing-and-linting) and they'd be significantly curtailed in usefulness if they could only be run on "internal" pull requests. (This could be easily, safely tested if I set up the right action on a test repository and somebody (other than me) creates a pull request.)

(I went a lot further down the rabbit hole than I intended to...)

**Comment by axelboc** [comment]
Honestly, I've added the workflow more as a way to check that the deck is not completely broken and that `data.csv` still gets parsed correctly. Quote normalisation is not crucial, so the way I see it, it's more about having a way to quickly check once in a while whether I should re-index, rather than to enforce a re-index in every PR.
