### ISSUE TITLE
How to go back after having customised the deck

### ISSUE THREAD

**Issue by DanceKafka** [axelboc/anki-ultimate-geography#19]
Just wondering if there's any process for trying to get the deck back to its original state after having (regrettably) tampered with it. I've tried clearing the tags after deleting it and re-downloading it etc but without success. Would really appreciate some help being able to properly use this awesome deck!

**Comment by axelboc** [comment]
Sorry for the late reply. Did you manage to get it back? I'm pretty sure the only way is to re-import the deck, but that would most likely erase your progress... Next time, try creating a filtered deck [as explained in the README](https://github.com/axelboc/anki-ultimate-geography#advanced-use). [Anki's support forum](https://anki.tenderapp.com/) might also be of more help.
