### ISSUE TITLE
Comma vs "and" in flag similarities

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#203]
As mentioned by @josealberto4444 in https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-583866082, "there are some flag similarities where all countries are separated by commas and some other where the last country is separated by 'and'."

I did notice this inconsistency when reviewing the French translation, and decided to enforce commas rather than "and". This seemed coherent with the fact that we don't use full stops.

If everyone's on board, then we might as well enforce this across all translations.

**Comment by josealberto4444** [comment]
I agree.

I will do it and submit a PR soon. In case aplaice or anyone does not agree, you can discard it, no problem. =)
