### ISSUE TITLE
Add differences to flag similarities

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#204]
See https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-583866082

- Item no 5: width of Ivory Coast and Ireland flags
- Item no 7: red colour of Monaco and Poland flags vs that of Indonesia flag

**Comment by josealberto4444** [comment]
Shoudn't we add that Poland flag is slighly wider than Monaco flag? It has almost the same proportion than Indonesia and we say that for Indonesia flag.

Also, what should I mention earlier in Monaco vs. Indonesia: brighter red or slightly wider?

**Comment by axelboc** [comment]
> Shoudn't we add that Poland flag is slighly wider than Monaco flag? It has almost the same proportion than Indonesia and we say that for Indonesia flag.

Totally! Seems I missed it in [my audit](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-524632859).

Note that Poland's similarity info is currently `Indonesia and Monaco (white and red flipped)`, so it will have to be separated (especially considering #203).

> Also, what should I mention first in Monaco vs. Indonesia: brighter red or slightly wider?

I think for both pairs (Indonesia/Monaco and Indonesia/Poland), the colour difference is the least significant difference, so I'd put it last.

**Comment by josealberto4444** [comment]
Great, thank you!

Maybe I'll have the PR ready tomorrow.

**Comment by josealberto4444** [comment]
> I think for both pairs (Indonesia/Monaco and Indonesia/Poland), the colour difference is the least significant difference, so I'd put it last.

Isn't it the other way around? I find the most significant difference at the end in other descriptions. Examples:

Côte d'Ivoire (narrower, green and orange flipped)
Austria (brighter red, wider white band)

**Comment by axelboc** [comment]
The order of the differences is just not something we've gone back and enforced in the deck yet, but it should definitely be `C > M > m > n`.

I agree with your assessment that it should be `wider`/`narrower` in this case. 👍

**Comment by josealberto4444** [comment]
Another issue I found (last one, haha). In English, Ivory Coast is written as Ivory Coast in the name of the country and with a country info "Officially Côte d'Ivoire.", but when talking about flag similarities in English, it's written Côte d'Ivoire. It only happens in English, in every other language the name in that language is used. Do I fix it?

**Comment by axelboc** [comment]
For sure, well spotted! 👀
