### ISSUE TITLE
Give same prominence to South Africa's three capitals

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#207]
@josealberto4444 in https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-583866082:

> 14. For South Africa, the English capital is put as Pretoria with some capital info explaining that there are three capitals with legislative, executive and judicial power. In Spanish capital, I put Pretoria for consistency and translated the capital info, but the Wikipedia infobox says: "Ciudad del Cabo (legislativa), Pretoria (ejecutiva), Bloemfontein (judicial)". Also, I think the three cities should be mentioned in the usual order of branches of government: legislative, executive and judicial.

@aplaice's reply:

> Ugh. The infobox in English Wikipedia also says "Pretoria (executive), Bloemfontein (judicial), Cape Town (legislative)" (as do the German, French and Norwegian ones), so the same solution should be used for all of them. (Encyclopaedia Britannica also gives the three cities as capitals...)
>
> The two possible approaches are:
> - (The current, de-facto approach.) Give the first city in the infobox as the "capital", and mention the remaining ones in the "Capital info".
> - List all the cities as capitals.
>
> I don't have any strong opinion on whether the current approach should be kept or not. This should probably go in its own issue...

@josealberto4444, I'm interested to know more about your last sentence:

> I think the three cities should be mentioned in the usual order of branches of government: legislative, executive and judicial.

Do you have a source that mentions this? If so, it might be worth reconsidering our current approach. Otherwise, I say we stay consistent with Wikipedia's Spanish info box and use Cape Town as the main Spanish capital.

**Comment by josealberto4444** [comment]
Sorry for taking so long to reply.

> Do you have a source that mentions this?

Well, AFAIK, it's just the usual order, like when you say black and white, and not white and black. (Maybe it's only in Spanish?) In fact, when I consulted the Wikipedia page for South Africa in Spanish, they were put in that order (and they still are). If you think this is a valid source...

> The two possible approaches are:
> 
> * (The current, de-facto approach.) Give the first city in the infobox as the "capital", and mention the remaining ones in the "Capital info".
> * List all the cities as capitals.
> 
> I don't have any strong opinion on whether the current approach should be kept or not. This should probably go in its own issue...

I prefer the second option a lot (which is already used in Canary Islands). Otherwise, I think we give a lot of importance to one capital and relegate others to mere curiosity that you can opt to memorize or not. Maybe that's not the intention at all, but that's how I interpreted the texts written in small font.

My propose is to put all the capitals in the capital field, separated by a comma and in a new line (a `<br>` in the csv might work), for example:

South Africa

Cape Town (legislative),
Pretoria (executive),
Bloemfontein (judicial)

That way, all of them have the same importance and are also present in the Capital - Country card.

---

In the following days I will try to get updated with all the open issues and probably get some of them done.

**Comment by axelboc** [comment]
> I prefer the second option a lot (which is already used in Canary Islands).

The situation in the Canaray Islands doesn't seem to be quite the same, in the sense that the two capitals aren't associated with specific government branches. They just share the capital status equally (not sure what this means in practice, though).

This seems to be a very unique situation, whereas many other countries than South Africa have multiple "branch" capitals. The difference is of course that South Africa doesn't declare one of its capitals as being more prominent than the others.

> My propose is to put all the capitals in the capital field, separated by a comma and in a new line (a <br> in the csv might work)

I have to say I'm not fond of putting HTML in textual fields... If we choose this route, I'd recommend listing the three capitals without their branches: `Cape Town, Pretoria, Bloemfontein`.

The branches can be mentioned in the _Capital info_ field: `Cape Town is the legislative capital, Pretoria is the executive capital, and Bloemfontein is the judiciary capital.`

---

That being said, this particular sentence from [Wikipedia](https://en.wikipedia.org/wiki/South_Africa) piqued my interest:

> Most foreign embassies are located in Pretoria. 

This could very well be a valid factor for picking Pretoria over the others. The location of embassies is, in my opinion, quite telling as to which capital is more relevant at the international level.

**Comment by josealberto4444** [comment]
> The situation in the Canaray Islands doesn't seem to be quite the same in the sense that the two capitals aren't associated with specific government branches. They just share the capital status equally (not sure what this means in practice, though).

It means that the government rotates between them. At least, that's what they told me in school. =)

> I have to say I'm not fond of putting HTML in textual fields... If we choose this route, I'd recommend listing the three capitals without their branches: `Cape Town, Pretoria, Bloemfontein`.
> 
> The branches could then be mentioned in the _Capital info_ field: `Cape Town is the legislative capital, Pretoria is the executive capital, and Bloemfontein is the judiciary capital.`

Yes, this seems a better solution. Thanks!

> That being said, this particular sentence from [Wikipedia](https://en.wikipedia.org/wiki/South_Africa) piqued my interest:
> 
> > Most foreign embassies are located in Pretoria.
> 
> This could very well be a valid factor for picking Pretoria over the others. The location of embassies is, in my opinion, quite telling as to which capital is more relevant politically at the international level.

It's interesting, though, that I've always believed that it was Cape Town, and I think a lot of people have heard that. As a curiosity, I even talked about it with a friend that was working there and he told me that he was living in the capital city. Anyway, I understand your argument, but I'd put the three cities as that's the official statement.

**Comment by axelboc** [comment]
Alright, let's list the three cities in the _Capital field_. 💯
