### ISSUE TITLE
Dealing with duplicate Country Names

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#212]
See #202 and https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-583842852

Summarising: the issue is that in Spanish and French, Sint Maarten (a constituent country of the Kingdom of the Netherlands) and Saint-Martin (French overseas collectivity) have the same names. Hence, for the Country → Map cards (in the extended deck), which don't have the "Country info" on the front (due to #164),  the learner has no way of distinguishing the two regions. (No other cards are affected, since all the other Country → X templates do have the "Country info" on the front, and all the cards have the "Country info" on the back.)

(I've moved this to a separate issue rather than continuing the discussion in the pull request, to avoid privileging one solution, and to (hopefully) present the problem more clearly.)

<hr/>

Answering @axelboc's comments from @202:

> Isn't distinguishing between two "countries" with the same name the role of the Country info field? 

That hasn't been the role of the "Country info" field until now, since there haven't been any cases where the "country" name was the same for two cards, though obviously it can take that role.

> Putting this information in parens as well will add redundant information to a few templates.

It would indeed add redundant info to all the templates except the Country → Map one. OTOH the Capital → Country template currently has redundant info on the back card when the "Capital hint" and "Country info" are non-empty (e.g. Sint Eustatius — "Special municipality of the Netherlands." —
Hint: "Special municipality"), so it's not *necessarily* catastrophic.

> Which template(s) is(are) affected by the missing Country info field?

As I've (now) written in the summary, it's only the "Country → Map" template.

> Perhaps we should reconsider the solution we picked in #164?

That makes sense!

(For context, if anybody reads this without having read #164, it was about the "Country info" being present on the front of the Country → Map cards and, because it often contains location info, providing the answer to the card.)

<hr/>

Possible solutions (AFAICT):

1. (Under the current circumstances terrible, but listed for completeness) **Add a dedicated "Country hint" field** in addition to the "Country info" field, similar to the "Capital hint" field (which exists in addition to the "Capital info" one).

    - Given that only two cards, in the extended translated versions of the deck, need this, it'd be an absurd overkill.

2. **Add a brief disambiguator in the Country field**, as is the case currently in the Spanish deck. ("San Martín (Francia)" and "San Martín (Países Bajos)") and as suggested in #202.

    - Disadvantage: as @axelboc pointed out, it adds redundant info to most of the templates, which might be annoying to the learner.

    - Advantage: it affects only the two notes, in the Spanish and French decks.

3. **Change the "Country → Map" template to include the "Capital info" as a ["hint field"](https://apps.ankiweb.net/docs/manual.html#hint-fields)**. This was originally suggested as one of the solutions in #164. In the case of "Saint-Martin"/"San Martín" the learner could click on the hint field and they'd know which card it was

    - The advantages/disadvantages listed in the context of #164 still apply:

        - (+) For cases like the Indonesian islands or the constituent countries of the UK, the "Country info" is an ideal location hint.

        - (-) The hint field should never contain the actual answer, which it still would for Scandinavia etc.

        - (-) For many of the cards that have it, the "Country info" *isn't * a very useful location hint (e.g. finding out that French Polynesia is an Overseas Territory of France won't help you place it on the map), potentially disappointing/discouraging learners.

    - Additional disadvantage:

        - Since the hint field would still be hidden by default, it wouldn't "warn" the learner that there were two "countries" with the same name, so they'd have to specifically remember that "Saint-Martin"/"San Martín" was ambiguous (getting into the habit of clicking on the hint field by default would be a bad idea, as it would still often contain too much information). 

            - If they already remembered that the card was ambiguous they could simply visualise both possible answers at the same time, which is more inconvenient than clicking on a hint field, but not *much* more so.

4. **Mention in the "Country info" that the "country" name is ambiguous**. (Something like (in French/Spanish): "There's a Constituent country of the Kingdom of the Netherlands which has the same name, and which takes up the southern part of the island." etc.) This wouldn't help directly, but would help make the learner aware of the problem, and indirectly encourage them to visualise both answers when they encountered "Saint-Martin"/"San Martín" on the Country → Map card.

    - Could be combined with 3. (It would then indirectly encourage the learner to click on the hint field for the relevant cards.)

    - Could be added irrespective of the solution chosen, as it's valuable information anyway.

5. (Not great) **Remove Saint Martin and Sint Maarten** from the deck, since they might end up not significant enough, anyway (see #137).

6. (Not great) **Revise the contents of the "Country info", to be less location-"spoilery" and re-add the "Country info" to the Country → Map template**. (**3** from #164.)

    - Would result in the loss of a large amount of useful info.

<hr/>

I personally lean towards **2**, but **3** + **4** also seems attractive.

**Comment by ohare93** [comment]
Option 2 sounds like the least intrusive which fixed the problem with no real downsides. If it is too laborious to do so in the future the policy can be changed to another option above, but it's fine for now.

**Comment by axelboc** [comment]
Thanks for laying it all out like this, @aplaice. Looks like option 2 is indeed the sanest way to go... 😖 

As you mention, I agree that adding a hint might encourage a habit of always clicking on it. I much prefer making information that matters available right away. 

In my opinion, adding a _Country hint_ field (i.e. option 1) would be the ideal, most consistent choice ... but for two notes, it'd be like hitting a nail with a sledge hammer! Especially considering that the cards may not stick around in the long term (i.e. option 5).

It's in times like these I wish Anki had a more "NoSQL" approach, in the sense that notes would be defined as key-value documents rather than arrays of strings... Anyway, just dreamin'... 😄

**Comment by aplaice** [comment]
> In my opinion, adding a Country hint field (i.e. option 1) would be the ideal, most consistent choice ... but for two notes, it'd be like hitting a nail with a sledge hammer!

That's exactly what I had thought too! (which is why I had listed it as the first option, while mentioning that right now it was pretty terrible.)

> It's in times like these I wish Anki had a more "NoSQL" approach, in the sense that notes would be defined as key-value documents rather than arrays of strings... Anyway, just dreamin'... smile

Yeah, that'd be convenient. :)
