### ISSUE TITLE
Add or remove EU's capital

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#213]
Currently, the EU has a capital in the French version of the deck, but none of the others.

<hr/>

Replying to https://github.com/axelboc/anki-ultimate-geography/issues/161#issuecomment-587128665:

> Here are my thoughts regarding the capital of the EU:
>
>   - First, it seems like a shame to have to add capital hints to distinguish Belgium from the European Union.

That's true, though adding a hint like "Sovereign state" wouldn't (IMO) really harm the value of the existing Capital → Country card for Belgium.\*

\* I'm not sure what would be the best hint for the EU.  "Supranational organisation" would uniquely identify the EU, so would be sub-optimal.  Our usual counterpart to "Sovereign state" — "Not a sovereign state" — is technically correct, but mildly misleading.  Perhaps "Not a state" would "leak" the least amount of information?

Additionally, given that (at least outside Belgium), one is far more likely to hear about Brussels as a shorthand for the EU institutions or the EU as a whole, in the same way that one uses "London" for the UK or "Paris" for France, than as a shorthand for Belgium, I don't think that it'd be somehow wrong for the capital of Belgium to have to be disambiguated. (Absolutely no offence meant to any Belgians!)

>   - Second, it's not a straightforward change:

>       - Although English Wikipedia mentions Brussels as the capital
>         in the info box, French Wikipedia doesn't and instead lists
>         the various institutions, so the French translation would
>         have to not have the capital.

If we're to consistently apply our guidelines, the French translation should indeed have the capital of the EU removed. However, it should be added to the English, Spanish and possibly Norwegian versions, but not the German one. It'd be a bit of a mess, but not more so than the capital of the British Indian Ocean territory...

>       - One of the institutions, the Parliament, is located in
>         Strasbourg, so should this city be considered a secondary
>         capital and mentioned in the *Capital info* field?

IMO if the EU's capital is added, this definitely should be mentioned.  The fact that there's no official capital and that Brussels is only the de facto capital (possibly with a listing of the institutions that are seated there the seat of the Commission and Council), like in the case of Nauru/Yaren, should probably also be noted.

> I feel like we keep trying to fit a square peg in a round hole. Maybe the current model of using the *Country - Capital* and *Capital - Country* templates for subdivisions, along with capital hints, has reach its limit and we should brainstorm an alternative? 

Interesting, perhaps you're right.

> I don't know, maybe we could add a new template, or decide that if a subdivision's capital conflicts with a sovereign country's capital, we simply don't add it.  After all, this is what we do with flags (e.g. we don't have a flag for French Guiana *because* it's the French flag). Anyway, just a thought for now. If you don't think I'm going crazy, we can discuss further this in a separate issue.

OTOH, I think that we don't have a flag for French Guiana because none of the subdivisions of France have a separate flag\*. If only a specific subdivision of a country had the same flag as the country itself, but the remaining subdivisions had different ones, it would IMO be worth including the flag even for the subdivision that had the same flag.

\* French Polynesia and New Caledonia are partial exceptions, but even in their case it seems that the situation is rather complicated and controversial: [French Polynesia](https://en.wikipedia.org/wiki/Flag_of_French_Polynesia), [New Caledonia](https://en.wikipedia.org/wiki/Flags_of_New_Caledonia).

Also, I'm not sure whether ignoring capital conflicts between a country and one of its subdivisions would help us much, since the "Capital hint" field would still need to be present for cases like Aruba/Sint Eustatius or Guyana/Cayman Islands.

<hr/>

Possible ways forward:

1. Keep the current situation (EU has a capital only in French).

    - Would probably need to add a capital hint.

2. Add for English/Spanish/Norwegian (?), remove for French; include "Capital info" mentioning Strasbourg; add a capital hint.

3. Remove altogether.

**Comment by axelboc** [comment]
> [...] one is far more likely to hear about Brussels as a shorthand for the EU institutions or the EU as a whole, [...] than as a shorthand for Belgium [...]

You make a very good point. This argument brings home option 2, I reckon.

> [...] the "Capital hint" field would still need to be present for cases like Aruba/Sint Eustatius or Guyana/Cayman Islands.

Also, very true! 😆

**Comment by aplaice** [comment]
> What issue #213 made me realise is that the capital we should remove is not the capital of the EU in French

I'm taking that as a vote for *4.* :D 

4. Keep the French
    Add the other languages.
    Add a capital info.
    Add capital hints.

### Capital info

I'd suggest:

> The European Union has no official capital. Its executive branch is based in Brussels. The legislative is split between Brussels and Strasbourg.

I think that it's a relatively compact representation of the horribly messy situation:

The [European Commission](https://en.wikipedia.org/wiki/European_Commission) and the [European Council](https://en.wikipedia.org/wiki/European_Council) (the former is the main executive and the latter is a sort-of executive body) are both based in Brussels.

The [European Parliament](https://en.wikipedia.org/wiki/European_Parliament) is obviously split between Brussels and Strasbourg (though the Secretariat is based in Luxembourg...) while the [Council of the European Union](https://en.wikipedia.org/wiki/Council_of_the_European_Union), the other legislative body, is based in Brussels.

The European Court of Justice is in Luxembourg.

I think that not mentioning the judicial branch (in Luxembourg) is justifiable, to avoid increasing the length of the field, and since we already don't mention the judicial branch in some cases (e.g. Germany where most of the Federal courts aren't in Berlin (some are in Karlsruhe, some elsewhere...)).


### "Capital hint" for Belgium and EU

Some options:

1. "One-word name" vs. "Two-word name"

    My current favourite, as arguably the least harmful.

2. "Sovereign state" vs. "Not a state"

    (My previous favourite, but "Not a state" might be too strong of a hint...)

3. "Sovereign state" vs. "Not a sovereign state"

    (This follows the standard convention of most of the other pairs, but "Not a sovereign state" is mildly misleading, if technically correct — the EU isn't a state, at all.)

4. "One-word country name" vs. "Two-word country name"

    (Based on the old Guyana—Cayman Islands pair, but the EU isn't a country either...)

### Translations

Other than the Norwegian, where  "One-word name" vs. "Two-word name" might possibly not work (is "Den europeiske union" two or three words — does the article "den" count?), I think all of these could work in translation. If the above English versions are accepted, I'll try to produce the translations (hopefully subject to correction by native speakers...).

**Comment by axelboc** [comment]
> I'm taking that as a vote for 4. :D

Haha I guess so! 😂 

I reckon something even more general for the _Capital info_ could work too, like:

> Brussels is the seat of the executive branch but the European Unions has institutions in other European cities.

I'm down with "one/two-word name" for the hint, though we could also shorten it to "one/two word(s)".

**Comment by josealberto4444** [comment]
> Some options:
> 
>     1. "One-word name" vs. "Two-word name"
>        My current favourite, as arguably the least harmful.
> 
>     2. "Sovereign state" vs. "Not a state"
>        (My previous favourite, but "Not a state" might be too strong of a hint...)
> 
>     3. "Sovereign state" vs. "Not a sovereign state"
>        (This follows the standard convention of most of the other pairs, but "Not a sovereign state" is mildly misleading, if technically correct — the EU isn't a state, at all.)
> 
>     4. "One-word country name" vs. "Two-word country name"
>        (Based on the old Guyana—Cayman Islands pair, but the EU isn't a country either...)

It's a very difficult decision.

While I agreed that the first option was the least harmful in the sense of giving less information, I think the problem of translations is very important and that'd be an argument in favour of choosing the second option.

Besides, I think the greatest part of information given by the hint comes from having a unique hint for that region and that also happens with option one, as all other country hints talk about sovereign/not sovereign countries, if I remember well. In other words, once you know that the hint talking about number of words is the European Union or Belgium, you can only remember that. Another advantage of the second option is that the country hint of Belgium is completely indistinguishable from other country hints.

Given all these problems, I now think that the least harmful option is the second option. =P

**Comment by axelboc** [comment]
Totally valid points. I'm happy with option 2, then, and I think @aplaice is too, so let's go with that!

**Comment by aplaice** [comment]
> I think the problem of translations is very important and that'd be an argument in favour of choosing the second option.

In this case I had checked that the "number of words" hint could work in the translations (in the Norwegian it could have been "three-word name", depending on how articles are counted), but

> In other words, once you know that the hint talking about number of words is the European Union or Belgium, you can only remember that. Another advantage of the second option is that the country hint of Belgium is completely indistinguishable from other country hints.

convinced me, so yeah, option 2. is great! :)

**Comment by horwitz** [comment]
It seems like this should be option 3, not option 2: doesn't choosing option 2 go against the hint-standardisation mentioned [here](https://github.com/axelboc/anki-ultimate-geography/pull/190#issuecomment-560491513)? These hints (unfortunately) reveal information—if a goal is to minimize that, option 3 seems to outperform option 2.

**Comment by aplaice** [comment]
First, I'm highly embarrassed to say, that it should be "country" not "state", (I must have looked at the German version of the hint just before writing the first comment, and then the error propagated) i.e. the options would be:

1. "One-word name" vs. "Two-word name"

2. "Sovereign country" vs. "Not a country"

3. "Sovereign country" vs. "Not a sovereign country"

4. "One-word country name" vs. "Two-word country name"

<hr/>

> These hints (unfortunately) reveal information—if a goal is to minimize that, option 3 seems to outperform option 2.

Yes, 3. definitely reveals the least information. However, while technically correct, describing the EU as "Not a sovereign country" is also arguably confusing, in that it's obviously not a country at all. In contrast, England definitely is a country, while the Cayman Islands, Norfolk Island and even Guadeloupe, can be described as countries (e.g. all their respective current Wikipedia articles have them referred to as countries at least once and the Cayman Islands as well as Norfolk Island have their own top-level internet country codes).

Hence, the key question is whether "Not a sovereign country" as applied to the EU is confusing. (After thinking about it again, I'm not quite sure...)

**Comment by josealberto4444** [comment]
How about changing "Not a sovereign country" to "Not sovereign" along the deck and putting also "Not sovereign" to the EU? Maybe it's also confusing because there are semi-autonomous regions&hellip;

After thinking all this, I agree with @horwitz and I think option 3 is the best. It might be confusing the first time, but once you've seen the card once, you'll agree that it's not a sovereign country and that is an obvious difference from Belgium, which is the objective.

**Comment by aplaice** [comment]
> How about changing "Not a sovereign country" to "Not sovereign" along the deck and putting also "Not sovereign" to the EU? Maybe it's also confusing because there are semi-autonomous regions…

I'm not sure. Aside from what you brought up, there's also the issue that the EU in some ways is [sort-of sovereign](https://en.wikipedia.org/wiki/Member_state_of_the_European_Union#Sovereignty), so while "Not a sovereign country" is unambiguously true as a description of the EU, "Not sovereign" is only mostly true...

**Comment by josealberto4444** [comment]
Yes, I completely agree. I'd go for option 3.

**Comment by aplaice** [comment]
> I'd go for option 3.

On n-th thoughts, I think I agree! :)

### Capital hint (es)

I'm not at all sure, as my Spanish is pretty terrible, but does "Nación no soberana" (our default Capital hint counterpart to "País soberano") say that whatever we're describing actually is a nation, unlike the English (and I think unlike the French, German and Norwegian), which only sort-of suggest that that might be the case.

(In other words, it feels like in the English, we have "NOT (sovereign nation)", while in the Spanish we have "(NOT sovereign) nation", but I might be wildly wrong. (I'd guess that the equivalent of "NOT (sovereign nation)" would be "No una nación soberana." (????).))

If that's the case, I'm not sure how to proceed:

1. Use "Nación no soberana" for the EU, anyway.
2. Use a different hint for the EU, only.
3. Change the hint throughout (:/).

(Sorry if what I wrote is completely wrong!)

**Comment by josealberto4444** [comment]
> In other words, it feels like in the English, we have "NOT (sovereign nation)"

Well, I think that English let open both interpretations, but&hellip;

> in the Spanish we have "(NOT sovereign) nation"

That's completely true and is the only possible interpretation. 🤦

> I'd guess that the equivalent of "NOT (sovereign nation)" would be "No una nación soberana."

I'm not sure if that would be correct, but it does not sound very well. For now, I think the best solution is to put a verb:
No es una nación soberana
(It's not a sovereign country)

but let me think about it until tomorrow, in case I find an expression without a verb that fits better.

> If that's the case, I'm not sure how to proceed:
> 
>     1. Use "Nación no soberana" for the EU, anyway.
> 
>     2. Use a different hint for the EU, only.
> 
>     3. Change the hint throughout (:/).

Option 3 for the win. =P

**Comment by josealberto4444** [comment]
There seems to be no better option. I've asked some friends and we cannot negate a substantive in Spanish, it seems.

If you agree, I will take a look at all the translations of that style and change them accordingly for consistency. I'll do it in a couple of days and submit a PR.

This does not prevent adding Brussels with that hint in Spanish, I can change the rest later.

**Comment by aplaice** [comment]
> I've asked some friends and we cannot negate a substantive in Spanish, it seems.

Interesting. Thanks for the information and for looking into this!

**Comment by aplaice** [comment]
### Norwegian

In the [Norwegian article about the EU](https://no.wikipedia.org/wiki/Den_europeiske_union), three capitals are listed (Brussel, Strasbourg, Luxembourg) — should we use that?

### Capital info

Translation suggestions (please tear apart!):

Brussels is the seat of the executive branch but the European Union has institutions in other European cities.

@Erim24
DE: Brüssel ist der Sitz der Exekutive, aber es gibt auch Institutionen der Europäischen Union in anderen europäischen Städten.

ES:  Bruselas es la sede del poder ejecutivo, pero la Unión Europea tiene instituciones en otras ciudades europeas. 
or (shorter) ES: Bruselas es la capital institucional, pero hay más sedes institucionales de la Unión Europea. (based on [these](https://es.wikipedia.org/wiki/Uni%C3%B3n_Europea#cite_ref-2) [links](https://es.wikipedia.org/wiki/Marco_institucional_de_la_Uni%C3%B3n_Europea)).

FR: Bruxelles est le siège de l'exécutif, mais l'Union européenne a des institutions dans d'autres villes européennes. (du pouvoir exécutif?; technically exécutif is a noun...)

@Vages
NB: Den europeiske unions institusjoner har hjemsteder i flere europeiske byer, inkludert Brussel (Europakommisjonen), Strasbourg (Europaparlamentet) og Luxembourg (Den europeiske unions domstol).
https://no.wikipedia.org/wiki/Den_europeiske_unions_institusjoner

**Comment by axelboc** [comment]
I like `siège du pouvoir exécutif` better, as "siège de l'exécutif" sounds a bit less formal. See also the title of [this article](https://fr.wikipedia.org/wiki/Pouvoir_ex%C3%A9cutif).

**Comment by axelboc** [comment]
Three capitals in Norwegian is fine by me 👍 .

**Comment by Vages** [comment]
The Norwegian translation is fine!
