### ISSUE TITLE
Mention The Hague in the "Capital info" for the Netherlands

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#218]
Amsterdam is the official capital of the Netherlands (according to the constitution), but The Hague is the seat of the government, the legislature and the supreme court. (See [Capital of the Netherlands]https://en.wikipedia.org/wiki/Capital_of_the_Netherlands.)

For Tanzania, we do mention that:

> While Dodoma is the official capital, Dar es Salaam is the de facto seat of government.

so I think that we should also mention it for the Netherlands. I'd suggest:

> While Amsterdam is the official capital, the Hague is the seat of government and the legislative.

**Comment by axelboc** [comment]
Yep, for sure!

**Comment by aplaice** [comment]
Suggestions for the translations (subject to being torn apart by native-speakers):

While Amsterdam is the official capital, the Hague is the seat of government and the legislative.
DE: Amsterdam ist die offizielle Hauptstadt, aber den Haag ist der Parlaments- und Regierungssitz.
https://de.wikipedia.org/wiki/Den_Haag
ES: Aunque Ámsterdam es la capital oficial, La Haya es la sede del gobierno y de la legislatura.
https://es.wikipedia.org/wiki/La_Haya
FR: Bien qu'Amsterdam soit la capitale officielle, La Haye est le siège du gouvernement et du parlement.
https://fr.wikipedia.org/wiki/La_Haye
NB: Amsterdam er offisiell hovedstad, mens i Haag har landets regjering og parlament sete.
https://no.wikipedia.org/wiki/Haag

(Translations based on the current capital info for South Africa, Eswatini and Tanzania:

<details>

South Africa has no legally defined capital: the branches of government are split over three cities: Pretoria (executive), Cape Town (legislative) and Bloemfontein (judicial).
Die Regierung sitzt in der formellen Hauptstadt Pretoria (Exekutive), das Parlament in Kapstadt (Legislative) und das Oberste Berufungsgericht in Bloemfontein (Judikative).
Sudáfrica no tiene capital legalmente establecida: los poderes del gobierno están repartidos en tres ciudades: Pretoria (ejecutivo), Ciudad del Cabo (legislativo) y Bloemfontein (judicial).
L'Afrique du Sud n'a pas de capitale officielle. Les branches du gouvernement sont réparties sur trois villes : Pretoria (exécutive), Le Cap (législative) et Bloemfontein (judiciaire).
Sør-Afrika har ingen fastsatt hovedstad; makten er fordelt på tre byer: Pretoria (utøvende), Cape Town (lovgivende) og Bloemfontein (dømmende).

While Mbabane is the official, executive capital, Lobamba is the traditional, spiritual and legislative capital.
Mbabane ist die offizielle Haupstadt, aber Lobamba ist die traditionelle Haupstadt und Sitz des nationalen Parlaments.
Aunque Mbabane es la capital oficial y ejecutiva, Lobamba es la capital tradicional, espiritual y legislativa.
Bien que Mbabane soit la capitale exécutive officielle, Lobamba est la capitale traditionnelle, spirituelle et légistlative.
Mbabane offisiell, utøvende hovedstad, mens Lobamba er tradisjonell, åndelig og lovgivende hovedstad.

While Dodoma is the official capital, Dar es Salaam is the de facto seat of government.
Dodoma ist die offizielle Hauptstadt, aber Dar es Salaam ist der Regierungssitz.
Aunque Dodoma es la capital oficial, Dar es-Salam es la capital de facto, donde reside la sede del gobierno.
Bien que Dodoma soit la capitale officielle, Dar es Salaam est le siège du gouvernement.
Dodoma er offisiell hovedstad, mens Dar es Salaam er regjeringssete.

</details>

and, where possible on direct quotes from the relevant Wikipedia articles.)

<hr/>

What do you think is the best way of going forward (here and in similar issues) regarding the approval of translations — should I start a pull request which can be considered for merging once the translations are accepted by people competent in the given languages?

(The translations are becoming rather unwieldy, but leaving them out would quickly result in desynchronisation from the English, and we don't currently have a scalable way of marking specific translated fields as needing updating. 

(The non-scalable way would be to open issues for every updated field (or group of fields), for every language, which would become an M×N problem.)

(A slightly less non-scalable way would be to keep an issue open for every language, and post to it with updates/requests for translations — but that would make partial updates of a translation harder.))

**Comment by axelboc** [comment]
The French translation looks great. Not sure about ending the English one with "and the legislative", though. It feels abrupt. I'm sure it's correct but I feel like it's missing a word like "capital" or "branch"... How about "[...] the Hague is the seat of the executive and legislative branches."?

---

I have been tormented by these questions in the past. I think a reasonable approach is to ping the relevant people in the PR but to not wait for their approval to merge. They can recommend a fix for the translation when they get around to checking the PR.

**Comment by aplaice** [comment]
Sorry, I'll do this soon...

**Comment by josealberto4444** [comment]
For the Spanish translation, I think it's better:
Aunque Ámsterdam es la capital oficial, La Haya es la sede del gobierno y del poder legislativo.

Feel free to ping me any time you need help with the Spanish translation.

**Comment by aplaice** [comment]
@josealberto4444 thanks! :)
