### ISSUE TITLE
Add capital info for Canary Islands

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#226]
See https://github.com/axelboc/anki-ultimate-geography/issues/205#issuecomment-601470159

> The capital is shared between the two cities of Santa Cruz de Tenerife and Las Palmas

**Comment by josealberto4444** [comment]
Should I also separate the two cities by a comma in the capital field in all translations?

**Comment by axelboc** [comment]
I'd say so, for consistency with South Africa. What do you reckon?

**Comment by josealberto4444** [comment]
Yes, I'd do that as well. =) I just wanted to confirm the criterion before making the PR just in case I didn't understand.

**Comment by josealberto4444** [comment]
Another doubt: Wouldn't be better to say that "The **capitality** is shared"?

**Comment by aplaice** [comment]
I'm not sure whether "capitality" actually exists in English. It seems to be used on Wikipedia as a direct calque of the Spanish "capitalidad", and searching with `"capitality" site:en.wikipedia.org` mainly gives results about Spain-related articles. I also can't find it in any other English dictionaries (even Wiktionary).

(FWIW I think that it's a nice word, since it allows distinguishing between the capital and the state of being a capital, but unfortunately my approval doesn't mean anything...)

**Comment by josealberto4444** [comment]
Yes, seems to be a bad translation of "capitalidad". Let's use capital, as it was proposed from the beginning, then. =)

**Comment by josealberto4444** [comment]
Do you have proposals for other translations? I could try with French, but I have no idea about the others.

**Comment by aplaice** [comment]
> Edit: However, in Spanish I will use capitalidad, if you don't mind.

I don't think I get a say, as you're the Spanish native, but yes, definitely! :)

> Do you have proposals for other translations? I could try with French, but I have no idea about the others.

Perhaps:

DE: Die zwei städte Santa Cruz de Tenerife und Las Palmas de Gran Canaria sind zusammen Hauptstädte der (Autonomen Gemeinschaft der) Kanaren.
FR: La fonction de capitale est partagée entre les deux villes de Santa Cruz et Las Palmas.
NB: De to byene Santa Cruz på Tenerife og Las Palmas på Gran Canaria deler hovedstadsstatusen.

Norwegian adapted from: https://no.wikipedia.org/wiki/Kanari%C3%B8yene

(??)

In all cases I've tried to emphasise that there are definitely two of them...

**Comment by axelboc** [comment]
In French, I think "Le statut de capitale est partagé ..." would work better.

**Comment by Vages** [comment]
The Nerwegian is all right to me.
