### ISSUE TITLE
[RFC] Change the spelling/transliteration of El Aaiún/Laayoune

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#231]
Currently, English Wikipedia lists the capital of SADR as Laayoune, rather than "El Aaiún", as it had before. The article about the city in question also uses Laayoune as the "principal" version of the name.

(For information, [according to Wikipedia](https://en.wikipedia.org/wiki/Laayoune#Etymology):

> Laâyoune or El Aaiún are respectively the French and Spanish transliterations of the Maghrebi Arabic name Layoun which means "the water springs". 

)

The translated versions of the deck are already in-line with the names used in their respective Wikipedia articles.

**Comment by aplaice** [comment]
Sorry, I should have though of this earlier, but to avoid confusing people who upgrade their deck, should we mention the alternative name in the "Capital info", making it into something like:

> Laayoune is also known as El Aaiún. While Laayoune is the declared capital, Tifariti is the de facto seat of government.

**Comment by axelboc** [comment]
How about:

> While Laayoune, also known as El Aaiún, is the declared capital, Tifariti is the de facto seat of government.
