### ISSUE TITLE
[ES] Translation issues

### ISSUE THREAD

**Issue by josealberto4444** [axelboc/anki-ultimate-geography#235]
In a conversation with a friend who is lawyer, I realized that «gobierno», government in Spanish, is equal to executive power, so I think I should check all places where it is used in the Spanish translation.

For example,

> Sudáfrica no tiene capital legalmente establecida: los poderes del gobierno están repartidos en tres ciudades: Pretoria (ejecutivo), Ciudad del Cabo (legislativo) y Bloemfontein (judicial).

is wrong, it should say "los poderes del Estado".

Also, "estado" is written sometimes with initial uppercase, depending on the meaning. I didn't know, my friend just told me and I checked.

I will fix this and submit a PR once all pending PRs are merged (because it might conflict). =)

**Comment by axelboc** [comment]
Hey, @josealberto4444! Just letting you know I'm going to release v3.3 this week-end, in case you'd like this fix to be included.

**Comment by josealberto4444** [comment]
Yes. I'm working on it right now. =)
