### ISSUE TITLE
Add grammatical genders

### ISSUE THREAD

**Issue by GrimPixel** [axelboc/anki-ultimate-geography#240]
As one of language learners, it is hard to memorise genders of vocabulary, including country names. We can simply add them to make the deck more helpful.

**Comment by axelboc** [comment]
I believe this was discussed previously, let me see if I can remember where... Ah yes, in the PR that added the French translation to the deck: https://github.com/axelboc/anki-ultimate-geography/pull/157#issuecomment-549121552

To summarise the discussion, it was decided to not add genders to country names, as learning genders is something you do as part of learning a language, not geography, so it's out of the scope of this deck.

I think this would make for a great new shared deck, though! The front of the cards could show country names without gender and the back of the cards could show them with gender. Feel free to post a link here if you decide to make one 😉

**Comment by GrimPixel** [comment]
When you learn some languages, you will find out how difficult it can be finding genders of countries. In textbooks, there are only several country names are taught. Even Wiktionary is still lacking a large part of them.

**Comment by GrimPixel** [comment]
Maybe you can help me by putting the link to the new shared deck on README.md?

This is what I have done:
https://polyglotclub.com/wiki/Language/Multiple-languages/Vocabulary/Genders-of-countries
