### ISSUE TITLE
Remove Guernsey flag

### ISSUE THREAD

**Issue by GrimPixel** [axelboc/anki-ultimate-geography#241]
According to https://en.wikipedia.org/wiki/Crown_dependencies#Definition, the flag of Guernsey in the deck is actually the flag of Guernsey Island, not of the Bailiwick of Guernsey, which the entry in the deck really indicates.

**Comment by aplaice** [comment]
Thanks for bringing up this interesting (if also rather thorny) topic!

I think that this is quite similar situation to [an issue about Easter Island](https://github.com/axelboc/anki-ultimate-geography/issues/117) where there was an analogous doubt about the map, flag, capital and country info not all "referring" to quite the same entity. In the case of Easter Island, the flag, "country info" and capital "refer" to the special territory of Easter Island (which also includes the uninhabited island of "Isla Salas y Gómez"), while the map shows the island of Easter Island itself. The (IMO sensible) conclusion was to [ignore the discrepancy](https://github.com/axelboc/anki-ultimate-geography/issues/117#issuecomment-520029363).

In this case, the country info refers to a "Crown dependency of the United Kingdom." (i.e. as you point out, the [Bailwick of Guernsey](https://en.wikipedia.org/wiki/Bailiwick_of_Guernsey), while the flag represents a Jurisdiction of the Bailiwick of Guernsey (~ population 60,000), which covers Guernsey Island and several other smaller islands (e.g. [Herm](https://en.wikipedia.org/wiki/Herm) (pop. 60)), but not all the islands which make up the Bailwick ([Alderney](https://en.wikipedia.org/wiki/Alderney) (pop. 2,000) and [Sark](https://en.wikipedia.org/wiki/Sark)). The capital is also of only the jurisdiction (AFAICT the Bailwick as such doesn't have a capital).The map is sufficiently coarse-grained that it's unclear what it depicts.

The principal differences with the Easter Island situation are that:

1. Alderney and Sark are not (quite) uninhabited.

2. The Bailwick of Guernsey and Guernsey have two separate English Wikipedia articles.

Arguments in favour of not worrying about the discrepancy anyway:

1. Wikipedia itself is not entirely meticulous about distinguishing between Guernsey the Bailwick and Guernsey the jurisdiction. For instance, it gives the same population for both entities (and uses the same source...) and in [States of Guernsey](https://en.wikipedia.org/wiki/States_of_Guernsey) it refers to Guernsey (the jurisdiction) as a "British Crown dependency"...

2. The Bailiff of the Bailwick of Guernsey is the head of the States of Guernsey (which is the parliament of only the jurisdiction).

3. Some laws passed by the States of Guernsey also apply to Alderney and Sark "with the consent of the governments of those islands" (whatever that exactly means...). It looks like the relation between Guernsey and Alderney/Sark is a fascinating sort of microcosm of the relation between the UK and Guernsey...

4. Encyclopaedia Britannica [is also slightly fuzzy about distinguishing between the Bailwick and the jurisdiction](https://www.britannica.com/place/Guernsey-island-and-bailiwick-Channel-Islands-English-Channel).

Also, if we were to remove the flag on these grounds, we'd also need to remove the capital. 

If anything, it might make sense to edit the "Capital info", but if somebody is learning about the countries of the world, they probably won't care much that the tiny dependent territory whose capital they're learning, is not technically a "Crown dependency of the UK", but actually a "Jurisdiction of a Crown dependency of the UK" (with the same name as the Crown dependency it's part of). Writing that Guernsey is a Crown dependency isn't really incorrect — it's just a simplification, especially as reality is a bit fuzzy here.

**Comment by axelboc** [comment]
@GrimPixel do you agree with @aplaice's reasoning that it's not worth removing the flag?

**Comment by GrimPixel** [comment]
Well, we can follow Wikipedia: maintain the status quo.
