### ISSUE TITLE
Split the whole deck into “Countries & Territories”, “Seas”, “Continents”

### ISSUE THREAD

**Issue by GrimPixel** [axelboc/anki-ultimate-geography#242]
It may be a better idea to have the option to learn them separately.

**Comment by GrimPixel** [comment]
“Countries & Territories” can be further split according to https://en.wikipedia.org/wiki/United_Nations_geoscheme.

**Comment by horwitz** [comment]
```Instead of creating lots of little decks, it’s a better idea to use tags and/or fields to classify your content. Instead of creating a “food verbs” decks for example, you could add those cards to your main language study deck, and tag the cards with “food” and “verb”. Each card can have multiple tags, which means you can do things like search for all verbs, or all food-related vocabulary, or all verbs that are related to food.```

(from [Anki manual](https://docs.ankiweb.net/#/editing?id=using-decks-appropriately))

**Comment by GrimPixel** [comment]
> `Instead of creating lots of little decks, it’s a better idea to use tags and/or fields to classify your content. Instead of creating a “food verbs” decks for example, you could add those cards to your main language study deck, and tag the cards with “food” and “verb”. Each card can have multiple tags, which means you can do things like search for all verbs, or all food-related vocabulary, or all verbs that are related to food.`
> 
> (from [Anki manual](https://docs.ankiweb.net/#/editing?id=using-decks-appropriately))

Thank you, I've understood how to learn by tags now. 

We can focus on adding subregion tags.

**Comment by axelboc** [comment]
Following @horwitz's comment, please note that the deck already includes [a number of sub-region tags](https://github.com/axelboc/anki-ultimate-geography#deck-structure). I hope they'll help you get through the deck faster. Good luck! 😉 

If you'd like to suggest adding a new sub-region tag, don't hesitate to open a new issue so we can discuss it more specifically.
