### ISSUE TITLE
About country names

### ISSUE THREAD

**Issue by GrimPixel** [axelboc/anki-ultimate-geography#243]
There are some problems:

1. Unnecessary formal names instead of available short names
	1.1 Federated States of Micronesia
	You might think that it can avoid misunderstanding it as a geographic name rather than a country name. But the truth is, there are a bunch of this situation. For example, Taiwan consists of not only the island of Taiwan, but also many smaller islands: https://en.wikipedia.org/wiki/List_of_islands_of_Taiwan. There is a “Micronesia” note, but it can be removed together with “Melanesia” and “Polynesia” when subregion tags are added (https://github.com/axelboc/anki-ultimate-geography/issues/242#issuecomment-606328635). For this reason, “Micronesia” is enough.
	1.2 Czech Republic
	There is already a “Czechia” being widely used: https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic#Adoption_of_Czechia.
	1.3 United States of America
	“of America” can be omitted, just like “United Kingdom”.
	1.4 Aruba, Curaçao, Sint Maarten
	In their “Country info”, “the Kingdom of the Netherlands” can be shorten.
	1.5 Kaliningrad Oblast
	In their “Country info”, “the Russian Federation” can be shorten.
	
2. Inconsistency on the choice of exdonyms or endonyms
	2.1 East Timor; eSwatini; Ivory Coast (Côte d'Ivoire)
	“East Timor” is exdonym, “eSwatini” is endonym, “Ivory Coast (Côte d'Ivoire)” is exdonym and endonym. It would be better to choose the endonyms and mention their exdonyms in “Country info”.
	
3. Lack of Ability to distinguish colloquial and formal country names
	3.1 South Korea; North Korea
	In their formal names, they are both “Korea”. They both claim to be the legitimate political power of Korea. There is no “South” or “North” in their formal names. This is different from names of “South Sudan” and “North Macedonia”. These two situations should be distinguished from each other. It would be better to adopt their formal names: Republic of Korea; Democratic People's Republic of Korea.
	3.2 China; Taiwan
	In their formal names, they are both “China”. They both claim to be the legitimate political power of China. It would be better to adopt their formal names: People's Republic of China; Republic of China.

**Comment by ohare93** [comment]
>3.2 China; Taiwan
In their formal names, they are both “China”. They both claim to be the legitimate political power of China. 

Pretty sure Taiwan wants to *not be China* in any way :sweat_smile: but big brother China is rather insistent.

**Comment by GrimPixel** [comment]
> > 3.2 China; Taiwan
> > In their formal names, they are both “China”. They both claim to be the legitimate political power of China.
> 
> Pretty sure Taiwan wants to _not be China_ in any way 😅 but big brother China is rather insistent.

Sure, but Taiwan has not yet declared independence from China.

**Comment by axelboc** [comment]
Hi @GrimPixel, thanks for all your comments! I'll go through them later today, but I thought I'd reply to this one quickly to bring to your attention our [contributing guidelines](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#country-names), especially the last section on country names. In summary, we use the title of Wikipedia articles as reference.

If you notice a mismatch between Wikipedia and the deck for a particular country, please open a new issue. I don't believe there's a mismatch with any of the countries you've mentioned here, so I'm closing this issue.
