### ISSUE TITLE
Set up Prettier

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#248]
Suggested in #246 by @ukanuk to format `src/style.css` automatically.

To discuss/investigate:

- I don't know whether Prettier comes as a PHP package, so we may have to use NPM and add a `package.json` file. This means adding `npm install` as an additional set-up step for contributors.
- Prettier might be useful to format more files than just `style.css`. It doesn't seem to support CSV, but it does support HTML, JSON, Markdown, etc.
- A pre-commit hook might add unnecessary overhead, as most changes occur in `data.csv`. A CI job could be sufficient, IMO.

**Comment by axelboc** [comment]
Might be worth waiting to see what's happening with Brain Brew (cf. #143).

**Comment by ukanuk** [comment]
There may be a way to get this to work with Github Actions such as the third-party [Prettier Action](https://github.com/marketplace/actions/prettier-action) on the Marketplace. I got the action working on a personal repository, but I am concerned whether it will work for pull requests raised from forks. I realized this potential limitation while reading the [autopep8](https://github.com/marketplace/actions/autopep8) action docs.

Autopep8 suggests using a "ChatOps" slash command style as shown in [slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch), which I'm thinking could potentially be triggered by the fork author. But I have not tested this. Another thought I had was maybe the GitHub action could add a comment to the pull request with the issues as in [Spectral comment](https://github.com/marketplace/actions/spectral-comment).

Maybe there's even a way to have it suggest the code changes [like aplaice did for me](https://github.com/axelboc/anki-ultimate-geography/pull/246#pullrequestreview-386237539), and I was able to implement his changes just by clicking "Commit suggestion".

**Comment by axelboc** [comment]
I think it's still worth waiting for Brain Brew at this point. Perfect formatting is not crucial, so I think we can wait to see how our set-up changes before doing anything.
