### ISSUE TITLE
[NB] Add missing capital info for SADR

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#251]
Reported by @aplaice in https://github.com/axelboc/anki-ultimate-geography/issues/230#issue-587946400:

> Currently, the Norwegian version of the deck doesn't have a "capital info" mentioning that El Aaiún is only the official capital.

**Comment by aplaice** [comment]
I had let this one slip through the gaps, as I'm not sure if a capital info should be added after all.

The "main" Norwegian translation source (The Norwegian Ministry of Foreign Affairs' brochure) doesn't seem to list SADR as a country, at all, either under Vest-Sahara or "Den saharawiske..." (though searching for Vest-Sahara there gives some articles about the political situation in the region, [mentioning El Aaiun](https://www.regjeringen.no/no/aktuelt/svar_hansson/id2474219/) as the capital). 

The Great Norwegian Encyclopædia seems to [only give El Aaiún](https://snl.no/Vest-Sahara) (with varying spelling) and doesn't mention Tifariti or Bir Lehlou in their capacity as capitals. 

Norwegian Wikipedia lists Bir Lehlou as the temporary capital of [Den Sahrawiske arabiske demokratiske republikk](https://no.wikipedia.org/wiki/Den_saharawiske_arabiske_demokratiske_republikk), while that for [Vest-Sahara](https://no.wikipedia.org/wiki/Vest-Sahara) (the name currently used in AUG) only lists El Aaiún. According to English Wikipedia, [Bir Lehlou](https://en.wikipedia.org/wiki/Bir_Lehlou) was the temporary capital only until 2008.

Hence, overall there's little justification to mention Bir Lehlou in the capital info (not to mention that that would be almost certainly outdated), and almost none to mention Tifariti. :/

(Perhaps I'm being overly attached to following the relevant language sources, again...)

**Comment by axelboc** [comment]
Alright, thanks for the research. I'll close this until further notice, then. 👍
