### ISSUE TITLE
Map for White Sea item has text with answer visible

### ISSUE THREAD

**Issue by flaheathrenn** [axelboc/anki-ultimate-geography#257]
The current image for the Map - Country card White Sea has the White Sea-Baltic Canal labelled in the lower-left corner. I suggest the label text for that feature should be removed.

**Comment by aplaice** [comment]
Thanks for filing the issue! That was indeed a problem until recently, but has been fixed on master (see #176):

https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-white_sea.png

The fix will be available on ankiweb once 3.3 is released. In the meantime you could [try importing the deck from git via `CrowdAnki`](https://github.com/axelboc/anki-ultimate-geography#other-languages-and-versions) (I advise backing up your collection first before trying this) or just replace your `ug-map-white_sea.png` with the latest version from GitHub.

**Comment by axelboc** [comment]
FYI, v3.3 won't be long. It's been a while since v3.2!

**Comment by flaheathrenn** [comment]
Thank you both for your kind and patient responses. I have updated to v3.3 and look forward to trying it out!
