### ISSUE TITLE
update deck without losing data

### ISSUE THREAD

**Issue by gpshearn** [axelboc/anki-ultimate-geography#262]
I had apparently changed the note-type from Ultimate Geography-19c7b to just be named Ultimate Geography back in late 2018 when I first started using this deck. Now I want to update to v3.2 but because the cards aren't the same note type it wouldn't alter the old cards. I tried changing the note-type back, but now when I try to upload the new deck version I see the message: "Notes found in file: 321 Notes skipped, as they're already in your collection: 321" The cards don't end up getting changed at all so it looks like I would have to manually go through and make the changes? Does anyone have suggestions for how I can work around this and make the deck update-able again for me?

**Comment by ohare93** [comment]
Late 2018, that means you're on 3.0, right? In that case that should be no problem, but you need to follow the steps laid out in the me, under [Upgrading - Minor Version](https://github.com/axelboc/anki-ultimate-geography#minor-version) which essentially says to *not import with an apkg* (as it sounds like you are doing) and instead install the Anki add-on CrowdAnki and use that to import in the deck. 

Follow the instructions laid out there and you should be good :+1: ping again here if there's anything else

**Comment by gpshearn** [comment]
Whoop, sorry I'm a buffoon that can't follow instructions! That worked perfectly. Thanks so much and sorry for the hassle!
