### ISSUE TITLE
Improve maps of oceans

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#264]
> Identified in https://github.com/axelboc/anki-ultimate-geography/issues/1#issuecomment-610031655

Should ocean maps be made more consistent with locator maps? If they are fine as is, then I'll refocus this issue on the map of the Southern Ocean, which is inconsistent with the other ocean maps.

![ug-map-atlantic_ocean](https://user-images.githubusercontent.com/2936402/78974386-25addb00-7b12-11ea-94aa-9d00ad2434f3.png)
![ug-map-southern_ocean](https://user-images.githubusercontent.com/2936402/78974380-247cae00-7b12-11ea-8039-7f5ed8467d2e.jpg)

**Comment by aplaice** [comment]
Some options are:

1. Leave them as they are.

2. Add a transparent background to the ones that don't have one yet.

    - by getting them SVGised (upstream), by tracing or a similar method

    - by regenerating them as an SVG (from scratch) but with the same projection and the same boundaries as currently

    - by editing the PNGs to add transparency (this is non-trivial, or at least non-trivial if you don't have the right tools (?))

3. Adapting the remainder to the style of the Southern Ocean one.

4. Edit them to follow the continents' maps' style. They could look something like this:

    ![ug-map-atlantic_ocean](https://user-images.githubusercontent.com/16461345/79026621-ba075480-7b89-11ea-8d90-eb87027a7346.png)

    (I followed the boundaries of the Atlantic Ocean set in our current map without thinking about whether they make much sense, for the time being.)

    - However, the Southern and Arctic Oceans might need to be treated alternatively anyway. (I'm not sure how well they'd look — I could try them, if you think it's worth it — it's not very much effort. Antarctica looks OK according to the [current continent maps' style](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-map-antarctica-nobox.png), so they might not be too badly brutalised either.)

5. If the continent style is changed (#265), then that of the oceans could also be adjusted to match.

    - However, as I wrote there I don't see much scope for changing them — zooming in so that only the given continent/ocean is visible might look silly.

**Comment by axelboc** [comment]
I'm definitely for option 4 or 5.

I really like your version of the Atlantic Ocean map, so I'd be happy with option 4. One downside is that the Pacific Ocean would be split in two. Not a big deal, but for argument's sake, how difficult would it be to centre the Winkel III projection on another meridian?

**Comment by aplaice** [comment]
> Not a big deal, but for argument's sake, how difficult would it be to centre the Winkel III projection on another meridian?

Relatively easy. (I had done that for some of the sea maps.)

Actually, since the continent maps are centred on 15 ° (which avoids eastern-most Russia getting split), it might be better to use that for the remaining seas. (I hadn't bothered with the sea maps, since using 0 ° made things minimally easier, at least to start off with, it didn't matter for the "main" parts of the maps and wasn't really visible in the "mini map".)

I probably won't have time to get things done today or tomorrow, though. :/

**Comment by axelboc** [comment]
Oh no rush, all of these can wait for v3.4. There's already way too much in v3.3! 😄
