### ISSUE TITLE
Improve maps of continents

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#265]
> Identified in https://github.com/axelboc/anki-ultimate-geography/issues/1#issuecomment-610031655

Should the maps of continents be made more consistent with the other locator maps (e.g. rectangular, centred on continent)?

![ug-map-asia](https://user-images.githubusercontent.com/2936402/78974841-28f59680-7b13-11ea-9e10-1e593cc7154a.png)

**Comment by aplaice** [comment]
I don't really see a means of zooming into the continents without losing context. We're using the same projection as for the remaining maps, just not zoomed into a rectangular frame and hence not requiring a mini-map. 

Hence, I think that the continent maps are as consistent with the remaining locator maps as they can be, and would vote for probably closing this.

One tiny difference is that these maps (unlike the others) have a graticule, but I think that in the zoomed-out case this looks nice (at least in the source SVG). 

Without the grid, Asia would look like this:

![ug-map-asia](https://user-images.githubusercontent.com/16461345/79006979-84974280-7b5a-11ea-8b1d-5763b7313aa5.png)

(Actually, given the low resolution, the grid is barely visible, so I don't think I have a preference either way in our PNGs...)

**Comment by axelboc** [comment]
How about "rotating" the globe to focus on a particular continent, since meridian-centring is not as ubiquitous in Asia, Oceania and America? An orthographic projection would be consistent with the ocean maps:

[![500px-Asia_(orthographic_projection) svg](https://user-images.githubusercontent.com/2936402/79040653-46e1fa80-7bea-11ea-8e90-107ab3988cd2.png)](https://en.wikipedia.org/wiki/Asia#/media/File:Asia_(orthographic_projection).svg)

**Comment by axelboc** [comment]
Hmm seeing how good the ocean maps would look in the Winkel III projection (#264), I'm less convinced by the orthographic projection... I'd be happy with just removing the graticules.

**Comment by aplaice** [comment]
The orthographic projection does look nice, and it might be better for [Antarctica](https://commons.wikimedia.org/wiki/File:Antarctica_(orthographic_projection).svg) and [Australia[(https://commons.wikimedia.org/wiki/File:Australia_(orthographic_projection).svg).

(I'd be down for applying consistency either way.)
