### ISSUE TITLE
New Blurred Flag Cards Are Blank on AnkiDroid

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#286]
Unsure whether to post this as an [issue on AnkiDroid](https://github.com/ankidroid/Anki-Android/issues) :thinking: 

Essentially the Flag -> Country card with the new css for the blurred flag makes the entire card blank :scream: This below screenshot (of nothing!) is for Paraguay.
 
![Screenshot_20200417-081955](https://user-images.githubusercontent.com/1471350/79538592-f0127000-8084-11ea-849d-946055a61ccb.jpg)

Changing to Night Mode has no effect.

Can anyone else reproduce this? :thinking: :sweat:

**Comment by ukanuk** [comment]
It works fine for me on AnkiDroid. 

Has AnkiDroid synced the new media? The blurred flags are new images. I know in the past I've turned off AnkiDroid media sync because it makes syncing take longer in the 99% of instances where no new media is needed. But then in the 1% of times where new media is necessary, I forgot to turn the option back on and see missing images.

**Comment by ohare93** [comment]
I have never turned the option off, but a double check confirms the file is indeed on my phone. Though viewing it in an SVG viewer app displays a non-blurred flag :thinking: 

Regardless, a lack of the media file would not make the entire card blank. It seems to me this could be some type of corruption :sweat: since the file looks not blurred. I will do a full database sync back onto my phone, and take a look again.

**Comment by ukanuk** [comment]
Hm, good point that the entire card is blank, not just media. Hopefully the full database sync fixes it? 

Also, do both these images really look non-blurred for you? The first image is the original one that should display on card backs, and the second image is the blurred one that should display on card fronts. Or maybe your browser will show the latter image blurred, but your SVG viewer app won't display it blurred? It is an SVG blur effect which maybe isn't supported by all viewers, I don't know. I assumed the effect was widely supported and it worked in the browsers I tried.
* [src/media/ug-flag-paraguay.svg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-flag-paraguay.svg)
* [src/media/ug-flag-paraguay-blur.svg](https://raw.githubusercontent.com/axelboc/anki-ultimate-geography/master/src/media/ug-flag-paraguay-blur.svg)

**Comment by ohare93** [comment]
They look blurred everywhere I look, apart from on Android, when I navigate to them. I do not yet know if that file is indeed unblurred (though it is a different file size than the normal one) or if it is an issue with AnkiDroid. Could be a coincidence, will find out.

Cannot find a "just download all my media again" button, so I suppose I may have to manually delete them :thinking: or just delete my account and remake it :sweat_smile: anyways, will inform when I know more.

**Comment by ukanuk** [comment]
Something else you could test is https://ankiweb.net from your phone browser. Unfortunately it doesn't seem to support searching for and previewing cards, but you can make a filtered deck with `card:4 Paraguay` to get it without having to wait for the review. I just tested this, and the blurring/non-blurring works here for me as well. 

AnkiDroid has a button for ["Force Full Sync" in the Advanced settings](https://docs.ankidroid.org/manual.html#_advanced), but my guess is that would only reset the decks and not the media.

Good luck, and looking forward to hearing what you find out!

**Comment by axelboc** [comment]
I confirm this is working fine for me in AnkiDroid. Any update on this @ohare93?

**Comment by ohare93** [comment]
Still an issue for me, sadly. Though I do not review on mobile much currently. I have absolutely no issue with any other cards in the deck, apart from these types :thinking: very strange

I will open an issue on AnkiDroid and see what comes of it. Feel free to close this until I can explicitly say it is an issue with the assets here :+1:

**Comment by ukanuk** [comment]
Did you happen to check on your phone with https://ankiweb.net

**Comment by ohare93** [comment]
Just tried, good idea. No issue at all, I can see the properly blurred card on the front and the normal card on the back. Strange.

**Comment by axelboc** [comment]
Hmm that's annoying, I hope you get to the bottom of this. Feel free to re-open when you learn more. Good luck!
