### ISSUE TITLE
pbkac: extra containing folder foils import selection

### ISSUE THREAD

**Issue by khonkhortisan** [axelboc/anki-ultimate-geography#287]
on step 7 of https://github.com/axelboc/anki-ultimate-geography#other-languages-and-versions I get this popup
```
---------------------------
Anki
---------------------------
Error: There is no C:\Users\Khonkhortisan\Downloads\Ultimate_Geography_v3.3_EN_EXTENDED\Ultimate_Geography_v3.json file inside of the selected directory. While trying to import deck from directory C:\Users\Khonkhortisan\Downloads\Ultimate_Geography_v3.3_EN_EXTENDED
---------------------------
Aceptar   
---------------------------
```
and then after closing it this error
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://help.ankiweb.net/discussions/add-ons/). 
Información de depuración: 
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-16 18:12:44

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1788670778\anki\ui\action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1788670778\importer\anki_importer.py", line 91, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1788670778\importer\anki_importer.py", line 80, in import_deck_from_path
    importer.load_from_directory(directory_path, import_media)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1788670778\importer\anki_importer.py", line 46, in load_from_directory
    self.load_from_file(self.get_deck_path(directory_path))
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1788670778\importer\anki_importer.py", line 25, in load_from_file
    raise ValueError("There is no {} file inside of the selected directory".format(file_path))
ValueError: There is no C:\Users\Khonkhortisan\Downloads\Ultimate_Geography_v3.3_EN_EXTENDED\Ultimate_Geography_v3.json file inside of the selected directory
```
C:\Users\Khonkhortisan\Downloads\Ultimate_Geography_v3.3_EN_EXTENDED\Ultimate Geography [Extended]\Ultimate Geography [Extended].json is the file it didn't find. If I import C:\Users\Khonkhortisan\Downloads\Ultimate_Geography_v3.3_EN_EXTENDED\Ultimate Geography [Extended] instead it works fine.
This is a CrowdAnki issue for not checking the containing folder or a windows issue for creating a containing folder or a documentation issue for not explicitly stating to open the lower folder or just plain user error. Do with this issue what you will.

**Comment by ohare93** [comment]
Looks like you extracted the "Ultimate Geography [Extended]" folder (the right one) into a folder of the same name as the zip "Ultimate_Geography_v3.3_EN_EXTENDED" and pointed CrowdAnki to that top level one (which contains no json).

> This is a CrowdAnki issue for not checking the containing folder or a windows issue for creating a containing folder or a documentation issue for not explicitly stating to open the lower folder or just plain user error.

Bit of each? :sweat_smile: 
1) I suppose the documentation could be more specific that it is the "Ultimate Geography [Extended]" folder to point to
1) CrowdAnki could be smarter about finding the file in the first place
1) All of my unzipping programs just take the folder out if it's the only thing in the zip :thinking: I only get "Ultimate Geography [Extended]"

Anyways, no major issue here I think, but thanks for bringing it up. Glad you got yours working in the end :+1:

**Comment by ukanuk** [comment]
Currently the released `Ultimate_Geography_v3.3_EN_EXTENDED` zip contains the folder `Ultimate Geography [Extended]` which then contains the json file and media folder. When I open the zip on Windows and click "Extract All", it defaults to creating the files under 
`...\Documents\Ultimate_Geography_v3.3_EN_EXTENDED\Ultimate Geography [Extended]`

Note the default-created folder-within-folder. I think it would make sense for the zip to contain the json and media folder directly, rather than stored within a subfolder. 

It shouldn't be a big deal, but in my opinion is worth it if it reduces potential confusion from people who want to experience the UG extended deck and this is the primary reason they're installing CrowdAnki (just like me).

**Comment by ukanuk** [comment]
It sounds like this could be a difference between how different operating systems unzip. Windows by default creates a new folder to hold the contents of an unzip, other systems like @ohare93's by default do not create a new folder. 

If this is the case, then the only resolution is to pick one way or the other and document it.

Maybe an even better solution would be to updated CrowdAnki with the option `CrowdAnki: Import from zip`. And this option would accept either a zip holding JSON and media folder directly, or holding a subfolder with JSON and zip.

**Comment by axelboc** [comment]
With 7zip, you get the option to _Extract Here_ which doesn't create an extra folder, and _Extract to [zip-filename]_, which does.

#### Pros of zipping the deck's folder

- You always end up with a folder that is named exactly like the deck it contains.
- If you open the zip, having a folder in there means that you can drag-and-drop it to extract it.
- If you select _Extract Here_ (or similar) and you're in your _Downloads_ folder, for instance, then the deck's content doesn't get lost amongst your other files and folders.

So I wouldn't recommend changing the current process, but I agree that this subtlety could be clarified in the documentation.
