### ISSUE TITLE
Problem about the flags

### ISSUE THREAD

**Issue by yen67** [axelboc/anki-ultimate-geography#289]
Hello, 
First of all, thank you for the work that you did !
I'm drawing this mail because I have a certain problem : 
When I'm doing this deck, I cannot see the flag or the emplacement in the earth of the country.
How I need to do ? 
Thank you for your answer in advance :)
![Capture](https://user-images.githubusercontent.com/63901595/79632885-72bd2d00-8162-11ea-91c3-ebd8bc7ef4e8.PNG)

**Comment by ukanuk** [comment]
The cards in this deck only test one thing at a time. Your screenshot is of a "Country" to "Capital" flashcard. If you keep going, you'll see cards which quiz you on the flags and maps.

**Comment by ukanuk** [comment]
For more info, you can take a look at the Readme: https://github.com/axelboc/anki-ultimate-geography/blob/master/README.md

**Comment by axelboc** [comment]
Sorry, thought the thumbs up were from @yen67. I'll leave this open in case it turns out to be another problem. Let us know how you go @yen67 😉

**Comment by aplaice** [comment]
In addition to what @ukanuk wrote, if for some reason (for example, always having the full context available) you *do* want the Map and Flag to be visible on the `Country -> Capital` cards (and not only the `Country -> Map`/`Map -> Country` and `Country -> Flag`/`Flag -> Country` cards, respectively), you can [edit the relevant card template](https://docs.ankiweb.net/#/templates/intro), (if you prefer there's also [a French, if possibly outdated version of the manual](https://apps.ankiweb.net/docs/manual.fr.html#cartes-et-mod%C3%A8les)) e.g. adding the following:

```html
{{#Flag}}
  <br/>
  <div class="type">Flag</div>
  <div class="value value--image value--front">{{Flag}}</div>
{{/Flag}}
{{#Map}}
  <br/>
  <div class="type">Location</div>
  <div class="value value--image">{{Map}}</div>
{{/Map}}
```

I'd recommend adding this only to the back template, not the front template. (I personally wouldn't find this particularly useful, but I don't think it'd be harmful, either.)

<hr/>

Please feel free to ask if you have any further questions!

**Comment by axelboc** [comment]
Alright, no news good news? :smile: Feel free to re-open if needed.

**Comment by yen67** [comment]
Sorry, I never used Gifthub and I thought that you have closed the discussion. So It works very well ! thank you for your advice and have a nice day !
