### ISSUE TITLE
Naming of the `UG::North+Central_America` tag

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#295]
According to Wikipedia's definitions, [Northern America](https://en.wikipedia.org/wiki/Northern_America) ≈ USA + Canada + Greenland, while [North America](https://en.wikipedia.org/wiki/North_America) = Northern America + Central America + Caribbean (which is also what we show on [our own continental map](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-map-north_america-nobox.png)).

Our `UG::North+Central_America` tag currently covers Wikipedia's Northern America and Central America.

Hence, I'd suggest either:

1. Renaming the tag `UG::Northern+Central_America` and keeping its "contents" the same.

2. Renaming the tag `UG::North_America`, adding it to all of the Caribbean notes and (possibly) removing the `UG::America` tag.

**Comment by axelboc** [comment]
Option 1 for me. The Caribbean notes are notoriously numerous and difficult to learn, so I'd keep them in a separate tag.

**Comment by aplaice** [comment]
Just in case, in **2** I'm not suggesting removing the `UG::Caribbean` tag, so the Caribbean notes would have both the `UG::North_America` and the `UG::Caribbean` tags. If your worry is that the "North(ern) America" tag shouldn't contain the Caribbean notes, then that indeed is a problem. It can obviously be worked around with negations (`tag:UG::North_America -tag:UG::Caribbean`), but for a beginner (the most likely user of the tags) that is probably too involved, so I'm now leaning towards **1** as well.

<hr/>

As an aside, are the regional tags (Mediterranean, South East Asia) supposed to be applied to islands (Sicily, Bali etc.) as well? (Currently they aren't.)

**Comment by axelboc** [comment]
In #244, I came to the realisation that it may be easier to more logical to just remove this tag altogether, as it is the equivalent of `tag:UG::America -tag:UG::South_America -tag:UG::Caribbean`. Quoting myself here for reference:

> This makes me wonder now whether tags `UG::South_America` and soon-to-be-renamed `UG::Northern+Central_America` are worth having at all, since they contain 25 notes together. 🤔 Perhaps we could just remove the latter since it makes the least sense as per naming discussions in #295 .

**Comment by axelboc** [comment]
> As an aside, are the regional tags (Mediterranean, South East Asia) supposed to be applied to islands (Sicily, Bali etc.) as well? (Currently they aren't.)

Hmm, they probably should, you're right.

**Comment by ukanuk** [comment]
> In #244 (comment), I came to the realisation that it may be easier and more logical to just remove this tag altogether, as it is the equivalent of tag:UG::America -tag:UG::South_America -tag:UG::Caribbean.

I like this, although I'd continue and ask whether the `UG::America` tag is really useful? Wouldn't a `UG::North_America` tag be more useful?

So the Americas could get just these three (or four) tags:
* `UG::South_America`
* `UG::North_America`
* `UG::Caribbean`
* `UG::Central_America` could make sense, too. It'd be basically achievable with `tag:UG::North_America -tag:UG::Caribbean`, although this search would additionally include USA+Canada+Mexico+Greenland(?), which arguably isn't a big deal. But probably easier to include it since I feel like it's a pretty common grouping (and thus more likely to be actually used by someone).

**Comment by aplaice** [comment]
> In #244 (comment), I came to the realisation that it may be easier and more logical to just remove this tag altogether, as it is the equivalent of `tag:UG::America -tag:UG::South_America -tag:UG::Caribbean`.

To summarise, if we are to minimise tag redundancy for the Americas, then we have the following "equivalent" (by adding/subtracting we can recreate all the same groupings of countries) sets of tags under discussion (there are obviously more options, but these are probably the most sensible):

1. `UG::Northern+Central_America`, `UG::South_America`, `UG::Caribbean`.
    - **+** IMO they're the most likely tags that'd be individually used by a learner (North America, but without all the many Caribbean countries, South America and the Caribbean). I can easily imagine somebody wanting to use each of these, on their own. (Being able to use a single tag, rather than a combination of tags, might be convenient for a beginner, as noted [above](https://github.com/axelboc/anki-ultimate-geography/issues/295#issuecomment-619517517).)
    - **+** IMO "adding" tags is probably slightly more intuitive (for an Anki beginner) than subtracting them, so all other things being equal, tags that aren't subsets of each other are preferable. (By "all other things being equal" I mean all the sets of tags being as natural — replacing `UG::Asia`, `UG::Middle_East` and `UG::Southeast_Asia` with `UG::Asia_but_not_Middle_East_or_Southeast`, `UG::Middle_East` and `UG::Southeast_Asia` would be evidently idiotic.)
    - **-**  The Caribbean lacks a continent tag, which feels disorderly.

2. `UG::North_America`, `UG::South_America`, `UG::Caribbean`.
    - **+** This most closely fits the grouping we otherwise use, of having tags for each of the "traditional" continents, and then tags for sub-regions, if necessary.

3. `UG::America`, `UG::South_America`, `UG::Caribbean`.
    - **-** We otherwise don't use "super-groupings". (We don't have a Eurasia or an "Old World" tag.)

(My focus on beginners is because I think they're likely to form a disproportionate percentage of those using the regional/continental tags — they might want to try things out without getting overwhelmed. I've read `anki-ultimate-geography` referred to as a gateway drug into Anki, so they might be Anki beginners as well.)

Overall, my preference is **1** > **2** > **3**.

<hr/>

In terms of an "equitable" division of tags among the continents, 3 tags for 56 notes in the Americas (population 960 M) doesn't seem excessive. If we add West and East Africa, then Africa (62 notes, population 1.3 G) will have ~3.4 tags (Africa, West Africa, East Africa, Mediterranean (0.3) and Middle East (0.1). Asia (56 notes, population 4.6 G) has ~3.2 tags (Asia, SE Asia, Mediterranean (0.3) and Middle East (0.9)).

Obviously, this calculus might change if we cull many of the dependent Caribbean states.

**Comment by axelboc** [comment]
I completely forgot that the deck follows the seven-continent system now, which was not the case when I first created the tags -- in France, we're taught the [six-continent system](https://en.wikipedia.org/wiki/Continent#Number) where North and South America are a single continent.

What you are both suggesting makes total sense, then: `UG::America` is inconsistent with the continent notes and definitely has to go.

I'm down with option 2, so we end up with two continent tags: `UG::North_America` and `UG::South_America`, and one subregion tag: `UG::Caribbean`. I don't think a tag for Central America is needed.

**Comment by aplaice** [comment]
@axelboc had convinced me to prefer **1** over **2**, but it seems the tide is changing. :) 

As it seems to be (close to) a consensus, I'll implement 2.

**Comment by ukanuk** [comment]
> in France, we're taught the six-continent system where North and South America are a single continent.

😮 Cool, had no idea other systems even existed!

**Comment by ukanuk** [comment]
> + IMO "adding" tags is probably slightly more intuitive (for an Anki beginner) than subtracting them, so all other things being equal, tags that aren't subsets of each other are preferable.

100% agree with this, and IMO is the primary reason to use option 1. But if people like option 2, that also seems good to me.

**Comment by axelboc** [comment]
It might help a tiny bit to add some examples to the [_Custom study_ section](https://github.com/axelboc/anki-ultimate-geography#custom-study), like `tag:UG::North_America -tag:UG::Caribbean`.

**Comment by aplaice** [comment]
I've implemented **2**, but switching to **1** should be straightforward.
