### ISSUE TITLE
Add continents

### ISSUE THREAD

**Issue by totsubo** [axelboc/anki-ultimate-geography#31]
Hello. Firstly I want to thank you for this great deck.

The deck contains oceans and seas, would it be possible to also add continents?

My daughter is starting elementary school and they are first starting by studying continents, then moving on to countries.

Thanks!

**Comment by axelboc** [comment]
Sounds good. The 7-continent model seems to be the most commonly used - https://en.wikipedia.org/wiki/Continent

I might mention _Oceania_ in the sub-text of the _Australia_ card. It's the term used in some countries.

**Comment by totsubo** [comment]
Thank you!

**Comment by axelboc** [comment]
It's about adding new notes for the seven continents. Got to start somewhere!
