### ISSUE TITLE
Disambiguate Macau & Hong Kong Maps

### ISSUE THREAD

**Issue by cburroughs** [axelboc/anki-ultimate-geography#314]
https://github.com/axelboc/anki-ultimate-geography/blob/v3.3.1/src/media/ug-map-macau.png
https://github.com/axelboc/anki-ultimate-geography/blob/v3.3.1/src/media/ug-map-hong_kong.png

These maps look almost the same.

**Comment by aplaice** [comment]
Thanks for reporting!

These would definitely benefit from a zoom box. (We're in the process of improving some of our maps.)

In the meantime, if you look very closely, you can distinguish them by the fact that Hong Kong is east of the Pearl River estuary, while Macau is west of it — at least that's what I use. (Obviously, squinting at the map shouldn't be necessary, though.)
