### ISSUE TITLE
Spanish translation typo

### ISSUE THREAD

**Issue by AlvaroCalo** [axelboc/anki-ultimate-geography#321]
Hello,

I founded a mistake in the Spanish translation. In the Philippines note, it is written in the Country field Flipinas instead of Filipinas (Fli wrote instead of Fil).

Here the Wikipedia article in Spanish: https://es.wikipedia.org/wiki/Filipinas

I'm new to GitHub and developing,  I read the documentation and I think this is the right place to tell this issue. I also searched for this issue in case it is been already reported and I didn't find it. I'm sorry if I'm not right. I'm also learning PHP and Web Development, maybe in a couple of months (when I will have more time), I will be able to submit a pull with the solution if you agree there is a mistake.

Thank you for your time and sorry for my bad English, I'm learning English too. I'm a student ;)

Álvaro

**Comment by axelboc** [comment]
All fixed, thanks for reporting! :tada:
