### ISSUE TITLE
Portuguese deck

### ISSUE THREAD

**Issue by ghost** [axelboc/anki-ultimate-geography#324]
Hi

I read #313 (Dutch translation) and I make his words mine, but about portuguese.
(https://github.com/axelboc/anki-ultimate-geography/issues/313)

My condition is similar to hoi3, I well intended but I know nothing about github...

I'll be waiting too.

From the bat, I noticed that portuguese translations vary a lot from pt-pt and pt-br. I can do them both, I'm a language nerd, and I think I share your passion for accuracy.

Contrary to english, in portuguese, capitals and coutries, have sometimes different names (Irão/Irã, Amesterdão/Amesterdã, etc...) in european portuguese or brazilian portuguese.

It is not productive or accurate to hide one of the translations... So since you were talking about Brain Brew, or other solutions, I was wandering what would be the best solution:

To make one portuguese deck always showing the differences, like:

Irão (ptpt) / Irã (ptbr)

(Like Wikipedia does)

Or to make separate decks.

So, I'll wait to see developments anyway, and I hope to be able to contribute to this beautiful project, adding a language that can bring 200 million people more to the fold...

**Comment by pt-pt-guy** [comment]
I thought this would be a LOT easier... Like someone would send me a CSV file, I would translate it, save it, and give it back...
I'm sorry, I'm completely out of depth here... :(

**Comment by axelboc** [comment]
No worries at all! Just download this file and post it back here when you're done 😉 https://github.com/axelboc/anki-ultimate-geography/blob/translation/src/data.csv

**Comment by pt-pt-guy** [comment]
Thanks axelboc....

But I click on the link, and it sends to a place where I can see the file... How do I download it?

For the life of me, I've searched every pixel of the page for a download option...

**Comment by axelboc** [comment]
Hey,  you're right, it's not obvious. 😌 Click on "Blame" and then tell you browser to save the file (with Ctrl+S if your on Windows, for instance).

**Comment by pt-pt-guy** [comment]
I did this, and I'm able to save it.
The file is even called data.csv by default, BUT if I open it with a spreadsheet program like LibreOffice Calc, I can see what's written that it's an HTML file and not a real CSV file...

**Comment by aplaice** [comment]
I think that `raw` (the button next to blame) would be far more convenient. (You can, at a pinch, use the "blame" interface, but you need to copy-paste the actual CSV data rather than just saving with Ctrl-S.)

**Comment by axelboc** [comment]
Silly me, sorry for the confusion... I did mean to say "Raw"... 😓

**Comment by pt-pt-guy** [comment]
Dear friends

I volunteer in too many projects and I'm spread too thin.

I'm very sorry, but I will be withdrawing from this project (without having helped at all, I know).

I hope you'll forgive me and "keep on keeping" this amazing deck.

Thank you all!

**Comment by axelboc** [comment]
Alright @ghost, no worries! Take care 😉
