### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by emiham** [axelboc/anki-ultimate-geography#329]
I've been waiting to start this for a while, but I'm creating this issue now just so that someone can comment when the new translation system is ready. 

I actually translated the whole deck to Swedish a long time ago, but just within Anki, and unfortunately I ended up deleting the deck. It's probably not that big of a loss though, since it wasn't as rigorous as a proper translation should be, and so I would have ended up redoing it anyway.

**Comment by ohare93** [comment]
New deck manager is pulled :+1: The source csv has now been broken into multiple separate csv files inside `src/data`. 

You can now add your translation :clap: This requires 2 steps to do it yourself:
1) Add the translation as a column in each of the source files.
2) Edit the Brain Brew recipe in `recipes/source_to_anki.yaml` to build your new column to your new language deck. Just copy pasting what the others do, and changing it to match your new columns will do :+1: 

I am happy to do the second step, if you do the first :wink: 

Better yet, if you have created the translation inside Anki itself then I can do it all in <5mins, as the new deck manager can also import _from CrowdAnki_ to our Source control. Feel free to export the deck, upload a zip of it here, and I will do magic :clap: :grin:

**Comment by emiham** [comment]
Great, I did the bulk of the work already, but was procrastinating finishing up. Now that it can be pushed I'll get back to it soon!

**Comment by Epitaxi** [comment]
Do you need any help with the translation @emiham or is it possible to download the translated deck now (or soon)?

**Comment by emiham** [comment]
I should be able to finish up this weekend, unless anything unexpected gets in the way. Then it needs to be merged into the main branch which I don't know how long it will take, but it seems like it's a pretty quick process. 

If you have time you'd be very welcome to look over the current translation in my fork, all countries and capitals are translated already, but a second pair of eyes would be great!
