### ISSUE TITLE
Why is the preferred format for maps SVG?

### ISSUE THREAD

**Issue by admiral-ackbar** [axelboc/anki-ultimate-geography#330]
They are based on the Wikipedia SVG locator maps, and the flags are already SVGs, so why are the maps different?

**Comment by axelboc** [comment]
It's just a file size issue. SVG maps are typically quite heavy, so we convert them to PNG to save space.

The reduction in quality is minor compared to the benefit of having a very small deck (12 MB) that doesn't take much space on people's phones and uses very little mobile data to synchronise. A small deck is also convenient when releasing new versions, especially now that we have so many versions (extended and translated).

At some point in the future, we might increase the size of the PNGs to gain on quality, but I don't think we'll switch to SVG, as the difference is quite significant.
