### ISSUE TITLE
Publish wikidata SPARQL queries?

### ISSUE THREAD

**Issue by gitonthescene** [axelboc/anki-ultimate-geography#332]
Hello, this is probably less a request than a heads up.  I recently ran across the [Wikidata query service](https://query.wikidata.org/), which you can use to do searches on data gleaned from wikipedia such as the following:

``` sql
SELECT DISTINCT ?state ?stateLabel ?shape ?population ?capitalLabel WHERE {
  ?state (wdt:P31/(wdt:P279*)) wd:Q3624078;
    p:P463 ?memberOfStatement;
    wdt:P3896 ?shape;
    wdt:P1082 ?population;
    wdt:P36 ?capital.
  ?memberOfStatement rdf:type wikibase:BestRank;
    ps:P463 wd:Q1065.
  MINUS { ?memberOfStatement pq:P582 ?endTime. }
  MINUS { ?state (wdt:P576|wdt:P582) ?end. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY (?stateLabel)
```

It's probably not possible to have a single query represent all the criteria used, but it might be worth playing with to see how close you can get.

Basically Wikidata maintains an RDF representation of data gleaned from Wikipedia (by no means complete because the transfer is manual), which amounts to a series of statements about a Wikipedia entry.  This is the entry for [Sri Lanka](https://www.wikidata.org/wiki/Q854).  A query is basically a list of statements with variables in them which searches the database for entries with variables that make all the statements true.  You can find the symbol for a given statement from the linked entry.  (for instance, wdt:P36 means "has capital" which you can find on the country page)

I'm still wrapping my head around it, but I thought I'd share.

**Comment by axelboc** [comment]
Good to know, thanks for sharing! Definitely something we should keep in mind in the long term. It could be used to check for outdated info in a GitHub Action.
