### ISSUE TITLE
Norwegian capital info for Nauru and Switzerland

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#335]
In the case of both countries there is no official (*de jure*) capital, but there is a *de facto* one. This is described in the relevant `Capital info`s in English, German, Spanish and French, since the information is mentioned in the relevant Wikipedia articles in the given languages. In the case of Norwegian the situation is trickier, since there are [three listed sources](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md#norwegian-bokm%C3%A5l). The question therefore is whether to include an NB `Capital info`, and if so, what.

### Nauru
For Nauru, the [*Country names, capitals and national holidays* brochure](https://www.regjeringen.no/no/dokumenter/statsnavn-og-hovedsteder---n/id87852/#nru) lists Yaren as the capital without any qualifiers (for comparison, for the Netherlands and Tanzania, it does mention their special situations, so it's not the case that being a brochure it's excessively brief).

The [SNL](https://snl.no/Nauru) however does mention that there's no official capital:

> Det er ingen offisiell hovedstad, men regjeringen har tilhold i Yaren.

[Wikipedia](https://no.wikipedia.org/wiki/Nauru) also mentions that Yaren is just the de facto capital.

### Switzerland

Again, the [brochure](https://www.regjeringen.no/no/dokumenter/statsnavn-og-hovedsteder-s/id87857/#ch) does not mention anything special about the capital.

Nor does [SNL](https://snl.no/Sveits) AFAICT.

[Wikipedia](https://no.wikipedia.org/wiki/Sveits) does however say that Bern is only the de facto capital.

(See also #334.)

### Potential translations

The obvious would be to copy directly from SNL:

> Det er ingen offisiell hovedstad, men regjeringen har tilhold i Yaren.

but it's a bit verbose.

Perhaps this?

> Nauru har ingen offisiell hovedstad; Yaren er regjeringssete.

("har ingen offisiell hovedstad" has some google results).

<hr/>

(@Vages, if you have time, though obviously this isn't urgent.)

**Comment by Vages** [comment]
> Nauru har ingen offisiell hovedstad; Yaren er regjeringssete.

is a great translation!

**Comment by Vages** [comment]
As for official sources not mentioning the capital's "de facto"-ness: I don't think I've ever come across a Norwegian tabular representation of country and capitals that acknowledges capital ambiguities (other than the South African tri-capital solution). I don't know why, but the Norwegian foreign ministry does not have an official "a country must have a capital", so you're not treading on any toes.

**Comment by aplaice** [comment]
Thanks for the confirmations and for the fast reply! :)
