### ISSUE TITLE
v4.0-beta Release Notes Suggestions

### ISSUE THREAD

**Issue by ukanuk** [axelboc/anki-ultimate-geography#338]
Thank you guys for the incredible amount of work over the last few weeks and months!

1. I thought I experienced a critical bug for this major upgrade, because Ceuta stayed in Anki in its entirety in the main deck (not legacy deck). But in fact, I needed to change the my CrowdAnki config. I had "Do Not Move Existing Cards" *checked*, but obviously this leaves Ceuta in the original deck the entire time. And because CrowdAnki can currently only modify notes and not delete notes entirely, this means Ceuta stays in the deck despite no longer being official. So, add a new Step 0 to check CrowdAnki config and ensure there is NO CHECKMARK on the setting "Do Not Move Existing Cards", and then re-start Anki to ensure the setting takes effect.
1. Add a new upgrade Step -1, to make a backup of your entire collection (File -> Export with both Format = Anki Collection Package and also Include Media = Checked), in case someone forgets (thankfully I did make a backup out of habit, not sure whether everyone does this and it was definitely helpful in my case).
1. Under **If you don't like the removals**, specifically note that you only keep your progress on completely removed notes. Wording from the Legacy Deck notes can also potentially be clarified, but they're fine honestly: *~~Some~~All of your progress for the cards in the removed content has had to be reset, which is why ~~some~~ cards are marked as \"new\". (No progress will have been lost in the main deck.)* Maybe include examples:
   1. Greece is still in main deck with capital+flag+map cards, along with all progress
   1. Christmas Island is moved to Legacy deck with capital+flag+map cards, along with all progress
   1. Turks and Caicos keeps map card(s) in main deck with existing progress. For capital+flag cards, a new note without review history is generated in the Legacy deck. Progress is therefore lost for capital+flag cards.
2. From your release notes, remove the sentence "Just don't move the cards back into the main UG deck, or you will lose content the next time you upgrade!" I thought the particular deck for a card was irrelevant, CrowdAnki updates cards by ID and the only time it pays attention to decks is at the very end, where it (optionally) moves all imports into a particular deck (as noted in first point above)? And since the Legacy cards have IDs which do not exist in regular UG deck, no imports will delete any Legacy content.

**Comment by axelboc** [comment]
1. Had you enabled the setting yourself, or was it the default? If it was the default, I can't decide whether it's a good thing or a bad thing 🤔 😄 -- either, way, I've added the step 👍 
2. I don't think a back-up is required. Once we've identified potential pitfalls, the process should be fairly straightforward. Also, if something bad happens, you can always delete the deck and the note model and force a re-download from Anki Web. Worst comes to worst, you clean import and lose your progress on UG -- it's annoying but it's not the end of the world either, IMO.
3. I've reworded the section. Let me know if it's clearer or if you still think I should add examples.
4. Oh right, makes total sense! Great news, then. 😄 I've removed the sentence.

**Comment by aplaice** [comment]
> Had you enabled the setting yourself, or was it the default? If it was the default, I can't decide whether it's a good thing or a bad thing thinking smile -- either, way, I've added the step +1 (EDIT: hmm, the option is unchecked for me, so I take it you must have ticked it at some point -- that's reassuring, because it means most users won't be affected even if they forget to check).

I'm pretty sure that by [default it's off](https://github.com/Stvad/CrowdAnki/blob/a42041f4eef56831d7607bc09ec0e7ba5babc545/crowd_anki/config/config_settings.py#L50). 

However, I'd add a comment that the setting does not need to be off for **Step 5**. (It seems obvious, but still...) Perhaps:

> (You can turn the option back on after step 4, if you want.)

at the end of **Step 3**.

> 2. back-up

I'm generally in favour of encouraging people to back-up, just in case, but you're right that the procedure should be mostly harmless, and adding even more steps might be off-putting. (It's possible that not everybody uses Ankiweb, though.)

> 4.

Yeah, the notes wouldn't get deleted. The only disadvantage is if somebody tries to export their modifications with CrowdAnki, but for AUG it's probably a very rare occurrence and it wouldn't be a major issue anyway.

<hr/>

There's a typo (`reasonable comprise` → `reasonable compromise`).

<hr/>

Finally, hooray! :)

**Comment by axelboc** [comment]
I've added a sentence about backing up the deck before the list of steps, with a link to Anki Manual. I actually discovered that Anki has auto-backups!

**Comment by ukanuk** [comment]
> Had you enabled the setting yourself, or was it the default?

I had enabled it myself awhile ago and forgot about it. So it took me about an hour to realize that's what was causing my issues, which is why I think it's helpful to note.

> I actually discovered that Anki has auto-backups!

It does make backups by default, although this can be disabled and imo people might not find it even when looking for it unless they happen to use multiple profiles.

Oops, just noticed two more things: 
1. Another typo: *Until now, there were no rules guiding which political entities were or were not ~~be~~ included in the deck.*
2. Besides `Check Media...` and `Check Database`, maybe also recommend running `Clear Unused Tags` in the `Notes` menu of the `Browse` window? This makes sure *UG::North+Central_America* and also *UG::America* go away.

Everything else looks great!

**Comment by axelboc** [comment]
Alright, let's do this. Thanks all for your feedback! 🎉

**Comment by axelboc** [comment]
Hmm I edited the pre-release to turn off the "pre-release" checkbox, and then saved it. Did you get a release notification? If not I may have to create a new, separate release and delete this one...

**Comment by aplaice** [comment]
> Did you get a release notification?

No (only the one two days ago for v4.0-beta).

**Comment by axelboc** [comment]
How about now? I deleted the v4.0 tag, which turned the release back into a draft, and I was then able to publish it again.

**Comment by aplaice** [comment]
Still no new release notifications. 😞

**Comment by ukanuk** [comment]
I think you want to create a brand-new release. For example look at https://github.com/microsoft/terminal/releases, which has multiple pre-releases followed by a regular release, and so on. Once you've made the new release, if you think the pre-release is excessive clutter then you could edit the description to be blank, or delete it entirely. https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

Note, I've never actually done any of this myself so take it with a grain of salt... 
Personally I don't see any problem with leaving pre-releases just like the Terminal project does. Although I suppose in this case it's a little strange as I don't think any of the release files actually changed.

**Comment by ukanuk** [comment]
Oh, looks like you already did this.... Weird that I still didn't get a notification for the new release though.

**Comment by ohare93** [comment]
>So, add a new Step 0 to check CrowdAnki config and ensure there is NO CHECKMARK on the setting "Do Not Move Existing Cards", and then re-start Anki to ensure the setting takes effect.

No need to restart :smile: 

>Had you enabled the setting yourself, or was it the default? If it was the default, I can't decide whether it's a good thing or a bad thing thinking smile

As Aplaice already commented it is not the default, though I hope to convince Stvad *to make it the default*. @axelboc you even expressed the same question of "Would anyone even want to change it back?" [in this thread](https://github.com/axelboc/anki-ultimate-geography/issues/175#issuecomment-554963204). Would people be against this change now? I hope you agree this is a rather unique import setup here :sweat_smile: as a norm people would want DoNotMove, I believe.

**Comment by ohare93** [comment]
Oh and fyi, I subscribe to the RSS for this repo and I got another update 9 hours ago :+1: ontop of the prerelease one from 2 days ago. No extra notification in Github itself though :thinking:

**Comment by axelboc** [comment]
@ohare93 I removed the mention of restarting Anki, and yeah you're right, this use case is the exception for the "DoNoMove" setting.

I was hoping not to have to re-upload all the ZIP files... 😄 Oh well, I tried again from scratch. I hope it works this time. 😓

**Comment by aplaice** [comment]
It worked!
