### ISSUE TITLE
[RFC] Mention and show flags whose reverse differs from the obverse

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#347]
There are apparently countries whose flags' obverse and reverse are different:

https://en.wikipedia.org/wiki/Flags_whose_reverse_differs_from_the_obverse

Normally, the obverse and reverse are mirror images of each other, since flags are usually made ["through and through"](https://en.wikipedia.org/wiki/Through_and_through) for convenience. 

(AFAICT the obverse is the side such that when the flag is hoisted on a flagpole, the flagpole is to the left of the flag.)

(For completeness: for a couple of flags, that contain emblems or writing which shouldn't be mirrored, the reverse is exactly the same as the obverse (i.e. not the mirror image) — for example [Saudi Arabia's](https://en.wikipedia.org/wiki/Flag_of_Saudi_Arabia#Design). (The first linked Wikipedia article also mentions Brazil's flag, but I haven't been able to find any independent corroboration of that.) For some flags having emblems, however, the reverse *is* mirrored (e.g. Mexico's (see [here](https://en.wikipedia.org/wiki/Flag_of_Mexico#History) and [more specifically here](https://www.crwflags.com/fotw/flags/mx.html#reve)) where the eagle will always look towards the flagpole). IMO these subtleties are only mildly interesting and we shouldn't include them — I've only mentioned them for completeness.)

For a very few flags, however, the reverse is neither the same as the obverse, nor the mirror image of the obverse. 

That definitely is the case for Paraguay ([Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Paraguay), [Britannica](https://www.britannica.com/topic/flag-of-Paraguay)). Obverse:

![obverse](https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/800px-Flag_of_Paraguay.svg.png)

Reverse:

![reverse](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_Paraguay_%28reverse%29.svg/800px-Flag_of_Paraguay_%28reverse%29.svg.png)

It might also be the case for Transnistria. I haven't been able to find much supporting information other than  [here](https://fotw.info/flags/md-dnies.html), which isn't necessarily very trustworthy. However, it seems that the flag of the USSR (which is the basis of Transnistria's) *was* officially intended to [have differing reverse and obverse](https://en.wikipedia.org/wiki/Flag_of_the_Soviet_Union#Symbolism_and_design), so it is likely that that is indeed also the case for Transnistria's, like Wikipedia and FOTW claim. Also, the only real-world image of the reverse of the flag of Transnistria that I found does indeed lack the hammer-sickle-and-star.

*If* we were to include the information about cases where the reverse is not any trivial transformation of the obverse, (I'm not convinced we should) then AFAICT we could either:

1. Have both images (of the reverse and obverse), as well as some explanation, included in the `Flag` field.

    - This would work well for the Country → Flag cards, but it might not be the best for the Flag → Country (people would start associating "Two flags with explanatory text", and not the actual design of the flag, with Paraguay).
    
    - It would also require making the `Flag` field localisable, which would be a huge shame and a bit silly.

2. Create a new field (~ `Flag info`) which would, in the case of Paraguay (and possibly Transnistria), contain a brief explanation of the reverse ≠ obverse, as well as the image of the reverse. (The `Flag` field would be unchanged.)

    - Obviously adding a new field is a gigantic overkill for just two countries.
    
    - OTOH the "flag info" field could also, in principle, contain "interesting information" for other flags.

    - Also obviously, though, "interesting information" is pretty subjective and hence as discussed in other issues not the best fit for this deck.

    - It might work best as an "extension" of the core deck (as has been discussed elsewhere)...
    

<hr/>

I accidentally found out about the peculiarity in the case of Paraguay and decided to investigate...

**Comment by axelboc** [comment]
Quite interesting! It would never have crossed my mind.

A third option would be to do something similar to blurred flags (e.g. show one on the front and two on the back). That being said, it definitely is a niche piece of knowledge that I don't think is worth considering for the core deck. Perhaps an extension, indeed.
