### ISSUE TITLE
Python port of anki-dm

### ISSUE THREAD

**Issue by gitonthescene** [axelboc/anki-ultimate-geography#352]
FWIW, I've written a [Python port](https://github.com/gitonthescene/ankidmpy) of anki-dm.  Anki-dm hasn't changed much in a couple of years, but CrowdAnki seems pretty active.  I thought it safest to have a version of anki-dm written in a [more popular language](https://www.cleveroad.com/blog/programming-languages-ranking) in case edits become necessary.

The only minor change in functionality is that it looks for a `deck.json` when importing in addition to a *deckname*`.json`.  This was bugging me because the file that CrowdAnki exports is named `deck.json`.

**Comment by gitonthescene** [comment]
I've managed to get this [installed on PyPI[(https://pypi.org/project/ankidmpy/) to make it easy to find with pip.

```sh
$ pip install ankidmpy     
Collecting ankidmpy
  Downloading ankidmpy-0.1.0-py3-none-any.whl (13 kB)
Installing collected packages: ankidmpy
Successfully installed ankidmpy-0.1.0
$ python -m ankidmpy --help
usage: anki-dm [-h] [--base BASE] [--templates]
               {init,import,build,copy,index} ...

This tool disassembles CrowdAnki decks into collections of files and
directories which are easy to maintain. It then allows you to can create
variants of your deck via combining fields, templates and data that you really
need. You can also use this tool to create translations of your deck by
creating localized columns in data files.

positional arguments:
  {init,import,build,copy,index}
    init                Create a new deck from a template.
    import              Import a CrowdAnki deck to Anki-dm format
    build               Build Anki-dm deck into CrowdAnki format
    copy                Make reindexed copy of Anki-dm deck.
    index               Set guids for rows missing them.

optional arguments:
  -h, --help            show this help message and exit
  --base BASE           Path to the deck set directory. [Default: src]
  --templates           List all available templates.
$
```

**Comment by axelboc** [comment]
Great work! I don't think we'll be moving to it, though, because we're already planning on moving to [Brain Brew](https://github.com/ohare93/brain-brew/), once it's ready. (It's also written in Python.) 😓 I'm sure your port will benefit other decks, though, since Anki DM did do a very good job for us for a very long time.
