### ISSUE TITLE
Chinese Seas

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#355]
[The South China Sea](https://en.wikipedia.org/wiki/South_China_Sea) is in the deck, but not [the East China Sea](https://en.wikipedia.org/wiki/East_China_Sea)? :thinking: I believe both should be included. 

![image](https://user-images.githubusercontent.com/1471350/89813600-38790080-db42-11ea-8599-10739170d5f3.png)

Perhaps also the [Taiwan Straight](https://en.wikipedia.org/wiki/Taiwan_Strait), which separates the two? Though, being China, there is some dispute there:

`The strait is currently part of the South China Sea and connects to the East China Sea to the north`

**Comment by aplaice** [comment]
I fully agree that the East China Sea should be added and lean towards also adding the Taiwan Strait.

FWIW I have ready maps for both (when creating the sea maps I had made some "extras", just in case):

![ug-map-east_china_sea](https://user-images.githubusercontent.com/16461345/89833662-b6003900-db61-11ea-95e8-6bccacf9fc96.png)

![ug-map-taiwan_strait](https://user-images.githubusercontent.com/16461345/89833704-c9130900-db61-11ea-8f11-f98a974a194d.png)

(adjusting the zoom etc. would be easy, if necessary).

<hr/>

However, I think that ideally, we should figure out #346 first. (For instance, why would we be adding the East China Sea, but not the [Java Sea](https://en.wikipedia.org/wiki/Java_Sea), the [Banda Sea](https://en.wikipedia.org/wiki/Banda_Sea) or the [Barents Sea](https://en.wikipedia.org/wiki/Barents_Sea)? My gut feeling is that Java Sea and Banda Sea should also probably be added, while the Barents not necessarily. This feeling is to some extent backed by a not-completely-arbitrary-but-still-subjective criterion (the Chinese and Indonesian seas are near densely populated areas, which makes them more interesting), but even if this criterion were accepted, we'd need to make it more rigorous....)

**Comment by ohare93** [comment]
One step ahead as always @aplaice! :+1: I agree fully with your analysis.

**Comment by axelboc** [comment]
I'll close this one so to focus discussions in #346.

One step ahead indeed, @aplaice! The maps look awesome. I look forward to moving forward with #346. Not sure when I'll find the motivation, though. If one of you feels like having a crack, feel free 😄 (If/when I decide to get started on it, I'll assign myself to it.)
