### ISSUE TITLE
Add ISO 3166 alpha-2 country codes

### ISSUE THREAD

**Issue by PolymathArtisan** [axelboc/anki-ultimate-geography#359]
I think it would be cool to add country-codes to the deck. They're a useful country-reference thing, and they're pretty widely used. 

There are [many different kinds](https://en.wikipedia.org/wiki/Comparison_of_alphabetic_country_codes). I think that ISO 3166 alpha-2 are the way to go because:
- the scheme is comprehensive, covering all sovereign states
- The codes are alphabetic, non-arbitrarily reflecting the names of the countries they represent. This is easier to remember than some of the other schemes (e.g. ISO 3166 numerica, which just uses numbers)

This issue is mostly to gauge interest for the public deck. *I* will definetly make a versoin of the deck for myself with country codes, but if there is any interest at all, then I'd be happy to push it back here. 

If so, what card types would be appropriate? Presumably name -> code (perhaps as a type-in? I find that quie useful for short codes and similar information, especially as anki can point out individual letters you got wrong in the answer). Flag -> code and code -> flag maybe? Or maps? I'm not sure. 

All thoughts appreciated. Thanks!

*(Sorry if I'm approaching this wrong or something, this is my first time doing something like this through github.)*

**Comment by axelboc** [comment]
Thanks @PolymathArtisan, I don't think this would go in the core Ultimate Geography, but it could definitely live as an extension in its own repository once [the ecosystem supports it](https://github.com/ohare93/brain-brew/issues/4).

**Comment by axelboc** [comment]
Closing for now, but I'll leave the tag on so we can find it again when the ecosystem is ready. See https://github.com/axelboc/anki-ultimate-geography/issues/362 for more info.
