### ISSUE TITLE
Flag of Northern Ireland

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#360]
Just noticed we have a flag for Scotland, England and Wales, but not for _Northern Ireland_!

**Comment by ohare93** [comment]
Was going to raise this one myself, as I saw it earlier today :sweat_smile: strange how it got past, especially since I've been comparing it to the Ivory Coast in my head :sweat_smile:

**Comment by aplaice** [comment]
Apparently, [according to Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Northern_Ireland), Northern Ireland currently does not have an official flag of its own, and it's apparently a [controversial issue](https://en.wikipedia.org/wiki/Northern_Ireland_flags_issue).

<details><summary>Background, in case of interest</summary>

The [Ulster Banner](https://en.wikipedia.org/wiki/Ulster_Banner) was the official flag between ~ 1953 and 1972, and is still occasionally used by Unionists:

![Ulster Banner](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Ulster_Banner.svg/600px-Ulster_Banner.svg.png)

There's also [Saint Patrick's Saltire](https://en.wikipedia.org/wiki/Saint_Patrick%27s_Saltire), which is the "Irish addition" to the Union Jack (and which I had thought was the actual flag of NI...), but it doesn't have any official status either:

![Saint Patrick's Saltire](https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Saint_Patrick's_Saltire.svg/600px-Saint_Patrick's_Saltire.svg.png).

</details>

Hence, I don't think we should add a flag.

<hr/>

BTW I'm really thrilled about the new Brain-Brew release and the AUG conversion — I'll have a (belated) look asap!
