### ISSUE TITLE
Discussions Tab

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#367]
Can you enable the new Github Discussions tab?

![image](https://user-images.githubusercontent.com/1471350/102601125-085cf200-4120-11eb-9dec-8a66df6470e4.png)

Some things feel like they do not belong as an Issue, but still merit a question to others 😄

**Comment by axelboc** [comment]
Done! Sorry I haven't had time to catch up with your latest work on #364. Will take a look asap 😉

**Comment by ohare93** [comment]
> Done! Sorry I haven't had time to catch up with your latest work on #364. Will take a look asap 😉

No problem mate, take your time 👍 I wanted it to post a meme, lol.
