### ISSUE TITLE
Antartica continent is missing

### ISSUE THREAD

**Issue by totsubo** [axelboc/anki-ultimate-geography#38]
I downloaded the new continent cards but looks like Antartica is missing?

**Comment by axelboc** [comment]
Ha, so it is! Sorry about that 😞

**Comment by axelboc** [comment]
Not sure when I'll work on the deck next, so here is the map in case you don't want to wait for the next release:

![ug-map-antartica](https://user-images.githubusercontent.com/2936402/33126233-e3584304-cfd7-11e7-931c-e6cb8d430d98.png)
