### ISSUE TITLE
Use of full stops at the ends of descriptive fields

### ISSUE THREAD

**Issue by aplaice** [axelboc/anki-ultimate-geography#383]
We currently have a cross-language, unofficial convention that the `capital_info` and `country_info` fields end in full stops, while the `capital_hint` and `flag_similarity` ones don't.

I assume that it's because the former group at least sometimes contains full sentences, while the latter are always phrases.

However, most of the `country info`s are also simple phrases (e.g. `Constituent country of X`, `Island of X` or `Also known as X` (AFAIK, in English, if my grammar knowledge is correct, past participles don't count as verbs for the purpose of determining what is a sentence or clause)). The only "country info" that is actually a sentence that I could find, at least in English, was for the Sea of Japan. In contrast, almost all of the `capital info`s are sentences (e.g. `Cetinje is an honorary capital.`). Hence:

1. Should we revise the (currently unofficial) convention? 

    For instance, change the rule such that all phrases do not end in a full stop, and all sentences do, irrespective of which field they're in. In practice, that'd result in most of the `country info`s and a couple `capital info`s losing their trailing full stops. However, would that not look ugly/inconsistent (even if it'd be "grammatically correct")?

2. Should we document the conventions in `CONTRIBUTING.md`?

3. Are the rules about what constitutes a complete sentence different in different languages? (For example, there are some languages where "to be" can be omitted and only be "implicitly" present. (Approximately, "This table." means "This is a table.").) Hence, would that affect the dividing line between phrases and sentences, for that language?

<hr/>

(Spun out from #382.) (Hmm, I automatically added a full stop, despite it not being a sentence...)

<hr/>

This is obviously extraordinarily minor, but getting such stylistic issues right (and consistent) makes the deck slightly nicer to use!

**Comment by emiham** [comment]
>For instance, change the rule such that all phrases do not end in a full stop, and all sentences do, irrespective of which field they're in. In practice, that'd result in most of the country infos and a couple capital infos losing their trailing full stops. However, would that not look ugly/inconsistent (even if it'd be "grammatically correct")?

It does give an inconsistent look to the cards, but if the idea is that it's important for sentences to be followed by a full stop it's at least internally consistent.  One way this could be addressed is by requiring every hint to be a full sentence, e.g. we'd change `Constituent country of X` to `Y is a constituent country of X.`, but that makes it a lot wordier than it needs to be. This might also make more sense for info fields that have multiple "phrases" or sentences.

Personally I think that not having any full stops in any fields would be best. Functionally they serve no purpose, since the fields are separated in other ways. The sentences also don't make much sense without the context of the main field, so if following grammatical rules is the goal I think that would have to apply to all fields. As long as there's only one sentence in each field I think it's best to consider it as a "phrase" that just happens to parse as a full sentence. 

It's also worth considering that if there are no full stops in fields they can be added on the card template, but you can't remove them (easily). 

>Should we document the conventions in `CONTRIBUTING.md`?

I think so. Clarity is important when we consider the fact that every new translation is done by someone who is completely new to the project, making the barrier of entry low seems worthwhile. 

>Are the rules about what constitutes a complete sentence different in different languages? (For example, there are some languages where "to be" can be omitted and only be "implicitly" present. (Approximately, "This table." means "This is a table.").) Hence, would that affect the dividing line between phrases and sentences, for that language?

Another thing about other languages is that a full stop might look different. I only know of Japanese off the top of my head, but a `。` takes up a lot more space (on the card and in the mind) than a simple `.`, both because of its shape and the fact that it has a lot of blank space to be considered full width, which in the worst case scenario this could cause an undesired line break.

**Comment by aplaice** [comment]
Thanks for the reply!

>  One way this could be addressed is by requiring every hint to be a full sentence, e.g. we'd change Constituent country of X to Y is a constituent country of X., but that makes it a lot wordier than it needs to be.

Yeah, I agree that that'd be unnecessarily wordy.

> As long as there's only one sentence in each field

Unfortunately, that's not the case (see `grep -r '\. ' src/data/` — there are quite a few cases), so I don't think that removing all trailing full stops is feasible.

> It's also worth considering that if there are no full stops in fields they can be added on the card template, but you can't remove them (easily).

True! :)

> Another thing about other languages is that a full stop might look different. I only know of Japanese off the top of my head, but a 。 takes up a lot more space (on the card and in the mind) than a simple ., both because of its shape and the fact that it has a lot of blank space to be considered full width, which in the worst case scenario this could cause an undesired line break.

Yeah, if we ever end up including Japanese, then depending on what we decide here, we might need to apply a slightly different set of rules for Japanese.

<hr/>

On second thoughts, I don't think that there's anything wrong with having a final full stop even for phrases, especially since it helps in situations where there are multiple phrases (e.g. `Autonome Region Finnlands. Auch Ålandinseln.`). Obviously, as you note, we could rewrite them as full sentences, but that makes them even longer.

**Comment by axelboc** [comment]
I quite like that fields that may include sentences always include full stops. (I came up with this unspoken rule, so I guess it makes sense that I like it 😄)

Seriously, though, I feel like it makes it easy to not forget a full stop when a full sentence comes along. It also helps differentiate (a tiny little bit) "informative" fields from "practical" fields (i.e. hints and flag similarities for memorization), both of which look the same CSS-wise.

Granted, these two arguments don't bring much weight to the debate ... 😂 so I'd be fine with phrases not having full stops throughout as well.

**Comment by axelboc** [comment]
I haven't found a source that treats of our exact use case, but it does seem that phrases should not to end with full stops in French. I don't believe it's a problem if they do, though. 🤷

**Comment by aplaice** [comment]
> I quite like that fields that may include sentences always include full stops. (I came up with this unspoken rule, so I guess it makes sense that I like it smile)

Yeah, we may as well stick with it! :) The rule works (in the sense that applying it never seems to result in a clearly terrible outcome, even in edge cases, like multiple phrases in a single field), and overly debating this feels crazy (I started the discussion, so I'm allowed to write this! :)).

I"ll try to very briefly summarise the existing convention in `CONTRIBUTING.md`, this week! (I hope that I'll have time...)

**Comment by aplaice** [comment]
> I haven't found a source that treats of our exact use case, but it does seem that some phrases are not supposed to end with full stops in French (like slogans). I don't believe it's a problem if they do, though. shrug

But if writers etc. are allowed to write "phrases" ([like `Pour embellir sa pelouse. Sans détruire l’environnement.`](https://www.btb.termiumplus.gc.ca/redac-chap?lang=fra&lettr=chapsect6&info0=6.3#zz6)) separated with full stops, to add ~ emphasis, then it can't be that horrible grammatically. This "use-case" is obviously different than ours, but arguably closer than slogans.

**Comment by emiham** [comment]
> I"ll try to very briefly summarise the existing convention in CONTRIBUTING.md, this week! (I hope that I'll have time...)

I'll look over the Swedish translation and add them once this is done, just to make sure nothing needs to be adjusted in any other way to look better with a full stop. 

> Yeah, if we ever end up including Japanese, then depending on what we decide here, we might need to apply a slightly different set of rules for Japanese.

I've toyed with the idea of doing this translation sometime in the future (I speak Japanese), but that would have to wait at least until I've gotten through the deck in Swedish which will probably take me a while. Japanese does have zero copula, and in all cases I can think about right now it would either clearly not be a full sentence or be ambiguous, so I think there's a stronger argument for omitting it there. The only issue we'd have to consider would be multiple "phrases"/sentences. 

This can probably be dealt with in a future _Japanese translation_ issue if/when that becomes relevant.

**Comment by aplaice** [comment]
> I'll look over the Swedish translation and add them once this is done, just to make sure nothing needs to be adjusted in any other way to look better with a full stop.

Thanks!

> I've toyed with the idea of doing this translation sometime in the future (I speak Japanese)

That'd be amazing, but obviously no pressure!

> This can probably be dealt with in a future Japanese translation issue if/when that becomes relevant.

Yeah, definitely!

**Comment by aplaice** [comment]
Justifications moved from the draft of `CONTRIBUTING.md`, to avoid cluttering it up.

We use a full stop at the end of the _Capital info_ and _Country info_ fields and no full stop for the _Capital hint_ and _Flag similarity_ fields because:

1. The former two fields contain sentences (as opposed to phrases) relatively frequently, while the latter two almost never (exceptions include `(No) es un país soberano`). For consistency, and to avoid missing full stops when they are grammatically needed, it's useful for all the fields of the same type to use the same convention.
2. It helps visually differentiate the former two "informative" fields, from the latter two "practical" ones.
3. The former two fields, unlike the latter two, sometimes contain multiple sentences or multiple phrases (e.g. `Auch Nur-Sultan. Früher Astana.`), which need to be delimited with full stops, so always ending these sentences and phrases with a full stop makes sense.

**1** and **2** are as described by @axelboc [above](https://github.com/axelboc/anki-ultimate-geography/issues/383#issuecomment-770441986), **3** is a new one.
