### ISSUE TITLE
Have upgrade instructions change now that we're not on CrowdAnki?

### ISSUE THREAD

**Issue by gitonthescene** [axelboc/anki-ultimate-geography#393]
The change to Brain Brew is a minor upgrade, but the instructions for a minor upgrade refer to CrowdAnki.  Does this still work?  It would probably help to make this explicit.

**Comment by ohare93** [comment]
We have not switched away from CrowdAnki, it is still used to import the deck into Anki :sweat_smile: 

Brain Brew is a replacement for Anki Deck Manager, which converted csvs into CrowdAnki json. Brain Brew still does that, as well as converts the opposite way (from CrowdAnki to source), in a more versatile way :+1:

**Comment by gitonthescene** [comment]
Thanks.  It might be nice for people like me to add a line to the release notes saying "Nothing in the release process has changed", though I did run into [an issue](https://github.com/Stvad/CrowdAnki/issues/120) with the latest Anki release.

**Comment by axelboc** [comment]
I see how this could have been confusing. I've added a sentence in the release notes. Thanks!
