### ISSUE TITLE
How to download a certain language? 

### ISSUE THREAD

**Issue by Fernti** [axelboc/anki-ultimate-geography#405]
I don't get it

**Comment by ohare93** [comment]
Did you read the [Getting Started section of the ReadMe](https://github.com/axelboc/anki-ultimate-geography#getting-started)? 👍 

Basically boils down to:
1. Install CrowdAnki (then restart)
1. Download the right language file
1. Import it with CrowdAnki

**Comment by Fernti** [comment]
After some installing issues it worked out! Thank you

**Comment by aplaice** [comment]
Would you suggest anything to make the instructions clearer or to avoid the installing issues?  (If there is please don't hesitate to tell us, but if not, that's also fine!)
