### ISSUE TITLE
Indonesia and Monaco flags are inaccurate

### ISSUE THREAD

**Issue by siriak** [axelboc/anki-ultimate-geography#410]
Steps to reproduce:
1. Compare colors of red on flags of Indonesia and Monaco in the deck with a color picker (like gpick).
2. Google for flags of Indonesia and Monaco and compare colors to those in the deck.

Expected result:
1. Red colors are different from one another and they are the same as in Google.
2. Value in the "Flag similarity" field corresponds to what's shown on the card.

Actual result:
1. Flags have the same red color.
2. Value in the "Flag similarity" field says that Indonesia has brighter red than Monaco, but colors are exactly the same on pictures.

Google Indonesia:
![image](https://user-images.githubusercontent.com/29201949/114021539-79fcaf80-9879-11eb-8345-a4011ff2d034.png)
Google Monaco:
![image](https://user-images.githubusercontent.com/29201949/114021617-8e40ac80-9879-11eb-9f24-ba54a6eea03d.png)

Ultimate Geography Indonesia:
![image](https://user-images.githubusercontent.com/29201949/114021755-b7f9d380-9879-11eb-87a8-6bf1cc6962dc.png)
Ultimate Geography Monaco:
![image](https://user-images.githubusercontent.com/29201949/114021855-d1028480-9879-11eb-9a36-4c23a7a681e2.png)

**Comment by ohare93** [comment]
Huh, so they are... :eyes:

**Comment by aplaice** [comment]
We were/are apparently using the [Indonesia flag from 2015](https://commons.wikimedia.org/wiki/File:Flag_of_Indonesia.svg) in `media` which is `#CE1126` (like Monaco), but using the updated version (2017, 2020), which is `#F00`/`red`, for determining flag similarity.

**Comment by axelboc** [comment]
Well spotted! 🎣 We should definitely update the Indonesian flag.

Just to clarify, though:

- Our flags are always sourced from Wikipedia/Wikimedia.
- Google does not (always) display the flag from Wikipedia in its infobox, which partly explains the differences.
