### ISSUE TITLE
German translation fixes

### ISSUE THREAD

**Issue by ghost** [axelboc/anki-ultimate-geography#483]
In the capital_info.csv for Burkina Faso there is a missing "dot". Minor detail but should be added for consistency with all other entries.

`Burkina Faso,,Auch Wagadugu,,,,,,,`

should be:

`Burkina Faso,,Auch Wagadugu.,,,,,,,`

In the country_info.csv for New Caledonia there is a grammatical error (a missing "s").

`New Caledonia,Overseas territory of France.,Französische Überseegebiet.,Territorio de ultramar de Francia.,Territoire français d'outre-mer.,Fransk oversjøisk territorium i det sørvestlige Stillehavet.,Zámořské území Francie.,Заморская территория Франции.,Overzees land van Frankrijk.,Franskt utomeuropeiskt territorium.`

should be:

`New Caledonia,Overseas territory of France.,Französisches Überseegebiet.,Territorio de ultramar de Francia.,Territoire français d'outre-mer.,Fransk oversjøisk territorium i det sørvestlige Stillehavet.,Zámořské území Francie.,Заморская территория Франции.,Overzees land van Frankrijk.,Franskt utomeuropeiskt territorium.`

**Comment by axelboc** [comment]
Well spotted! Would you like to open a PR?
