### ISSUE TITLE
Add more flag similarity info

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#50]
From a comment on the [shared deck's page](https://ankiweb.net/shared/info/2109889812):

> [...] Countries with similar flags were a lot of trouble (ex. New Zealand/Australia, Curaçao/Nauru, Palestine/Sudan, Andorra/Moldova), [...]

**Comment by ohare93** [comment]
There are still some flag similarities missing.

Iraq, Egypt, Yemen, and Syria, for instance.

If I recall more I shall comment them in this thread.

**Comment by axelboc** [comment]
Nice one, thanks! I've added flag similarities for Iraq, Egypt, Yemen and Syria in #88. Do you find them clear enough?

**Comment by ohare93** [comment]
> Nice one, thanks! I've added flag similarities for Iraq, Egypt, Yemen and Syria in #88. Do you find them clear enough?

Yes those descriptions are clear 👍 

Looking through my notes and quickly glancing through all the flags, here are all the flag similarities I believe are missing:

1. Iceland's flag is similar to Norway's, but Norway's is not similar to Iceland's
2. Palestine's flag is similar to both Jordan's and Sudan's, but those two are not similar to each other's flag. Kuwait is potentially similar to them all too.
3. Hungary, Luxembourg, Netherlands, Tajikistan
4. Italy and France
5. Guinea-Bissau and Benin
6. Romania and Chad are already similar, and Andorra and Moldova are similar, but they should all be similar to each other.
7. Northern Cyprus and Turkey

These last three are a bit of a stretch, but they have tripped me up before:
1. Papa New Guinea and Christmas Island
2. Montenegro and Mt Athos (at a push Serbia too?)
3. Isle of Man and Sicily

Also all those flags in Scandinavia are somewhat similar (Norway, Iceland, Finland, Sweden, Denmark, Faroe Islands, Åland Islands). Though I don't know how you would go about differentiating them in a useful way 🤔

**Comment by ohare93** [comment]
As a side issue, I have found that some of the existing similarities do not help at all due to their wording.

Such as Thailand and Costa Rica simply stating the other country with "(blue and red inverted)". Clearer wording like of "(Red outside stripes, blue inside stripe)" and "(Blue outside stripes, red inside stripe)" may help to differentiate them in memory. 

Same goes to the flag descriptions for: Cuba and Puerto Rico; Poland and Indonesia; Ireland and Côte d'Ivoire; Guina and Mali;

**Comment by ohare93** [comment]
I'll update the still undone flag similarities I pointed out and make a PR this weekend.

Let me know if there are any others to do, and I'll cover them too 👍

**Comment by ohare93** [comment]
I have made most of the changes I listed above (man, some are just hard to word or decide if it's even necessary!) in my fork 👍 but I cannot seem to make another pull while my current one is open. Perhaps putting it in it's own branch would fix that, but I'm not sure.

**Comment by axelboc** [comment]
Ah right, you've committed directly to your fork's `master` branch and your cloze templates PR is for this same branch. The flag similarities now [appear in your PR](https://github.com/axelboc/anki-ultimate-geography/pull/118/commits) as a result.

To save you a headache, I've copied your changes into a new branch in this repo and opened a PR.

**Comment by axelboc** [comment]
To answer your side question, I'm editing `data.csv` in a code editor at the moment. It's far from ideal, but it does the trick. If anyone knows of a tool than works better than Excel, I'm all ears! 👂

**Comment by ohare93** [comment]
> Ah right, you've committed directly to your fork's `master` branch and your cloze templates PR is for this same branch. The flag similarities now [appear in your PR](https://github.com/axelboc/anki-ultimate-geography/pull/118/commits) as a result.
> 
> To save you a headache, I've copied your changes into a new branch in this repo and opened a PR.

Ahh damn, yes my mistake I forgot to make a branch for the original change! Thanks for going to the trouble 💯 👍

**Comment by ohare93** [comment]
> To answer your side question, I'm editing `data.csv` in a code editor at the moment. It's far from ideal, but it does the trick. If anyone knows of a tool than works better than Excel, I'm all ears! 👂

Yes it is incredibly tedious to double and triple check everything. Is there any particular reason why you don't just let all fields be encapsulated in quotes? Everything should render the same in the end, right? Then this would allow the use of Excel, or the like.

**Comment by axelboc** [comment]
Very true. Though I feel like I've seen a case where the quotes were removed because they were not needed. Of course now I can't remember when that happened and what I was doing...

**Comment by ohare93** [comment]
"Not needed" may be true, but as long as they export to the exact same flashcards in the end then they have use, in that they allow us to use a more sophisticated csv editor.

I'll save my own document in Excel, which will add quotes everywhere, then save it, and rebuild the deck. I'll let you know if it seems to be fine.

**Comment by aplaice** [comment]
> Yes it is incredibly tedious to double and triple check everything. Is there any particular reason why you don't just let all fields be encapsulated in quotes?

I agree that some sort of standardisation would be great! :)

For comparison, Libreoffice by default only wraps in quotes (`"`) the cells/fields that contain a literal comma (`,`), probably because that's the only case where they're necessary to prevent ambiguity. It is also possible to change the export so that all fields are wrapped in quotes (`File > Save As; Check "Edit Filter Settings" and select "Text CSV" format; Save; Check "Quote all text cells"` for future reference). However, just like for @ohare93 for Excel, I can't find an option to reproduce the current apparent convention used for `data.csv` of encapsulating fields in quotes iff they contain spaces OR quotes. (Hence, I just used an editor.)

Google docs has the same default as Libreoffice (wrapping with quotes iff a field contains a comma). It's probably also possible to export with all fields wrapped in quotes, though I can't find the option at first glance.

**Comment by ohare93** [comment]
@aplaice Hmm, very strange. Also, what program do you generally use?


Anyways, be it LibreOffice or a random VS Code extension it's very easy for all to get a program with "Quote all fields" option for free.

![image](https://user-images.githubusercontent.com/1471350/63103896-41121780-bf7e-11e9-8444-9e360ab57c70.png)

![image](https://user-images.githubusercontent.com/1471350/63103940-52f3ba80-bf7e-11e9-806e-2d56c891a036.png)

I think all that is left is to work out if there is any detriment to having this be the case. I have just made a rebuild of the deck with this set, and everything appears to be the same 😁 Is there any

###### Apologies for getting out of the original issue haha

**Comment by ohare93** [comment]
Aha, it's AnkiDM which is adding in quotes only in some parts! I can do a build with all quotes and it all works fine, but after a quick `composer index` the quotes go back to how they were before. 

So this is only good news! It would be good to know why AnkiDM does that (but haven't looked into it), but it's fine because this means anyone can safely edit the data file in excel/libreoffice/etc and save it with any type of quotes, as long as they run `composer index` before syncing 👍

**Comment by aplaice** [comment]
> @aplaice Hmm, very strange. Also, what program do you generally use?

Once I realised that Libreoffice gave spurious "changes" (I wish that I had realised that `composer index` would have got rid of them), I just edited the CSV as plain text, which in many ways was easier than doing it in a tabulated form (I double-checked to make sure that I had edited the correct columns, but I'd have done that anyway).

**Comment by aplaice** [comment]
On-topic, some further similarities are:

### [Ghana](https://en.wikipedia.org/wiki/Flag_of_Ghana) and [Bolivia](https://en.wikipedia.org/wiki/Flag_of_Bolivia)

(Would it make sense to describe them as:

```
(For Ghana's flag) Bolivia (coat of arms instead of star)

(For Bolivia's flag) Ghana (star instead of coat of arms)
```

?)

### [Paraguay](https://en.wikipedia.org/wiki/Flag_of_Paraguay), [Netherlands](https://en.wikipedia.org/wiki/Flag_of_the_Netherlands) and [Luxembourg](https://en.wikipedia.org/wiki/Flag_of_Luxembourg):

(I'm not sure about the relative brightness of Paraguay's and the Netherland's blue...)

```
(For Paraguay's flag) Netherlands (no coat of arms), Luxembourg (no coat of arms, lighter red and blue)

(For Netherlands) Paraguay (with coat of arms)

(For Luxembourg) Paraguay (with coat of arms)

**Comment by ohare93** [comment]
@aplaice Good shout! And yes, those descriptions sound good to me.

---

Here are some further similarities:

# Liberia
![image](https://user-images.githubusercontent.com/1471350/63182660-586f0480-c053-11e9-819d-7ddfe27b89cd.png)

# Malaysia
![image](https://user-images.githubusercontent.com/1471350/63182670-5c9b2200-c053-11e9-9afa-1ad2a1e11d63.png)


### Suggested wordings
```
(For Liberia)
Malaysia (yellow moon and star, larger box)

(For Malaysia)
Liberia (white star, smaller box)
```

Is there a better term for that part of a flag than "box"? I am unaware of the technical descriptive terms for parts of a flag 😅 




---




# All the flags of Scandinavia

![image](https://user-images.githubusercontent.com/1471350/63183662-d3391f00-c055-11e9-9b30-dd9ec0c88d98.png)

\+ Åland Islands
![image](https://user-images.githubusercontent.com/1471350/63183692-ea780c80-c055-11e9-85f1-b3efe509622f.png)

I truly believe these flags are similar enough to warrant their own Flag Similarities. However how to do that...? 😰 There are not enough similarities between them *all* for a general statement, but then working out which are close enough to link together becomes a challenge. Here are just some general observations from looking at them all:

 - There seems to be two groups. Perhaps this is what we could break them down into?
    - Single crosses (Denmark, Sweden, and Finland)
    - Double crosses (Norway, Iceland, Faroe Islands, and Åland Islands).
 - Iceland and Norway are inverted versions of each other.

---

Some brainstorming on these Scandinavian flags would be much welcomed 👍

**Comment by aplaice** [comment]
> @aplaice Good shout! And yes, those descriptions sound good to me.

Great! Thanks for the feedback.

<hr/>

> Is there a better term for that part of a flag than "box"? I am unaware of the technical descriptive terms for parts of a flag sweat_smile

Looking at the design descriptions in the Wikipedia articles corresponding to the two flags ([Liberia's](https://en.wikipedia.org/wiki/Flag_of_Liberia) and [Malaysia's](https://en.wikipedia.org/wiki/Flag_of_Malaysia)), the "box" is described as a [canton](https://en.wikipedia.org/wiki/Canton_(flag)):

> Eleven horizontal stripes alternating red and white; in the canton, a white star on a blue field

> Fourteen horizontal stripes alternating red and white; in the canton, a yellow crescent and 14-point star on a blue field

AFAICT:

### Advantages of using "canton"

* (Apparently) the proper term.
* People will (eventually...) guess what "canton" is supposed to mean, and learn a new term, by diffusion (perhaps there should be cards for flag terminology :P)

### Disadvantages of using "canton"

* Almost nobody who isn't a vexillologist will understand the term, to begin with.

### Advantages of using "box"

* It's a normal, commonly used word, whose meaning vaguely fits the context.

### Disadvantages of usign "box"

* It's still not necessarily an entirely unambiguous description without having both flags in front of you.

Overall, my vote would go to "canton", perhaps with a hyperlink to the Wikipedia article (`<a href="https://en.wikipedia.org/wiki/Canton_(flag)">canton</a>`)?

<hr/>

> Some brainstorming on these Scandinavian flags would be much welcomed

Sorry, I have no idea about clear, concise and useful comparisons.

**Comment by axelboc** [comment]
I feel like we're going a bit too far with this issue, in terms of scope. Although I agree that a few useful flag similarities are currently missing, the goal of the field remains to help differentiate the flags most people keep mixing up, even with repetition.

Do you really think most people confuse, for instance, the flags of Sweden, Denmark and Finland? In my personal experience, I've never had any trouble with them, mostly because the colours and the "weights" of the crosses are so different. I'm European, so I'm probably biased, but I believe that, with repetition and a bit of effort, these flags can be memorised. If people with different backgrounds than mine keep tripping on them no matter what, then flag similarities are justified.

It's also an important part of learning to find your own ways of remembering things, whether by doing some research or by coming up with mnemonics. For instance:
- The [star and crescent](https://en.wikipedia.org/wiki/Star_and_crescent) is a well-known symbol of Islam, and can help differentiate the flags of [Malaysia](https://commons.wikimedia.org/wiki/File:Flag_of_Malaysia.svg) and [Liberia](https://commons.wikimedia.org/wiki/File:Flag_of_Liberia.svg).
- I found that the position of the red band in the flags of [Poland](https://commons.wikimedia.org/wiki/File_talk:Flag_of_Indonesia.svg) and [Indonesia](https://commons.wikimedia.org/wiki/File_talk:Flag_of_Indonesia.svg) is the opposite of the country's hemisphere: Poland is in the North hemisphere, so the red band is at the bottom.

My point is, learning flags is difficult. Mixing up a couple of them from time to time is normal. Let's make sure that the flag similarities we add are really needed and beneficial to most.

---

So, I guess my question is: do you, personally, keep on confusing any of the following pairs of flags that do not currently have flag similarities?

1. [France](https://commons.wikimedia.org/wiki/File:Flag_of_France.svg), [Italy](https://commons.wikimedia.org/wiki/File:Flag_of_Italy.svg)
1. [Tajikistan](https://commons.wikimedia.org/wiki/File:Flag_of_Tajikistan.svg), [Hungary](https://commons.wikimedia.org/wiki/File:Flag_of_Hungary.svg)
1. [Hungary](https://commons.wikimedia.org/wiki/File:Flag_of_Hungary.svg), [Netherlands](https://commons.wikimedia.org/wiki/File:Flag_of_Netherlands.svg)/[Luxembourg](https://commons.wikimedia.org/wiki/File:Flag_of_Luxembourg.svg)
1. [Tajikistan](https://commons.wikimedia.org/wiki/File:Flag_of_Tajikistan.svg), [Netherlands](https://commons.wikimedia.org/wiki/File:Flag_of_Netherlands.svg)/[Luxembourg](https://commons.wikimedia.org/wiki/File:Flag_of_Luxembourg.svg)
1. [Paraguay](https://commons.wikimedia.org/wiki/File:Flag_of_Paraguay.svg), [Netherlands](https://commons.wikimedia.org/wiki/File:Flag_of_Netherlands.svg)/[Luxembourg](https://commons.wikimedia.org/wiki/File:Flag_of_Luxembourg.svg)
1. [Norway](https://commons.wikimedia.org/wiki/File:Flag_of_Norway.svg), [Faroe Islands](https://commons.wikimedia.org/wiki/File:Flag_of_Faroe_Islands.svg)
1. [Iceland](https://commons.wikimedia.org/wiki/File:Flag_of_Iceland.svg), [Faroe Islands](https://commons.wikimedia.org/wiki/File:Flag_of_Faroe_Islands.svg)
1. [Turkey](https://commons.wikimedia.org/wiki/File:Flag_of_Turkey.svg), [Northern Cyprus](https://commons.wikimedia.org/wiki/File:Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg)
1. [Benin](https://commons.wikimedia.org/wiki/File:Flag_of_Benin.svg), [Guinea-Bissau](https://commons.wikimedia.org/wiki/File:Flag_of_Guinea-Bissau.svg)
1. [Isle of Man](https://commons.wikimedia.org/wiki/File:Flag_of_Isle_of_Man.svg), [Sicily](https://commons.wikimedia.org/wiki/File:Flag_of_Sicily.svg)
1. [Ghana](https://commons.wikimedia.org/wiki/File:Flag_of_Ghana.svg), [Bolivia](https://commons.wikimedia.org/wiki/File:Flag_of_Bolivia_(state).svg)
1. [Liberia](https://commons.wikimedia.org/wiki/File:Flag_of_Liberia.svg), [Malaysia](https://commons.wikimedia.org/wiki/File:Flag_of_Malaysia.svg)

There's already a flag similarity in the deck for Iceland and Norway, but only on the note for Iceland, not on the note for Norway... This should definitely be added.

Personally, the one that regularly trips me up is the pair **Iceland / Faroe Islands**, so I think it would be beneficial to add cross-similarities for Iceland, Norway and the Faroe Islands.

I've tripped on Sicily and Isle of Man a while back, but that's because Sicily didn't use to be in the original Ultimate Geography deck. The flag of Sicily is actually quite distinctive with its diagonal, yellow half.

I don't believe I've ever tripped on the others before, but I'm eager to hear about your own experiences.

**Comment by axelboc** [comment]
I should clarify that I'm totally on board with improving the wording of the existing flag similarities. Some of them are indeed quite useless.

**Comment by axelboc** [comment]
Also, sorry for reacting so late... When I re-opened this issue, I knew that there were still some improvements to be made, but I had not taken the time to really compare the flags [you had listed](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-486129121), @ohare93. My apologies.

**Comment by aplaice** [comment]
For some of the flag similarities, I treat them as an aide for remembering the flag by helping identify common patterns, not as a way of avoiding confusing similar flags. For instance, for the Egypt, Sudan, Syria and Yemen group, it's useful (for me) to remember that the red and the black are on the top and bottom, respectively, for the entire group as a whole.

Of the flag pairs/groups you listed, I have used the similarities to remember the ordering of the stripes for the following:

> 2. Tajikistan, Hungary
> 5. Paraguay, Netherlands/Luxembourg
> 11. Ghana, Bolivia

I haven't confused any of the pairs you listed, though. Hence, you may well be right that listing the similarities for them might be out-of-scope for the "flag similarities" field.

**Comment by axelboc** [comment]
Oh right, I get you! You're talking about the extended deck's _Country - Flag_ template, aren't you? I had never considered what role the similarities played in this case. Very interesting.

The purpose is quite different, indeed. The current similarities are meant to teach what to look for on a flag in order to differentiate it from another the next time you see it.

With the _Country - Flag_ template, it seems that what is needed is a hint as to which countries have similar flags in order to jog your memory (as chances are you already know what one of the other flags looks like). If that's the case, then perhaps we need to add a new field and display it on the front of the _Country - Flag_ template as a [hint field](https://apps.ankiweb.net/docs/manual.html#hint-fields) (so it can be revealed on demand).

**Comment by aplaice** [comment]
> You're talking about the extended deck's Country - Flag template, aren't you?

Yes.

> If that's the case, then perhaps we need to add a new field and display it on the front of the Country - Flag template as a hint field (so it can be revealed on demand).

That makes sense, though I don't currently have a great idea on how exactly to organise this. In the meantime, I'll close my over-enthusiastic similarities pull request, at least for the time being, pending (potential) re-organistion. :)

**Comment by axelboc** [comment]
Hopefully, PR #125 covers all remaining flag similarities in the context of the _Flag - Country_ template. If not, let's open new issues to discuss specific similarities.

I'll open a separate issue so we can discuss the case of the _Country - Flag_ template.

**Comment by ohare93** [comment]
Hmm, I see I have been coming at this from a more completionist view, of "anything that is similar needs to state it is so". I understand if you want a more minimal approach of "if it will help someone", I guess I just see this as a hard thing to judge who around the world will be confused by what flags depending mainly on their location. For flags like Italy/France I have never once been confused between them (also being a European), however it is undeniable that they are similar, and very possible that others around the world may be confused by it. 

>My point is, learning flags is difficult. Mixing up a couple of them from time to time is normal. Let's make sure that the flag similarities we add are really needed and beneficial to most.

I completely agree with everything you said about learning your own ways to differentiate and remember. I suppose I just never considered that _not adding a similarity was the default_ 🤔 and the flag similarities were there to help with this differentiation, not to replace it.

Anyways feel free and see all my not yet implemented flag similarity claims as being made for these reasons 😅 👍 Yes, I have gotten some of these mixed up (mostly Liberia/Malysia, Benin/Guinea-Bissau). The others have been one-off wrong answers, or simply ones I noticed were similar and noted down for the sake of it.

**Comment by axelboc** [comment]
> I just never considered that not adding a similarity was the default

Fair enough! I'd never made that clear, sorry 😅 

> I guess I just see this as a hard thing to judge who around the world will be confused by what flags 

You're totally right. Waiting to hear from people's experiences and relying on biased intuition is definitely not the best approach... Perhaps we need to identify and document a more reliable and objective list of criteria/guidelines for flag similarities?

---

If that sounds useful, here are some initial ideas for criteria that may help identify whether two or more flags are "similar-enough" to warrant having flag similarities info in this deck:

1. The flags differ in ways that can be described both **precisely** and **clearly**. If we're not sure about how to describe some of the differences without being vague or without using advanced vexillological terms, it's a pass.
1. The flags differ in ways that can be described both **concisely** and **exhaustively**. If there are just too many differences to describe, or if some of the differences are too long to describe, it's a pass.
1. A group of similar flags forms a **complete graph** - i.e. each flag is similar to every other flag in the group. I think this is important for the user's comprehension and for our sanity as contributors (cf. example further down).

---

Alternatively, we could go ahead and specify exactly **which and how many differences** two similar flags are allowed to have to be qualified as such. For instance, knowing the following differences:

#### Critical differences
  - presence/absence of decoration (i.e. symbol, coat of arms, etc.)

#### Major differences
  - same colours in different positions (e.g. two swapped, three rotated)
  - different type of decoration but in same position (e.g. symbol vs. coat of arms)

#### Minor differences
  - different decoration of same type in same position (e.g. different symbol, different coat of arms)
  - different number of decorations of same type (e.g. fewer stars)
  - slightly different colours at same position (e.g. shade of blue, red vs. maroon, darker green, etc.)
  - slightly different geometry (e.g. width, number of serrated edges (Qatar/Bahrain), size of canton, etc.)

Two flags could then be qualified as "similar" if they had:
- one and only one critical difference;
- one major difference and zero or one minor difference;
- one or two minor differences.

I purposely didn't add "different color at specific position" to the list of differences, as I believe this is too broad and would lead to **chains of similarities** rather than groups (i.e. complete graphs) - e.g. Ireland => Italy => France => Chad/Romania => Guinea => ...

We'd have to go through existing and candidate flag similarities to finish the list of differences and iron out the rules, but I reckon it's doable. This may very well lead to some existing similarities being removed and new ones being added, but we'll have done so with a bit more of an objective approach. What do you think?

**Comment by aplaice** [comment]
I think that these guidelines are sensible.

For the cases where the similarity descriptions will be removed — e.g. that between [Thailand's](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-flag-thailand.svg) and [Costa Rica's "updated" (state, not civil)](https://github.com/axelboc/anki-ultimate-geography/blob/master/src/media/ug-flag-costa_rica.png) flags (I can't think of any others at the moment) — I think it makes sense. 

In the Thailand-Costa Rica case, while the similarity description was useful for distinguishing Thailand's flag and Costa Rica's "old" (civil, not state) flag, I don't think that anybody would confuse the current pair. (I believe that their similarity would still be useful as a mnemonic for the Country -> Flag cards, but as agreed, that's not in scope for *this* issue.)

**Comment by ohare93** [comment]
@alexboc sounds great to me! 👍 I completely agree with @aplaice

Thank you for taking the time to expand your thoughts and set some guidelines here. I think these will serve splendidly to keep us going on future flag similarity discussions 😁 

I will review my previous flag similarity entries in the light of the new guidelines at some point, whenever I have the time/drive. They are not a high priority in my mind though, so anyone please feel free to lead the charge here 👍

**Comment by axelboc** [comment]
Pheww! 😤 I've audited all existing and potential flag similarities against the rules I suggested in my [comment](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-523192823).

For starters, I decided to add a fourth difference category: **negligible differences** for those cases where the widths and/or the colours of two flags differ ever so slightly. These differences would typically not be mentioned in the flag similarity field unless they are the only differences (e.g. Romania / Chad). Here are some examples of what I mean:

- Romania / Chad, Columbia / El Salvador, Cuba / Puerto Rico => negligible colour difference
- Liberia / Malaysia => negligible width difference
- Luxembourg / Netherlands, Bahrain / Qatar => non-negligible colour difference
- Andorra / Moldova => non-negligible width difference

Without further ado, below is the full audit along with potential resolution steps. FYI, I've put the steps I think we should take in bold.

### Existing similarities

- ✔️ Andorra / Moldova => 0C 0M 2m 1n (width, coat of arms, shade of blue)
- ✔️ Australia / New Zealand => 0C 0M 2m 0n (colour of stars, number of stars)
- ✔️ Austria / Latvia => 0C 0M 2m 0n (shade of red, size of bands)
- ❌ Bahrain / Qatar => 0C 0M 3m 0n (shade of red/maroon, number of serrated edges, width)
  - **ALLOW 3m**
  - REMOVE
- ✔️ Cameroon / Senegal => 0C 1M 1m 1n (red and yellow swapped, colour of star, shades)
- ✔️ Chad / Romania => 0C 0M 0m 1n (shades)
- ✔️ Colombia / Ecuador => 1C 0M 0m 1n (presence of coat of arms, shades)
- ❌ Costa Rica / Thailand => 1C 1M ... (presence of coat of arms, colours rotated
  - **REMOVE**
- ✔️ Cuba / Puerto Rico => 0C 1M 1m 1n (red and blue swapped, width, shades)
- (✔️) Curaçao / Nauru => 0C (1M) 2m 1n (position of decoration, one vs two stars, position of middle band, shade of yellow)
  - **ADD MINOR DIFFERENCE** "same type of decoration at difference position"
- ✔️ Côte d'Ivoire / Ireland => 0C 1M 1m 0n (green and orange swapped, width)
- ✔️ Egypt / Iraq => 0C 1M 0m 0n (emblem vs text)
- ✔️ Egypt / Syria => 0C 1M 0m 0n (emblem vs two stars)
- ✔️ Egypt / Yemen => 1C 0M 0m 0n (presence of emblem)
- ✔️ Iraq / Syria => 0C 1M 0m 0n (text vs two stars)
- ✔️ Iraq / Yemen => 1C 0M 0m 0n (presence of text)
- ✔️ Syria / Yemen => 1C 0M 0m 0n (presence of stars)
- ✔️ El Salvador / Nicaragua => 0C 0M 1m 1n (coat of arms, shade of blue)
- ✔️ Galápagos Islands / Sierra Leone => 0C 0M 0m 1n (shade of blue)
- ✔️ Guinea / Mali => 0C 1M 0m 1n (red and green swapped, shade of green)
- ✔️ Faroe Islands / Iceland => 0C 1M 0m 1n (white and blue swapped, shade of blue)
- ✔️ Faroe Islands / Norway => 0C 1M 0m 0n (colours rotated, shade of blue)
- ✔️ Iceland / Norway => 0C 1M 0m 0n (red and blue swapped, shade of blue)
- ✔️ Indonesia / Monaco => 0C 0M 1m 0n (width)
- ✔️ Indonesia / Poland => 0C 1M 0m 1n (white and red swapped, shade of red)
- ✔️ Monaco / Poland => 0C 1M 1m 1n (white and red swapped, width, shade of red)
- ❌ Jordan / Palestine => 1C 0M 1m 0n (presence of star, length of triangle)
  - ALLOW 1m with 1C
  - CONSIDER presence/absence of symbol (i.e. not coat of arms, emblem or text) to be 1M rather than 1C ... _doesn't solve Jordan / Sudan_
  - **REMOVE** ... _especially considering Jordan / Sudan below_
- ❌ Jordan / Sudan => 1C 1M 1m 0n (presence of star, colours rotated, length of triangle)
  - **REMOVE**
- ✔️ Palestine / Sudan => 0C 1M 0m 0n (colours rotated)
- ✔️ Luxembourg / Netherlands => 0C 0M 1m 0n (significantly different blue)

### Potential similarities

- ❌ France / Italy => different colour in same position
- ❌ Denmark / Finland / Sweden => different colour in same position
- ❌ Hungary / Luxembourg/Netherlands/Paraguay => different colour in same position
- ❌ Isle of Man / Sicily => different geometry
- ❌ Turkey / Northern Cyprus => different geometry
- ❌ Kuwait / Palestine/Jordan/Sudan => different geometry
- ❌ Benin / Guinea-Bissau => 1C 1M 1m 1n (presence of decoration, red and green swapped, width, shades)
- ❌ Tajikistan / Hungary => 1C 0M 1m 1n (presence of decoration, wider band, shades)
  - ALLOW 1m with 1C
- ✔️ Ghana / Bolivia => 0C 1M 0m 2n (star vs coat of arms, width, shades)
  - **ADD**
- ❌ Liberia / Malaysia => 0C 0M 3m 1n (symbol, number of bands, size of canton, width)
  - **ALLOW 3m** then **ADD**
- ❌ Paraguay / Netherlands => 1C 0M 2m 0n (presence of coat of arms, width, brightness of colours)
  - ARGUE 0m 2n instead of 2m 0n then ADD
  - ARGUE 1m 1n instead of 2m 0n, ALLOW 1m with 1C, and then ADD
- ❌ Paraguay / Luxembourg => 1C 0M 1m 1n (presence of coat of arms, different blue, width)
  - ALLOW 1m with 1C then ADD
- ❌ Moldova / Romania/Chad => 1C 0M 1m 1n (presence of coat of arms, width, shade of blue)
  - ALLOW 1m with 1C then ADD
- ✔️ Andorra / Romania/Chad => 1C 0M 0m 2n (presence of coat of arms, width, shade of blue)
  - **ADD**

**Comment by aplaice** [comment]
Wow! That was thorough!

I think I agree with everything.

(Increasing the limit to 3m, to allow Bahrain/Qatar, which (in my experience) can indeed be hard to distinguish, makes sense.

I'm on the fence regarding Jordan/Palestine, but I don't actually remember confusing them, so I think I agree with your decision.)

**Comment by axelboc** [comment]
I'm having second thoughts about Andorra / Romania/Chad. If I add the similarities, then the group Andorra / Moldova /  Romania / Chad forms a graph that's not quite complete. It's a pretty arbitrary guideline, but it's worth a second though... Arguably, Andorra's blue is quite different, but is it different-enough that the difference should be categorised as non-negligible, and therefore the similarities not be added? Are the two blues more different than the two greens of Tajikistan and Hungary?

**Comment by aplaice** [comment]
> Are the two blues more different than the two greens of Tajikistan and Hungary?

Apparently, no. Using the not-exactly accurate Euclidean RGB distance between the colours (and not the fancy [CIELAB ΔE](https://en.wikipedia.org/wiki/Color_difference#CIELAB_%CE%94E*)):

```python
import math

def colour_tuple(rgb_s):
   r = int(rgb_s[1:3], 16)
   g = int(rgb_s[3:5], 16)
   b = int(rgb_s[5:7], 16)
   return (r,g,b)

def colour_difference(rgb_s1, rgb_s2):
   (r1, g1, b1) = colour_tuple(rgb_s1)
   (r2, g2, b2) = colour_tuple(rgb_s2)
   return math.sqrt((r1-r2)**2 + (g1-g2)**2 + (b1-b2)**2)

# taken from within svg
# blues
romania = '#002B7F'
andorra = '#0018a8'
chad = '#002664'

# greens
hungary = '#436F4D'
tajikistan = '#006600'

colour_difference(hungary, tajikistan)
# 102.46462804304713

colour_difference(romania, andorra)
# 45.18849411078001

colour_difference(chad, andorra)
# 69.42621983083913

# for comparison
colour_difference(romania, chad)
# 27.459060435491963
```

**Comment by axelboc** [comment]
Brilliant, I don't know why I didn't think of that. I had nothing better to do, so I adapted a spreadsheet I found online to compute DELTA E colour differences :

[Delta E calculator.zip](https://github.com/axelboc/anki-ultimate-geography/files/3552614/Delta.E.calculator.zip)

I updated [my comment above](https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-524632859) as follows:

- I added DELTA E colour differences where relevant.
- I updated the audit based on a **DELTA E threshold of 30** (less = 1n, more or equal = 1m).
- For simplicity, if a pair of flags had more than one negligible colour difference, I counted only 1n.
- I took into account the following, agreed upon changes:
  - "same type of decoration at difference position" is worth 1M
  - 0C 0M 3m make two flags similar
  - 1C 0M 1m do not make two flags similar -- so Andorra / Romania/Chad, Paraguay / Netherlands and Tajikistan / Hungary do not make the cut because of their DELTA E.
- I made the following rule change that I had forgotten to mention in the first audit:
  - 0C 1M 2m (instead of only 1m) make two flags similar -- so Cuba / Puerto Rico and Curaçao / Nauru make the cut despite their DELTA E.

If you disagree with any of these updated rules, I'll happily adjust the audit.

**Comment by axelboc** [comment]
Instead of adding 0C 1M 2m, I could alternatively adjust the threshold to 35, which would still exclude Andorra / Romania/Chad, and still include Cuba / Puerto Rico. Curacao / Nauru would be removed, though.

**Comment by aplaice** [comment]
This is amazing!

It'd be a shame to remove Curaçao / Nauru — I've confused them in the Flag -> Country cards — so I'd lean towards adding 0C 1M 2m, rather than raising the threshold (shamelessly fitting policy to achieve the right goal...).

Independently of this, I'm not sure whether the colour difference criterion should not be laxer when the colours are swapped or rotated. I know that humans are better at distinguishing colours when they're placed next to each other, than when they're shown separately. I'd guess, though I can't find any studies on this, that it's also easier to distinguish colours in separately shown images when the colours are in the same positions in the images. 

OTOH, I might just be heavily over-complicating the issue, especially since this further adjustment isn't needed to include/exclude specific pairs.

**Comment by axelboc** [comment]
I was about to add similarities for Malaysia and Liberia until I realised that, in the audit, I missed the fact that the symbols have different colours! I feel like it makes for a fourth minor difference, which means that the flags no longer qualify as similar. What to you think? To be honest, I was having trouble finding a concise, yet exhaustive-enough description of the differences...

**Comment by axelboc** [comment]
Alright, I'm done! I've documented the guidelines in [CONTRIBUTING.md](https://github.com/axelboc/anki-ultimate-geography/blob/master/CONTRIBUTING.md)

**Comment by aplaice** [comment]
Sorry for the lack of replies for so long!

`CONTRIBUTING.md` looks great!

> I was about to add similarities for Malaysia and Liberia until I realised that, in the audit, I missed the fact that the symbols have different colours! I feel like it makes for a fourth minor difference, which means that the flags no longer qualify as similar. What to you think?

I agree with your decision — I've never confused the two flags and I think that they're different enough not to need a similarity comment.
