### ISSUE TITLE
Suggestions for new note templates

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#51]
From a comment on the [shared deck's page](https://ankiweb.net/shared/info/2109889812):

> The conclusion is that, to master this deck and to have a reasonably accurate world map in my head (which is the goal, no?), I really needed to also learn cards for Country->Flag and Country->Map relations too. Adding these cards to the deck forced me to verbally explain what each country's flag looks like and what countries they border.

Very true...

### Country > Flag

If the idea is simply to display the flag in the answer, then people can create their own note template for this, like this person did. As I mention in the [README](https://github.com/axelboc/anki-ultimate-geography#guidelines), I don't think the deck should have more note templates than it already has so beginners don't feel overwhelmed.

Displaying only the flag in the answer, however, doesn't seem like it would make it easy to learn... Everyone would have to come up with their own way of describing each flag. One option could be to add a new field specifically for describing each flag in writing, in a formal (but concise) way. [Vexillology](https://en.wikipedia.org/wiki/Glossary_of_vexillology) could be an option, but it might be too obscure. Anyway, so the field would remain hidden for the user unless they create a note template for it.

### Country > Map relations (i.e. bordering countries)

This could also be a good case for a new "secret" field. It could even be used the other way around: Map relations > Country. The definition of a bordering country might be a contentious point (i.e. do you include maritime borders?)

**Comment by OnkelTem** [comment]
My few cents.

In attempts to figure out some way to remember fags, I created a hierarchical list which classifies fags by colors and similarity. E.g.:

- GWO
  - > Ireland
  - < Ivory Coast
  - < India
  - < + o Niger
- GWR
  - > Italy
  - v Iran
  - v Hungary
  - v + B Kuwait
```
etc, but this list is external to Anki. Probably "Flag similarity" can be enhanced in some way or another field can be added. 

And I liked the idea of adding some uniform terms to describe flags - e.g. from Vexillology.

But this is another more generic issue about memorizing information. Most often you don't have any associations with a country. So your brain is like a blank piece of paper. Now we add there:

**flag** + **geographical shape** + **capital**.

Are they really natural and easy to remember? What do you think about adding more associations to get better feeling of the country?

First of all, what I want to know about a country is the languages they speak!
Second - how big is their population.
Third - how rich is this country (e.g. GDP)

What do you think?


P.S. How do you edit this huge JSON? Is there a tool for this or you just use AnkiDesktop?

**Comment by code-hunger** [comment]
> But there is another more generic issue about memorizing information. Most often you don't have any associations with a country. So your brain is like a blank piece of paper. Currently we have there fields:

That's exactly the issue I wanted to address a year ago in my PR. I wanted to add short historical/cultural facts to most countries. It turned out to be quite a tedious task – by the time I added a few, I had already memorized most of the deck.

I'm not sure memorizing numbers like population/GDB will help a lot – because numbers are forgotten. Facts from the geography/history will be more useful, although much harder to find & select appropriate ones.

**Comment by OnkelTem** [comment]
> That's exactly the issue I wanted to address a year ago in my PR. I wanted to add short historical/cultural facts to most countries. It turned out to be quite a tedious task – by the time I added a few, I had already memorized most of the deck.

Yes, I was thinking about adding this too. As for the history - well it may sound little bit rude but the history of the majority of countries is more or less the same: basically they'd been killing and raping people until it became against the law — hard to remember details!

What seems to have some higher "memorizable power" — are the cultural facts: being chosen in a smart way they would come in big diversity and would barely intersect. One downside however - it's not easy to choose them without offending someone accidentally.

For example, what would be the one fact about Russia? Of course that we drink vodka a lot (yet we're not the champions - in Finland they drink even more!) And while this fact is easy to remember, it might offend someone from Russia. (I myself would prefer to be remembered as one who owns a personal bear who plays balalaika while guarding a nuclear reactor)

Another example. Today I googled for "interesting facts about countries" and the first link lead me to some "25-facts-about-...." article and their first fact was about some small island country where the most overweight population in the world live. I don't think they dream of getting such a reputation.

Probably this cultural associations game is too personal and should not be shared...

But yet I believe that some universal combination of facts can be sorted out anyway. Facts from different areas, what is more appropriate for every specific case: culture, language, geography, flora and fauna, climate, maybe a bit of history.

> I'm not sure memorizing numbers like population/GDB will help a lot – because numbers are forgotten. Facts from the geography/history will be more useful, although much harder to find & select appropriate ones.

Yep, then maybe just poor, medium rich? But this is too judgemental...

**Comment by code-hunger** [comment]
Now you understand why I have close to zero progress with my PR :) 
Maybe geography facts like "highest/lowest country in the world", "longest living population" etc. are the most acceptable even if hard to find.

**Comment by code-hunger** [comment]
> Anki power users can add a note template themselves if they wish to, but non-power users should not have to learn how to remove the note template if they don't want to learn countries' languages.

Hint: you could also release an __UG Extended__ version of the deck along the one for casual users - and not necessarily publish it on ankiweb, I guess on github it would suffice. But I agree it's best to be kept separated.

**Comment by axelboc** [comment]
Very true! Downside is if we get the translations going as well, that'd be another set of JSON files to keep in sync... But if it's just on GitHub for starters, it'd be easy to at least generate the extended decks automatically by just copying the original JSONs and adding the note templates.

That'd still be an extra step every time something changes in the deck, though... In a way, if a user is able to install CrowdAnki and import the extended deck's JSON file, they're more than capable of creating a note template, in which case, perhaps a wiki page on GitHub that explains how to add specific note templates (along with the actual template code) would suffice?

**Comment by code-hunger** [comment]
Why not release __with__ the additional templates included and the relevant cards suspended? Won't be harder for development, and will be easier for the end-users.

**Comment by axelboc** [comment]
That'd be perfect, but I don't think CrowdAnki supports outputting the suspended state of cards, unless I'm mistaken? Seems like user-specific information.

**Comment by axelboc** [comment]
Closing in favour of #71.
