### ISSUE TITLE
Translate deck to Russian

### ISSUE THREAD

**Issue by OnkelTem** [axelboc/anki-ultimate-geography#62]
Hi folks!

I started to work on Russian version of the deck.
Here is the repository: https://github.com/OnkelTem/anki-ultimate-geography-ru

Have a look at [TRANSLATE.md](https://github.com/onkeltem/anki-ultimate-geography-ru/blob/master/TRANSLATE.md) for details on the translation process.

**Comment by axelboc** [comment]
Wow, impressive process. So you use Google Translate to do the translations automatically? Is it accurate? If it is, then it's brilliant! It means we could write a script that can translate the deck into any language; we wouldn't have to keep the translated versions in the repo and update them manually.

**Comment by OnkelTem** [comment]
Google Translate is pretty accurate for countries - I would say it does its job with 90% success rate.
But for cities it's not that good, I'd estimate success rate at 70-80%. But this numbers are rather subjective. And of course the work in not done yet, I need to review translations manually.

Hold on, I'm working on something else - a deck builder. Will be ready to upload it soon. I'll keep you posted.

**Comment by OnkelTem** [comment]
Hi guys! 

(summon: @axelboc)

It's done finally. Oh, I didn't tell you what, yeah. Don't blame me, I spent so much time on this! But I couldn't resist. You'll see why.

Meet [Anki Deck Manager](https://github.com/OnkelTem/anki-dm)!

It's a beast which can just break our decks apart, pull the CSV data out of its guts, let you edit it, and build a new deck. Or many decks - it supports decks variations. And decks translations. Huh...

And the first deck built on it - Countries decks: https://github.com/OnkelTem/anki-dm-countries
No, it's not Ultimate Geography deck yet, I just wished to demonstrate/test Anki DM on something real.
Fellas, if you like it, we can migrate Ultimate Geography on it. It shouldn't be that difficult really!

**Comment by axelboc** [comment]
Brilliant!! This is just amazing. IT (re-)opens the door to so many things!

I'll definitely start the migration as soon as I can. Thanks!!

**Comment by axelboc** [comment]
Closing this as inactive. Re-opening a more generic issue for transaltions.
