### ISSUE TITLE
Translate deck to German

### ISSUE THREAD

**Issue by axelboc** [axelboc/anki-ultimate-geography#64]
Translations can be found in the [de_wip](https://github.com/axelboc/anki-ultimate-geography/tree/de_wip) branch. They'll need to be moved into the new CSV form of Anki Deck Manager and reviewed.

- [x] Move translations from JSON file in `de_wip` branch's to `data.csv` once deck is fully migrated to Anki Deck Manager. #66 
- [x] Review translations #79 
- [x] Mention German deck in README

**Comment by Erim24** [comment]
Would it help to have an additional eye on the german translations? I'm very interested on having them, so I would be willing to help in the future
Btw what do you use as source the official name? I just noticed that for example the Czech Republic is translated to Tschechien, which is the commonly used name although the official full name would be "Tschechische Republik"?

**Comment by axelboc** [comment]
Hi @Erim24! Sorry for the late reply, been swamped.

I'm thrilled that you're interested in helping out! 🎉 Please do have a look at the translations, they're in dire need of a proofread. 😄 You can fix things yourself and open a PR if you're up for it. Otherwise, just create some issues as you go and I'll be more than happy to make the changes myself.

To answer your question, for country names and capitals, we refer to the main title of their Wikipedia pages. So [Tschechien](https://de.wikipedia.org/wiki/Tschechien) is indeed correct. If we were to use official names, some countries would be very hard to memorise. If you notice an inconsistency with Wikipedia, it's most likely a mistake.

For info, fields such as _Country info_ or _Flag similarity_ are, and should remain, fairly concise and repetitive. Like in the English version, the same, consistent wording should be used across all cards. Feel free to report any inconsistencies or awkward translations.

Let me know how you go, and most importantly, thanks a lot!! 💯

**Comment by Erim24** [comment]
Hi @axelboc 
That's great. I will start proofreading this weekend. I haven't used git/github yet so I will see if I figure out how to use it to create a PR. (Should be fairly easy to figure that out though) Otherwise I will use issues.

**Comment by Erim24** [comment]
Hi @axelboc 
I managed to finish it today and created a pull request. I hope I did everything in a way it is meant to be, let me know otherwise.

**Comment by axelboc** [comment]
Amazing work, thanks again. 🙂
I'll try to release v3.1 before the end of the month.
