### ISSUE TITLE
Nouakchott typo 

### ISSUE THREAD

**Issue by chartokai** [axelboc/anki-ultimate-geography#68]
"Nouakchot" should be "Nouakchott".
The current spelling appears to be a German variant.

I wanted audio for my UG deck so I manually checked places like dictionaries for the "Country" and "Capital" fields (including many obvious ones). That's why I'm quite sure this is the last typo. If you wanted the audio, sorry, I didn't check the licences as it was for personal use.

Also, note that I'm not familiar with GitHub (I update my deck with difference checker tools and the RSS release feed).

**Comment by axelboc** [comment]
Ah good catch, thanks!

**Comment by axelboc** [comment]
Fixed in 56ca5a9ba3c93f9ab2b1aca958b3ecaf96275039
