### ISSUE TITLE
When importing version 3.0 I get some additional decks (such as Taekwondo)

### ISSUE THREAD

**Issue by omarkohl** [axelboc/anki-ultimate-geography#69]
I downloaded the release 3.0 from GitHub and imported it. I got (I think - I've deleted them since) 5 decks in total. Is this on purpose? I did not see it documented.
I also wondered why the version 3.0 from GitHub has a different size than the download from AnkiWeb. Maybe these additional decks are the reason.

**Comment by axelboc** [comment]
I must have exported all my decks, my apologies! 😖

I've updated the package on the release's page. Thanks for letting me know!
