### ISSUE TITLE
List all available country info on the back of all cards

### ISSUE THREAD

**Issue by benthor** [axelboc/anki-ultimate-geography#70]
When studying info about countries I know nothing about (Burkina Faso anyone?), it is really annoying to ONLY get the currently relevant info (e.g., Ougadougou) on the back.

Why not show every fact the deck has about each country? Then I don't have to associate two random, floating words with each other but can start learning about flag and geographic location immediately while trying to form my metal connections...

**Comment by code-hunger** [comment]
Ultimate Geography is a wonderful deck and will help you a lot, but it has some (easily resolvable) issues like the one you encountered.

Before you start with this deck I'd recommend you to learn, or at least get familiar with where all countries are located using some other apps that are better suited for such questions.

I used an android app that gave me a country name/capital/flag and a map with only outlines, and told me to find the respective state on the map. Unfortunately it is no longer available on the android store, so you'd have to find another one; or, if you use an Apple device, I see the app is still on the Apple store, named "World Map Quiz".

What Ultimate Geography offers is the SRS supported by Anki. You probably won't find any geography-teacher app as simple and non-distracting and as powerful as Anki, so you definitely should use it if you want to keep the individual pieces of data in your head fresh.

But before that, you must learn the locations on the world map. Not a part of it, not in a specific region, but on the whole map. It will take you about a few days to learn them all, depending on your prior knowledge and the time you invest, but you should do it. Also, it's much easier to learn (the first few times) locations interactively than from a cut off image of a map.

UG will teach you all facts, and will keep them fresh in your memory, but you're better off with an initial boot. Good luck!

**Comment by axelboc** [comment]
Yeah, starting on the whole deck without a strong foundation is probably not the best way to go. Personally, I learnt flags through a couple of multiple-choice quiz games on Facebook... 😄 For locations, I remember using a software where I could select a continent and then try to locate each country.

Anki is not quite as fun... :D As @code-hunger mentioned, it's really more for drilling facts into your brain. What you could try, though, is to create filtered decks [as explained in the README](https://github.com/axelboc/anki-ultimate-geography#custom-study). You could start, for instance, with the 206 maps of the sovereign states, or even narrow that down further to a specific continent. Proceeding step by step will make mastering the whole deck a lot more achievable.

I'm closing this issue as `wontfix`, but if you need any help with creating filtered decks or whatever, let us know. Good luck !
