### ISSUE TITLE
Errors when importing version 3.0

### ISSUE THREAD

**Issue by thompsy** [axelboc/anki-ultimate-geography#77]
Hi, when importing a fresh version of 3.0 I get the following errors with Anki v2.1.5 and addons disabled. The result is that I'm left with a deck of only 199 cards.

## 1. Error when Importing
This is an error that pops up immediately upon importing the deck:
```
Updated 0 of 226 existing notes.
Some updates were ignored because note type has changed:
Map: New Zealand,,Wellington,,,<img src="ug-flag-new_zealand.svg" />,Australia (white stars, two more stars),<img src="ug-map-new_zealand.png" />
869 cards imported.
```
## 2. Viewing the newly imported deck in the browser
When I open the browser immediately after importing I get the following error:
```
Error 
An error occurred. Please use Tools > Check Database to see if that fixes the problem. 
If problems persist, please report the problem on our support site. Please copy and paste the information below into your report.
Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=False sv=1

Caught exception:
  File "aqt\browser.py", line 81, in data
  File "anki\cards.py", line 151, in template
<class 'IndexError'>: list index out of range
Caught exception:
  File "aqt\browser.py", line 96, in data
  File "aqt\browser.py", line 241, in columnData
  File "anki\cards.py", line 151, in template
<class 'IndexError'>: list index out of range
.... snip lots of repeated entries of the same errors ....
```

## 3. When running 'Check Database'
As suggested by the previous error message I then run a 'Check Database' and this produces the following output:
```
Deleted 670 cards with missing template.
Database rebuilt and optimized.
```

At this point I only have 199 cards remaining in the imported deck. The rest have been deleted or ignored.
Any help would be much appreciated. 
Thanks

**Comment by thompsy** [comment]
Interestingly, if I create a new profile, the import works fine, but on my existing profile (I've got a few other home-made decks) it gives the errors above.

**Comment by axelboc** [comment]
Hi! Had you installed the deck before and then maybe deleted it? If so, perhaps the old note type was still present. Did you try [the steps](https://github.com/axelboc/anki-ultimate-geography#major-version) listed in the README to upgrade to a major version?

**Comment by thompsy** [comment]
I didn't think I had installed it before but I followed the steps you pointed to and it imported fine!

Thanks for your help :-)

**Comment by axelboc** [comment]
No worries! Perhaps you had tried the [original Ultimate Geography deck](https://ankiweb.net/shared/info/261823898) at some point. Anyway, glad I could help 🙂
