### ISSUE TITLE
How can I tell which version of the deck I have?

### ISSUE THREAD

**Issue by stianlagstad** [axelboc/anki-ultimate-geography#78]
Hey Axel,

Thank you very much for your work on this deck!

I'd like to upgrade the version of the deck that I'm using, becaues I don't think I have the most recent one. I might be missing something obvious, but how exactly can I tell which version of the deck I have?

![screenshot from 2018-12-07 18-39-54](https://user-images.githubusercontent.com/4340859/49663683-b58bd280-fa4f-11e8-84f4-4e0f8bec08a7.png)

**Comment by axelboc** [comment]
That's a excellent question! 😄 I'm afraid the version is only mentioned on the [shared deck's page](https://ankiweb.net/shared/info/2109889812). Do you remember when you downloaded it last?

Either way, I'll make sure to add the version number to the deck's description in the next release.

**Comment by stianlagstad** [comment]
Thank you, @axelboc!
