### ISSUE TITLE
Luxembourg Capital is Wrong(?)

### ISSUE THREAD

**Issue by ohare93** [axelboc/anki-ultimate-geography#80]
The deck states that the Capital of Luxembourg is "Luxembourg", which is technically correct as far as I can see. However it is better known in English as "Luxembourg City".

**Comment by axelboc** [comment]
You're totally right, the title of the Wikipedia page is indeed "Luxembourg City". I'll make the change asap. Thanks!

**Comment by axelboc** [comment]
I've left the German translation as is, since the Wikipedia page has so far not been renamed.
