### ISSUE TITLE
How do I update the deck?

### ISSUE THREAD

**Issue by PurpleManners** [axelboc/anki-ultimate-geography#93]
Hi,

Sorry if this is not the right forum for this question. I downloaded de Ultimate Geography deck sometime in 2017 or 2018, and now I understand it has ben updated. So is it possible for me to update my deck with those new additions, without deleting all the studying-data (I have been studying and reviewing the cards for 1+ year).

Thanks!

**Comment by stianlagstad** [comment]
There are instructions for upgrading the deck [in the readme page here](https://github.com/axelboc/anki-ultimate-geography#upgrading). :)

**Comment by PurpleManners** [comment]
So there's definitely no way of updating without loss of progress? :/

**Comment by axelboc** [comment]
I'm afraid not, sorry 😢 ... Perhaps it's a good opportunity to see how fast you can go through all the cards again!? 😆 In all seriousness, it was a tough choice to make, but it was worth it. Now that each card has a unique identifier that we control, it's unlikely that future updates will ever cause a loss of progress again. I'm closing the issue, but don't hesitate if you have any questions regarding the upgrade.
