### ISSUE TITLE
Mistake? Gulf of Carpentaria

### ISSUE THREAD

**Issue by Incorporated95** [axelboc/anki-ultimate-geography#94]
I think it might be "Gulf of Carpent**a**ria" not "Gulf of Carpent**e**ria". I am not Australian. Maybe there are multiple spellings?
![image](https://user-images.githubusercontent.com/47544162/58010920-93fc4000-7af1-11e9-89f2-52213c6a0213.png)

**Comment by axelboc** [comment]
This typo should be fixed in v3.1 https://github.com/axelboc/anki-ultimate-geography/releases/tag/v3.1 😊

**Comment by Incorporated95** [comment]
Oh. I didn't see that. I updated now.

BTW
Thank you so much for your work with this deck. It is great!
