### ISSUE TITLE
Sort countries by size or population

### ISSUE THREAD

**Issue by Bazalia** [axelboc/anki-ultimate-geography#96]
Is it possible to sort the cards by population or size of country. As it is right now the first countries that I got to learn were some tiny countries or states that I never heard of. This felt demotivating as it didn't seem like I'm learning anything useful. Perhaps if the deck starts with bigger countries and then slowly overtime moves towards less known ones then it is easier to follow through.

**Comment by code-hunger** [comment]
Until a better solution is suggested, you can filter by sovereign states and study them first.
Or you can choose a single continent and study only countries near you.

**Comment by axelboc** [comment]
Sorry @Bazalia, for the time being, Anki doesn't allow decks to be sorted. New cards are always scheduled at random. You do have a couple of options, though:

- As @code-hunger mentioned, you can create **filtered decks** to narrow down the cards you'd like to study first. Check out the _[Custom study](https://github.com/axelboc/anki-ultimate-geography#custom-study)_ section in the README for more info.
- While you study, you can also make use of Anki's [**Suspend note** feature](https://github.com/axelboc/anki-ultimate-geography#custom-study) to hide notes that are too hard until you're ready for them.

I'm closing this issue, but let us know if you need any help. Good luck!
