### ISSUE TITLE
In the EXTENDED version, seas that have no flags have Flag -> Country cards

### ISSUE THREAD

**Issue by viivgit** [axelboc/anki-ultimate-geography#98]
Everthing is the title: so for instance there is a card with nothing on its front, and the back is the Adriatic Sea.
Actually if you browse the deck you can see that a Flag->Country card has been created for seas. So it makes sense since a sea has no flag, that the Flag->Country card is empty on its front.

But this bug was not here in the normal version of the deck where seas don't have a Flag->Country card (and for a reason) so these cards should not be created.

This should be taken care of when building the EXTENDED deck, I guess with a kind of filter.

P.S.: I followed the instruction on the presentation page, and did not change any option on import.
<img width="597" alt="bug Ultimate Geography seas" src="https://user-images.githubusercontent.com/34168892/60627803-8d9afc80-9def-11e9-9fa8-b3ca2cecaf17.png">

**Comment by axelboc** [comment]
The extended deck's configuration and its generated JSON file both look fine. On import, Anki is supposed to automatically skip generating cards with empty front sides. I can't figure out why this is not working in this specific case.

Can you see any other card with empty front sides at all?

**Comment by viivgit** [comment]
I checked and it is just the seas and continents too actually (Africa, Polynesia, etc...), which is consistent  because continents also have no flags, so they shouldn't have a Flag->Country card created.

Maybe you could try to follow the same steps I did and create the deck from scratch in a different Anki profile and see if you can reproduce?

Steps I followed:
1) I download the files from the Release page, for version 3.1.
2) I double click on the apkg to import it in Anki, it creates 319 notes I believe.
3) I unzip the .zip of the extended package.
4) Then in Anki, I click on the "CrowdAnki: Import from disk" option and select the subfolder "Ultimate Geography [Extended]" and click import.
5) The window telling me what it's going to do pops up and I change nothing, click yes, wait a minute for processing, and it's done.

**Comment by axelboc** [comment]
Sorry for the delay. I've tried importing the extended English deck in a fresh Anki profile and I'm not seeing any cards with empty fronts! The only difference is I didn't import the normal deck first; I just imported the extended deck directly. Perhaps that's what's causing the issue?

**Comment by viivgit** [comment]
Indeed, if I do what you say and do not import first the other deck, it doesn't happen.
I guess I got confused by the guidelines.
Having just read them again, they are actually not confusing, BUT if you already happen to have the normal deck in your Anki profile (I would say this is a likely oportunity), and just want to test and see the Extended version, then this bug will happen.
So maybe there is something to do on that side, either fix that bug or put a mention in the README section about the other decks?

Also side note: it is written in the README that the normal deck has 1097 cards, but I believe it is now only 1096.

**Comment by axelboc** [comment]
Good call, I've added a note to the [_Other languages and versions_](https://github.com/axelboc/anki-ultimate-geography#other-languages-and-versions) section of the README. I've also updated the number of cards, thanks for that!

For info, I've tested importing the German deck on top of the English deck and that worked fine. Good to know.
